### ISSUE TITLE
[BUG] Missing viAlias and vimAlias documentation

### ISSUE THREAD

**Issue by covert8** [nix-community/nixvim#1002]
The viAlias and vimAlias options are not being rendered on the documentation site.

[wrappers](https://github.com/nix-community/nixvim/tree/079c03228c20c9cf49ab4dda2aa65fc27233fc53/wrappers)/[modules](https://github.com/nix-community/nixvim/tree/079c03228c20c9cf49ab4dda2aa65fc27233fc53/wrappers/modules)
https://nix-community.github.io/nixvim/CONTRIBUTING.html?search=viAlias

**Comment by traxys** [comment]
Yeah there are a number of options that are not automatically picked up, we should improve on that
