### ISSUE TITLE
[FEATURE/QUESTION] Extract config for non NixOs/Nix capable system

### ISSUE THREAD

**Issue by atropos112** [nix-community/nixvim#1005]
Howdy, 

I am sorry for writing here, i am not sure this is the place to ask such question but been trying to figure this out am sure where else to ask.

I have gotten into using vim as my editor of choice, slowly moving off vs-code, at work I was given a mac and was shown a list of applications I am allowed to install, it's a finance sector so the list is not super big but NeoVim is there, sadly Nix is not. 

I was wondering if there is a way for me to extract the lua/vim-config somehow so that I can copy it across to the work machine rather than writing it from scratch, this solution isn't perfect for plethora of reasons, but given I can't have Nix there it seems like the "best" approach, sadly I am not at all sure how I can extract such files. Any suggestion how I can go about such thing ?

--- EDIT

Through some grepping i was able to find an `...-init.lua` file in `/nix/store` to then realise the plugins are not there if i try to use that config via `~/.config/nvim/init.lua`, I suspect the approach on a non-nix device is
1. Find `/nix/store/...-init.lua` 
2. Adapt it by removing the `vim.opt.runtimepath:remove(vim.fn.stdpath('config'))              -- ~/.config/nvim` line
3. Figure out what plugins need to be installed, install them and load them on top of the init.lua file I copied form /nix/store
4. Party?
Is it naive of me to expect this to work in the future?

**Comment by traxys** [comment]
There are some ways to do it:
- The simplest is to instantiate normally your nixvim configuration and then use `nixvim-print-init` command to get the contents of the init.lua
  You will then need to manually add a way to bundle the plugins.
- The next way you can do it is by creating a standalone nix derivation that does the same as above, but automatically. This could be a bit more involved as you need to write some nix code, but you could automate the plugin registrations.

**Comment by traxys** [comment]
the `nixvim-print-init` way should never break, as we will maintain the command even if we refactor things.
The other method should not break either, but as it touches at implementation details if we do a deep refactor it could change a bit

**Comment by siph** [comment]
`nixvim-print-init` should probably have some way of passing `--plain` to `bat` to remove the extra decorations. It would make it easier to automate reading the config.

**Comment by atropos112** [comment]
That explains my question thank you!

**Comment by traxys** [comment]
> `nixvim-print-init` should probably have some way of passing `--plain` to `bat` to remove the extra decorations. It would make it easier to automate reading the config.

`bat` will omit decorations when piped/redirected
