### ISSUE TITLE
[PLUGIN REQUEST] Transparent.nvim

### ISSUE THREAD

**Issue by W-Y-R** [nix-community/nixvim#1026]
| Field    | Description |
|----------|-------------|
| Plugin   | `transparent.nvim`  | 
| Homepage | `https://github.com/xiyaowong/transparent.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information

This plugin is meant to remove all background colors from neovim, making it transparent. For making it more declarative, however, it should also include an **"autoStart"** option.

**Comment by Bodleum** [comment]
[Nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/294008)
