### ISSUE TITLE
[BUG] error about unsupport attributes

### ISSUE THREAD

**Issue by chadcatlett** [nix-community/nixvim#1042]
| Field        | Description |
|--------------|-------------|
| Plugin       | n/a  | 
| Nixpkgs      | unstable | 
| Home Manager | unstable | 

## Description

Unable to set clipboard.register value since PR #1041 was merged. If I go to the commit prior to 1041 it works.

I get an error like this:
```
error: Module `:anon-9:anon-1' has an unsupported attribute `clipboard'. This is caused by introducing a top-level `config' or `options' attribute. Add configuration attributes immediately on the top level instead, or move all of them (namely: clipboard editorconfig enable extraPlugins globals keymaps plugins) into the explicit `config' attribute.
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
clipboard.register = "unnamedplus";
}
```

**Comment by GaetanLepage** [comment]
@roberth looks like it was needed somehow ^^
