### ISSUE TITLE
[BUG] `nixvim.highlight` does not work?

### ISSUE THREAD

**Issue by mrtnvgr** [nix-community/nixvim#1051]
| Field        | Description |
|--------------|-------------|
| Plugin       | `none`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

## Description

![20240210_15h58m24s_grim](https://github.com/nix-community/nixvim/assets/48406064/99399692-11df-472d-a154-4bc383e6be3c)
![20240210_15h58m38s_grim](https://github.com/nix-community/nixvim/assets/48406064/32312193-5549-4c73-a636-788dae561708)
![20240210_15h59m08s_grim](https://github.com/nix-community/nixvim/assets/48406064/a1e45cfc-924a-4c40-82a0-c07c9f719055)

`:hi! link @comment.todo DiagnosticInfo`fixes the issue:
![20240210_16h00m30s_grim](https://github.com/nix-community/nixvim/assets/48406064/3c9e53f0-8a6a-4eb4-b65a-4f0441bff034)

Snippet from generated `init.lua`:
```lua
vim.loader.enable()
-- Highlight groups {{
do
  local highlights = {["@comment.danger"] = {["link"] = "DiagnosticError"},["@comment.hint"] = {["link"] = "DiagnosticHint"},["@comment.todo"] = {["link"] = "DiagnosticInfo"},["@comment.warning"] = {["link"] = "DiagnosticWarn"},["NormalFloat"] = {["bg"] = "NONE"},["Pmenu"] = {["bg"] = "NONE"}}

  for k,v in pairs(highlights) do
    vim.api.nvim_set_hl(0, k, v)
  end
end
-- }}
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.comment-nvim.enable = true;
  highlight = {
    "@comment.todo".link = "DiagnosticInfo";
    "@comment.hint".link = "DiagnosticHint";
    "@comment.warning".link = "DiagnosticWarn";
    "@comment.danger".link = "DiagnosticError";
  };
}
```

**Comment by khaneliman** [comment]
https://github.com/nix-community/nixvim/pull/1036/files implemented an override for existing highlights that get declared by something else and need to be overwritten. The highlights option is declared at beginning of the config so new highlight groups can be used by the rest of the config.
