### ISSUE TITLE
[BUG] mkTestDerivationFromNvim fails for image.nvim

### ISSUE THREAD

**Issue by MartinEekGerhardsen** [nix-community/nixvim#1085]
| Field        | Description |
|--------------|-------------|
| Plugin       | `image`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `<VERSION>` | 

## Description

The `image.nvim` plugin breaks the `mkTestDerivationFromNvim` function in the build phase. This is due to a failure to get the current terminal size. I'm not too familiar with the `mkTestDerivationFromNvim` function, but I expect it tries to load the `image.nvim` plugin in a headless mode, which would obviously fail to get the terminal size. 

The function which fails is on [this line](https://github.com/3rd/image.nvim/blob/4c6cb5ad93ee93d8d7b7c84e1eb291cee99f0a0e/lua/image/utils/term.lua#L34), where the [`ioctl`](https://www.man7.org/linux/man-pages/man2/ioctl.2.html) function is called. In the same file, the function which calls `ioctl` is called as part of the `term.lua` file [here](https://github.com/3rd/image.nvim/blob/4c6cb5ad93ee93d8d7b7c84e1eb291cee99f0a0e/lua/image/utils/term.lua#L46C2-L46C3). 

This means that when this file is included in while this plugin is loaded, this function is called and we get an assert error. 

I think this would be best to solve in the `image.nvim` plugin itself, but I figured I'd create the issue here first as this was how I found it. 

## Minimal, Reproducible Example (MRE)

For simplicity, start with the standalone example: 
```bash
mkdir /tmp/test-config
cd /tmp/test-config
nix flake init --template github:nix-community/nixvim
```

From here, `nix flake check .` works as expected.

Then add to `config/default.nix`:
```nix
plugins.image.enable = true;
```

Now `nix flake check .` will break with a log similar to this:

```
@nix { "action": "setPhase", "phase": "patchPhase" }Running phase: patchPhase@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
ERROR: Error detected while processing /nix/store/4ccnws6j00gwma81nzhaygg76w85c782-init.lua:
E5113: Error while calling lua chunk: ...NeovimPackages/start/image.nvim/lua/image/utils/term.lua:34: Failed to get terminal size
stack traceback:
        [C]: in function 'assert'
        ...NeovimPackages/start/image.nvim/lua/image/utils/term.lua:34: in function 'update_size'
        ...NeovimPackages/start/image.nvim/lua/image/utils/term.lua:46: in main chunk
        [C]: in function 'require'
        ...NeovimPackages/start/image.nvim/lua/image/utils/init.lua:7: in main chunk
        [C]: in function 'require'
        ...myNeovimPackages/start/image.nvim/lua/image/renderer.lua:2: in main chunk
        [C]: in function 'require'
        ...ck/myNeovimPackages/start/image.nvim/lua/image/image.lua:2: in main
```

**Comment by MartinEekGerhardsen** [comment]
As an aside, which could actually be a `nixvim` bug, while trying to debug this issue I forked `image.nvim` and added a non-flake input to this test config. Then I change `config/default.nix` like this: 

```nix
{
pkgs,
inputs,
...
}:
{
  # Import all your configuration modules here
  imports = [
    ./bufferline.nix
  ];

  plugins.image = {
    enable = true;
    package = let
      image-nvim = pkgs.vimUtils.buildVimPlugin {
        name = "image.nvim";
        src = inputs.image-nvim;
      };
    in image-nvim;
  };
}
```

Now when I run `nix run .#`, I get this error:

```
Error detected while processing /nix/store/7n4hrzs3kv68r5mr22xbyxb695hb4dpy-init.lua:
image.nvim: magick rock not found, please install it and restart your editor
```

If I comment out the overwritten package (such that I get the nixpkgs version), I get no error. As far as I understand the `nixvim` implementation of `plugins.image`, this should be available either way?

**Comment by traxys** [comment]
It may be that the master image.nvim has changes from the nixpkgs one. The other posibility is that image.nvim has nixpkgs overrides. I would consider doing `pkgs.vimPlugins.image-nvim.overiddeAttrs (_: { src = ipnuts.image-nvim; })`, that would handle the second case.

**Comment by MartinEekGerhardsen** [comment]
Thanks, adding that override solved that issue! I expect using an autocmd on `UIEnter` around the functions which actually requires the UI to be available should solve this. I'll open an issue on the `image.nvim` plugin repo.

**Comment by MartinEekGerhardsen** [comment]
There seems to be several places where this plugin assumes we are not in a headless mode, so I think there might not be a simple way to fix this. Is there a way to just remove this plugin when I run `nix flake check .`, without removing it for my actual config?

**Comment by traxys** [comment]
There should be a way to disable running the tests in nixvim

**Comment by traxys** [comment]
We _should_ have disabled it:
```
  empty = {
    # At runtime, the plugin tries to get the size of the terminal which doesn't exist in the
    # headless environment.
    tests.dontRun = true;

    plugins.image.enable = true;
  };
```

**Comment by traxys** [comment]
Ah I see your issue, you are trying to use it for your own config. That's an issue I had not yet considered!

**Comment by traxys** [comment]
You may want to disable image.nvim while running in the test derivation. I'll think of a way to do it automatically though.

**Comment by MartinEekGerhardsen** [comment]
Yeah, is there a way to override the config set from the result of makeNixvimWithModule?

**Comment by traxys** [comment]
With #1095 there is now a way to handle this! I updated the template at https://github.com/nix-community/nixvim/blob/main/templates/simple/flake.nix if you want an example on how to make this work

**Comment by MartinEekGerhardsen** [comment]
Thank you for the quick work! I tried to update my flake based on this, if I update my flake and do these changes, should it work?

```
diff --git a/flake.nix b/flake.nix
index 76479c7..727074f 100644
--- a/flake.nix
+++ b/flake.nix
@@ -50,7 +50,8 @@
       }: let
         nixvimLib = nixvim.lib.${system};
         nixvim' = nixvim.legacyPackages.${system};
-        nvim = nixvim'.makeNixvimWithModule {
+
+        nixvimModule = {
           inherit pkgs;
           module = config;
           # You can use `extraSpecialArgs` to pass additional arguments to your module files
@@ -59,6 +60,8 @@
             inherit inputs;
           };
         };
+
+        nvim = nixvim'.makeNixvimWithModule nixvimModule;
       in {
         _module.args.pkgs = import nixpkgs {
           inherit system;
@@ -72,10 +75,7 @@

         checks = {
           # Run `nix flake check .` to verify that your config is not broken
-          default = nixvimLib.check.mkTestDerivationFromNvim {
-            inherit nvim;
-            name = "A nixvim configuration";
-          };
+          default = nixvimLib.check.mkTestDerivationFromNixvimModule nixvimModule;
         };

         packages = {
```

I tried this and get the same error. Or should I use `helpers.enableExceptInTests` to enable the `image` plugin as well?

**Comment by traxys** [comment]
Exatcly!

**Comment by MartinEekGerhardsen** [comment]
Works perfectly, thank you!
