### ISSUE TITLE
[BUG] `coq-thirdparty` is missing `acceptKey` option and string cases don't match with example

### ISSUE THREAD

**Issue by wvffle** [nix-community/nixvim#1113]
| Field        | Description |
|--------------|-------------|
| Plugin       | `coq-thirdparty`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

## Description

In the example listed under [plugins.coq-thirdparty.sources](https://nix-community.github.io/nixvim/plugins/coq-thirdparty/sources.html#pluginscoq-thirdpartysources), there are two errors:
- `acceptKey` is not handled by nixvim
- `shortName` is actually `short_name`

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.coq-nvim.enable = true;
  plugins.coq-thirdparty = {
    sources = [{
      acceptKey = "<c-f>";
      shortName = "COP";
      src = "copilot";
    }];
  };
}
```

**Comment by traxys** [comment]
We are using a freeform type for the sources, so you should be able to add any keys you want like. Though I think we lack some documentation on freeform types, we need to improve in that regard.
