### ISSUE TITLE
[BUG] Example for plugins.gitsigns.onAttach is wrong / confusing

### ISSUE THREAD

**Issue by gbirke** [nix-community/nixvim#1116]
| Field        | Description |
|--------------|-------------|
| Plugin       | `gitsigns`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

## Description

The example for the `onAttach` option of the `gitsigns` plugin in the documentation looks like this:

```
''
  {
    function = \'\'
      function(bufnr)
        if vim.api.nvim_buf_get_name(bufnr):match(<PATTERN>) then
          -- Don't attach to specific buffers whose name matches a pattern
          return false
        end
        -- Setup keymaps
        vim.api.nvim_buf_set_keymap(bufnr, 'n', 'hs', '<cmd>lua require"gitsigns".stage_hunk()<CR>', {})
        ... -- More keymaps
      end
    \'\'
  }
''
```

That makes it look like the option should be assigned a multiline string (which of course will fail when building). The documentation says that it should be `null` or a submodule, but as a very inexperienced Nix user I was confused, because I did not know how the submodule is supposed to look.

A better way to display the example could look like this:

```
{
  onAttach.function = ''
      function(bufnr)
        if vim.api.nvim_buf_get_name(bufnr):match(<PATTERN>) then
          -- Don't attach to specific buffers whose name matches a pattern
          return false
        end
        -- Setup keymaps
        vim.api.nvim_buf_set_keymap(bufnr, 'n', 'hs', '<cmd>lua require"gitsigns".stage_hunk()<CR>', {})
        ... -- More keymaps
      end
  ''
}
```

**Comment by GaetanLepage** [comment]
Thanks for reporting !
Fixed by https://github.com/nix-community/nixvim/pull/1266

Assigning a (multiline) string to `settings.on_attach` directly now works fine.
