### ISSUE TITLE
[BUG] attribute 'base16-nvim' missing

### ISSUE THREAD

**Issue by GiyoMoon** [nix-community/nixvim#1130]
| Field        | Description |
|--------------|-------------|
| Plugin       | `base16`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `24.05` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When trying to set up nixvim, I encountered the following error:

<img width="1087" alt="image" src="https://github.com/nix-community/nixvim/assets/36984337/5f1e1ac7-9c76-47e4-b127-73cb58c192f1">

I don't have anything special configured, just `programs.nixvim.enable = true`

It seems to be related to 08f3289d34ef8b69cb2da768cb80777fe5a7f076.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
}
```

**Comment by GaetanLepage** [comment]
Hi !
Thank you for reporting.
This issue is known and you can find more information in https://github.com/nix-community/nixvim/issues/1112.

**Comment by GiyoMoon** [comment]
Thanks! Switching from `nixos-unstable` to `nixpkgs-unstable` worked.
