### ISSUE TITLE
plugins/whichkey: Support window and layout fields

### ISSUE THREAD

**Issue by alexpetrean80** [nix-community/nixvim#1167]
In lua `wc.setup` can take some optional parameters that can change the way the helper looks, e.g.
```lua
wc.setup({
  window = { margin = {1, 0, 0, 0.8 }, border = "single"},
  layout = { height = {min = 4, max = 150}, align = "left" },
})
```
That seem to be missing from nixvim.plugins.which-key and they would be nice to have.

**Comment by alexpetrean80** [comment]
After looking over  `plugins/utils/which-key` I realised the options exist, they are just not documented.

**Comment by khaneliman** [comment]
Closing as supporting plugin's options in https://github.com/nix-community/nixvim/pull/1990 and also allowing undocumented
options.
