### ISSUE TITLE
[PLUGIN REQUEST] <auto-save fork>

### ISSUE THREAD

**Issue by w4krzw9N8aIvT8cdEFd** [nix-community/nixvim#1171]
| Field    | Description |
|----------|-------------|
| Plugin   | [auto-save fork link](https://github.com/okuuva/auto-save.nvim)
| Homepage | [auto-save fork link](https://github.com/okuuva/auto-save.nvim)     | 
| Nixpkgs  | [PACKAGE](https://search.nixos.org/packages?channel=unstable&show=vimPlugins.auto-save-nvim&from=0&size=50&sort=relevance&type=packages&query=auto-save)

## Extra Information
So, there is already an auto-save plugin; however, it seems that it has been forked, and the fork is 40 commits ahead of pocco81/auto-save.nvim:main. Perhaps this might be prudent to include?

**Comment by GaetanLepage** [comment]
Hey,
It seems that [`vimPlugins.auto-save-nvim`](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=auto-save-nvim) is indeed already pointing at the updated fork.
Do the nixvim options for this plugin need a refresh though ?
