### ISSUE TITLE
nord colorscheme not starting on launch due to `colorscheme` not set when `colorschemes.nord.enable = true;`

### ISSUE THREAD

**Issue by stepbrobd** [nix-community/nixvim#1189]
| Field        | Description |
|--------------|-------------|
| Plugin       | `nord`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

nord was switched to `mkVimPlugin` but it should be `colorscheme`

introduced in: https://github.com/nix-community/nixvim/commit/be87309e0c1da19d99d969625300aaed36ff1b91

related issue: https://github.com/nix-community/nixvim/issues/941

**Comment by GaetanLepage** [comment]
In what sense is it broken ?
The current implementation should not have a different effect than the previous one, which is to set some global values (`vim.g.nord_*`). Was it doing something more before ? Should it do something differently ?

We now use the `mkVimPlugin` helper but [the `namespace` is properly set to `colorschemes`](https://github.com/nix-community/nixvim/blob/5eae22d14eb1c4e0670fed8753b8ae88fe8e3a58/plugins/colorschemes/nord.nix#L9).

**Comment by stepbrobd** [comment]
Ah, this is caused by `colorscheme = "nord";` was removed in [this commit](https://github.com/nix-community/nixvim/commit/be87309e0c1da19d99d969625300aaed36ff1b91)

Thus, in https://github.com/nix-community/nixvim/blob/main/modules/colorscheme.nix#L17, `colorscheme` is not set, causing nord not starting on launch

**Comment by GaetanLepage** [comment]
> Ah, this is caused by `colorscheme = "nord";` was removed in [this commit](https://github.com/nix-community/nixvim/commit/be87309e0c1da19d99d969625300aaed36ff1b91)
> 
> Thus, in https://github.com/nix-community/nixvim/blob/main/modules/colorscheme.nix#L17, `colorscheme` is not set, causing nord not starting on launch

Indeed, thanks for finding out this bug !

**Comment by stepbrobd** [comment]
I'm not sure if the `mkVimPlugin` rewrite affected other colorschemes plugins tho, it might be better to take another look for those plugins
