### ISSUE TITLE
[BUG] some none-ls servers have no nixpkgs sources configured

### ISSUE THREAD

**Issue by atimofeev** [nix-community/nixvim#1210]
| Field        | Description |
|--------------|-------------|
| Plugin       | `none-ls`  |
| Nixpkgs      | `unstable` |

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Some of None-ls servers are marked as if they have no sources present in nixpkgs:
https://github.com/nix-community/nixvim/blob/5293373732f51f83017484831bc26365caecd965/plugins/none-ls/servers.nix#L239

Which is not true for these servers at least:
- nixpkgs/package/yamlfix
- nixpkgs/package/nodePackages.fixjson
- nixpkgs/package/nodePackages.jsonlint

## Minimal, Reproducible Example (MRE)
```nix
programs.nixvim.plugins.none-ls = {
  enable = true;
  sources = {
    diagnostics  = {
      jsonlint.enable = true;
    };
    formatting = {
      yamlfix.enable = true;
      fixjson.enable = true;
    };
  };
};
```

**Comment by GaetanLepage** [comment]
You are right.
I added them to the list in https://github.com/nix-community/nixvim/pull/1211.

**Comment by traxys** [comment]
Yeah sorry I tried to get every one of them, but there are _a lot_ of sources
