### ISSUE TITLE
feature: keymaps action should be optional

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1214]
Currently, which-key descriptions are automatically added for any keymap that defines `options.desc`, however to set a description for a "group" you must use `plugins.which-key.registrations` directly, which leads to (potentially related) keymap descriptions being declared in totally separate parts of a config.

If keymap's `action` was allowed to be `null`, then this could be used to register descriptions without defining an actual keymap.

You would need to manually assert that _at least one of_ `action` and `options.desc` is non-null, panicking if both are `null`.

**Comment by GaetanLepage** [comment]
This is the behavior we had before.
We removed it when adding the aforementioned `plugins.which-key.registrations` option.

That being said, I get your point. I have no major reason to oppose this change.
What do you think @traxys ?

**Comment by MattSturgeon** [comment]
I don't feel strongly about this either. It just felt strange that you can use `keymaps` to register _most_ of your key descriptions, but not all.

Looking ahead, _if_ this is accepted _and_ plugin-specific keymaps get refactored to be consistent with `keymap`, perhaps `plugins.which-key.registrations` would become redundant and end up being deprecated?

**Comment by GaetanLepage** [comment]
Actually, I remember now.
We used to allow this behavior but [decided to remove it](https://github.com/nix-community/nixvim/pull/605/commits/2b4456317a3c56f1e34f395f48108cc7a7b42b85).
Basically, 1 entry in the `keymaps` option leads to one call of `vim.keymap.set`.
The latter does not support `nil` `rhs` argument. Hence, the behavior for specifying a keymap without an action does not make sense (if you forget about `which-key`.
We (at least I) don't want our core `keymaps` option to depend on a third-party plugin.
