### ISSUE TITLE
feature: keymap aliasing

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1215]
Currently if you wish to have multiple keymaps that do the same thing, you must either duplicate your definition for each alias or `map` a list of alias strings into a list of keymap attribute sets.

It may be handy to provide an `aliases` option accepting `null`, `str` or `listOf str`. If used, the keymap will be created for `key` as well as each `alias`.

If this is considered unnecessary feature bloat, perhaps document an example somewhere (README, Wiki, or docs) demonstrating how `map` can be used to produce duplicate keymaps?

**Comment by MattSturgeon** [comment]
@traxys this is probably wontfix for the same reason as #1214?

I guess, at most, the scope of this issue could be reduced to documenting an example of mapping a list of string-keys into multiple keybinds.

If you think such an example adds more value than confusion...

**Comment by traxys** [comment]
Yeah I think like #1214 this is a bit out of the scope of nixvim.

**Comment by traxys** [comment]
But we could add a section Tips & Tricks to the user guide were we could add Nix snippets to do stuff like this (and maybe to simulate something like #1214)
