### ISSUE TITLE
feature: option to enable refactor.nvim's telescope extension

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1218]
[refactoring.nvim](https://github.com/ThePrimeagen/refactoring.nvim) includes a Telescope extension that can be enabled using

```nix
extraConfigLuaPre = /* lua */ ''
  -- load refactoring Telescope extension
  require("telescope").load_extension("refactoring")
'';
```

And used in keymaps as follows:

```nix
keymps = [
  {
    mode = "n";
    key = "<leader>rr";
    action = /* lua */ ''
      function() require("telescope").extensions.refactoring.refactors() end
    '';
    lua = true;
    options.desc = "Select refactoring option";
  }
];
```

It'd be great if `plugins.refactoring` had options to configure this

#### Related

Perhaps `plugins.telescope.enabledExtensions` could be made public or an `plugins.telescope.extraExtensions` could be introduced to handle other unsupported telescope extensions?

**Comment by Bodleum** [comment]
Would it make sense to do this? You could have something like:

```nix
plugins.refactoring = {
    enable = true;
    telescopeExtension.enable = true;
};
```

but that wouldn't guarantee that `plugins.telescope` was enabled.
Of course, by enabling the extension from the refactoring side, it could also enable telescope, but I get the feeling that silently enabling other plugins is a bad idea!

Just my thoughts, push back if you disagree!

**Comment by GaetanLepage** [comment]
Maybe, we should merge the telescope refactor first...

**Comment by MattSturgeon** [comment]
> Maybe, we should merge the telescope refactor first...

Agreed.

It'd be great if that pr added public access to `plugins.telescope.enabledExtensions` too, for any other telescope extensions we don't support.

> Would it make sense to do this? You could have something like: `plugins.refactoring.telescopeExtension.enable`

Looks fine to me. Is this how other telescope plugins (not included in telescope itself) are handled?
