### ISSUE TITLE
feature: register LSP binds on `LspAttach`

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1219]
Currently, LSP's keymap registration is done together with most other keymaps, as LSP keymaps actually get added to `programs.nixvim.keymaps` after a bit of processing.

It's common practice in neovim configs to only register LSP-related keymaps when the buffer is attached to a language server, so that vanilla keys can be overridden with LSP functions (etc).

This is demonstrated by [kickstart.nvim here](https://github.com/nvim-lua/kickstart.nvim/blob/66e2a5a425a4f3b2e4f9456d82b29718c24a8993/init.lua#L440-L446).

- This could be configured using a new option such as `plugins.lsp.keymaps.onAttach`

If this is supported, users may wish to add arbitrary keymaps when the LSP is attached, not just the `vim.lsp.*` functions. E.g. to make use of [telescope's lsp functions](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#neovim-lsp-pickers).

- This could be configured by adding an "extra" list; `plugins.lsp.keymaps.extra`, which is a list of normal keymap submodules.
- Alternatively, users could add keymaps themselves, and manually set the keymap event to `"LspAttach"`.
- Ideally, both configuration methods would be available.

### Potential strategy

One way to approach this might be to add a "registered on event" attribute to the keymaps submodule...

When rendering keymaps to lua, first _grouped them_ using the new `event` attribute.

The "`null`" group would be registered the same way keymaps are now, since it represents keymaps with no `event`.

All other groups would be mapped to an `autoCmd` submodule, with `event` being the group's key and the `callback` function registering the group's keymaps like normal.

The LSP plugin could then take advantage of the new system by having it's keymaps use `event = "LspAttach"` by default. Similar to how `options.silent` is configured currently.

Draft implementation of grouping keymaps by event in [this comment](https://github.com/nix-community/nixvim/issues/1219#issuecomment-1984855570) below.

**Comment by Bodleum** [comment]
I think I can tackle this next week.
The only hurdle I can think of right now is we would want `event` to be `null` or `string` or `list of string` just like `autoCmd.*.event`, and in the `list of string` case we would want the keymap to be registered in both groupings of `event` and I'm not sure how to implement that.

The basic `string` case I'm pretty sure I can get going though!

**Comment by MattSturgeon** [comment]
> I think I can tackle this next week.

👀 

> in the `list of string` case we would want the keymap to be registered in both groupings of `event` and I'm not sure how to implement that.

I hadn't thought about lists of events, that makes sense...

Would something like this work?

```nix
eventKeys = let
  # The mapping function converts a keymap
  # with a _list of events_ into a _list
  # of keymaps_, each with a _single_ event.
  mapper = keymap:
    if isList keymap.event
    then map (event: keymap // {inherit event;}) keymap.event
    else [keymap];

  # Filter for keymaps that have events
  matched = filter (k: k ? "event" && k.event != null) keymaps

  # Map using mapper, then flatten the result
  flattened = flatten (map mapper matched);

  # Group by event
  grouped = groupBy (k: k.event) flattened;
  
in grouped;

# keymaps without event
globalKeys = filter (k: !(k ? "event") || k.event == null) keymaps;
```
_I threw this together on my phone so forgive any mistakes, it's mostly to demonstrate the concept._

**Comment by MattSturgeon** [comment]
I think the general solution of adding `event` to keymaps  that I proposed above is probably not the right approach... Similar to #1214; it adds too much magic, on top of how neovim does things.

For LSPs we could instead make use of the existing `onAttach` option (`__lspOnAttach` func).

For a general solution, perhaps auto commands could support recieving a NixVim config in a similar way to the [`files` option](https://nix-community.github.io/nixvim/NeovimOptions/index.html#files)? Maybe this should have its own issue...

**Comment by Bodleum** [comment]
I've got some working code for this already which I was going to tidy up today, but I hear what you're saying.
What do the maintainers think @pta2002 , @traxys, @GaetanLepage?

**Comment by traxys** [comment]
I think it would depend on how much it is applicable to different kind of plugins. If you have something maybe you can try to open a PR, but I won't guarantee that we would integrate this in nixvim.
