### ISSUE TITLE
[BUG] docs wrongly claim `helpers` is accessible anywhere

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1220]
| Field        | Description |
|--------------|-------------|
| Plugin       | `N/A`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

The docs state that I should be able to access the `helpers` attribute as a module parameter, however `nix flake check` states it is missing.

## Minimal, Reproducible Example (MRE)

Not very minimal I'm afraid, but [this branch](https://github.com/MattSturgeon/nix_config/tree/bug/nixvim-helpers) demonstrates the issue when running `nix flake check .`

_(I'll try and make a proper MRE if this proves necessary)_

## Speculation

My first thought was this is flake related, however I would have expected this to have come up already if so. My next guess is is could be related to [the way I add](https://github.com/MattSturgeon/nix_config/blob/f3696a3eaf2d9e3700949e8d9b5af2ef82f33d53/lib/system.nix#L16-L22) my flake inputs to the nixos/home-manager `extraArgs`?

**Comment by MattSturgeon** [comment]
I suspect this is happening because I `import` the NixVim home-manager module from within my module;

If NixVim is using `_module.args` to add `helpers` to the module args, I believe that will only affect modules on the same _"import level",_ for lack of a better term.

As an aside, personally I'd rather access helper libs via a `lib` flake output. I'm not massively keen on third-party modules cluttering up my module args...

**Comment by MattSturgeon** [comment]
I've updated the title because I believe this is mostly a documentation issue, rather than an implementation bug.

Perhaps, instead of claiming we can use `helpers` anywhere, the flake output and config attribute should also be mentioned.

Maybe there is also a good way to explain where `_module.args` has any effectm

**Comment by traxys** [comment]
I think this _used_ to be true, but due to some refactoring of the helpers it is now broken. I need to look into it but I never find the time...

**Comment by traxys** [comment]
It is definitely true that this works for standalone nixvim, but I kind of agree that we should _not_ do it for NixOS and Home-Manager because it could conflict with a user defined extraArg
