### ISSUE TITLE
docs: support other branches

### ISSUE THREAD

**Issue by wikiker** [nix-community/nixvim#1223]
Currently only master branch is documented on https://nix-community.github.io/nixvim/
But this won't correspond to other branches: e.g. during yesterday nvim-cmp changed to cmp (and its options changed too), so now nvim-cmp options must be view upon through someting like wayback machine.

**Comment by clemenscodes** [comment]
Versioned docs would be great. So far only reading the source is viable for anything but latest.

**Comment by arunoruto** [comment]
It would be beneficial to have the docs of previous Nixvim versions. I am not sure how, or even if, it would be done using the current docs generator, but an example of how it is nicely done is the [docs of numba](https://numba.readthedocs.io/en/stable/index.html). We can just select what version should be used!

Maybe the docs need to be switched to a different "backend"?

An alternative is to highlight this problem in the readme or even in the docs under FAQ and give a workaround like building the docs locally, as explained [here](https://github.com/nix-community/nixvim/issues/1485#issuecomment-2092471511).

**Comment by traxys** [comment]
We currently build for the current [unstable](https://nix-community.github.io/nixvim/) and [stable](https://nix-community.github.io/nixvim/stable/) branches.
I don't think we are going to support previous branches, as we don't push any commits to them anymore.
