### ISSUE TITLE
[BUG] cmp sources do not accept list of lists

### ISSUE THREAD

**Issue by Scrumplex** [nix-community/nixvim#1224]
| Field        | Description |
|--------------|-------------|
| Plugin       | `cmp`  | 
| Nixpkgs      | `'github:NixOS/nixpkgs/9df3e30ce24fd28c7b3e2de0d986769db5d6225d' (2024-03-06)` | 
| Home Manager | `N/A` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

The example of `cmp.cmdline` looks like this:
```nix
{
  "/" = {
    mapping.__raw = "cmp.mapping.preset.cmdline()";
    sources = [
      {name = "buffer";}
    ];
  };
  ":" = {
    mapping.__raw = "cmp.mapping.preset.cmdline()";
    sources = [
      [
        {name = "path";}
      ]
      [
        {
          name = "cmdline";
          option = {
            ignore_cmds = ["Man" "!"];
          };
        }
      ]
    ];
  };
}
```

As you can see, the `sources` configuration of `":"` uses lists in a list to achieve something like
```lua
cmp.setup.cmdline(":", {
	sources = cmp.config.sources({
		{ name = "path" },
	}, {
		{ name = "cmdline" },
	}),
})
```

But if I try this exact example I get an evaluation error, as the type of this submodule is:
```nix
attrsOf (
  submodule {
    freeformType = attrsOf anything;
    options = settingsOptions;
  }
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.cmp = {
    enable = true;
    cmdline.":".sources = [
      [
        {name = "path";}
      ]
      [
        {
          name = "cmdline";
          option = {
            ignore_cmds = ["Man" "!"];
          };
        }
      ]
    ];
  };
}
```

**Comment by Scrumplex** [comment]
Probably introduced by #1174

**Comment by traxys** [comment]
I don't think list of list of sources are natively handled by nvim-cmp, it requires to be processed by the `cmp.config.sources()` lua function. In the nvim-cmp refactor we have stopped doing this automatically, this now needs to be done manually with something like `sources = mkRaw "cmp.config.sources(${helpers.toLuaObject listOfListOfSources})"`.

Do note that this will mean that sources won't be installed automatically!
The configuration of nvim-cmp is a bit complex, so we may revisit this at some later point to help this use case, but this is not planned in the sort term

**Comment by Scrumplex** [comment]
In that case the example value of `cmd.cmdline` should be updated as it currently does not evaluate.
