### ISSUE TITLE
[BUG]  Onedark color scheme not loading

### ISSUE THREAD

**Issue by cyntheticfox** [nix-community/nixvim#1228]
| Field        | Description |
|--------------|-------------|
| Plugin       | `onedark`  | 
| Nixpkgs      | `nixos-unstable` | 
| Home Manager | `release-23.11` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
  colorscheme.onedark.enable = true;
};
```

Maybe related to https://github.com/nix-community/nixvim/issues/1189#issuecomment-1974921435

I just tried to switch to onedark, and had issues loading it. Though given the `colorscheme onedark` line definitely appeared in `~/.config/nvim/init.lua`, it seems like the corresponding package referred to in the `colorscheme.onedark.package` var of `onedark.vim` doesn't get loaded. <https://github.com/joshdick/onedark.vim> seems to expect very manual setup with adding the color files to `autoload` and `colors` directories.

First, are colorschemes configured to load plugins if they have one, and second, is there a reason to not use <https://github.com/navarasu/onedark.nvim> instead?

**Comment by GaetanLepage** [comment]
@cyntheticfox what would you think if we would transition to [onedark.nvim](https://github.com/navarasu/onedark.nvim) ?

**Comment by cyntheticfox** [comment]
That sounds good to me, both if it works and if the additional color options work
