### ISSUE TITLE
[BUG] nvim-cmp fails to build after update 

### ISSUE THREAD

**Issue by BananchickPasha** [nix-community/nixvim#1272]
| Field        | Description |
|--------------|-------------|
| Plugin       | nvim-cmp | 
| Nixpkgs      | unstable | 
| Home Manager | unstable | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

nix build fails after I decided to update my system. I guess the issue is because of https://github.com/nix-community/nixvim/commit/a61c8fbc3d845fb7a5966fc9d25021d2a8264edf. Here is part of my config:

```nix
programs.nixvim = {
      plugins.nvim-cmp = {
        enable = true;
        autoEnableSources = true;
        sources = [
          { name = "nvim_lsp"; }
          { name = "treesitter"; }
          { name = "path"; }
          { name = "buffer"; }
        ];
        mapping = let
          genericFallBack = func: ''
            function(fallback)
              if cmp.visible() then
                ${func}
              elseif check_backspace ~= nil and check_backspace() then
                fallback()
              else
                fallback()
              end
            end
          '';
        in {
          "<CR>" = "cmp.mapping.confirm({ select = true })";
          "<Tab>" = {
            action = genericFallBack "cmp.select_next_item()";
            modes = [ "i" ];
          };
          "<C-n>" = {
            action = genericFallBack "cmp.select_next_item()";
            modes = [ "i" ];
          };
          "<C-p>" = {
            action = genericFallBack "cmp.select_prev_item()";
            modes = [ "i" ];
          };
        };
      };

}
```

And error:
```
> sudo nixos-rebuild switch --flake .
warning: Git tree '/home/banana/nixconf' is dirty
building the system configuration...
warning: Git tree '/home/banana/nixconf' is dirty
error:
       … while calling the 'head' builtin

         at /nix/store/9mf8fkjw3vw1gm4s6j5fqlwrv5wf2knf-source/lib/attrsets.nix:967:11:

          966|         || pred here (elemAt values 1) (head values) then
          967|           head values
             |           ^
          968|         else

       … while evaluating the attribute 'value'

         at /nix/store/9mf8fkjw3vw1gm4s6j5fqlwrv5wf2knf-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `plugins.nvim-cmp.autoEnableSources' does not exist. Definition values:
       - In `<unknown-file>': true
```

Could you please return these options for backward compatability?

**Comment by Charging1948** [comment]
I think the module has been renamed from `nvim-cmp` to just `cmp`.

The new options can be found here: https://nix-community.github.io/nixvim/plugins/cmp/index.html

Things like sources and mappings now also need to be defined in the settings attrSet: https://nix-community.github.io/nixvim/plugins/cmp/settings/index.html

**Comment by BananchickPasha** [comment]
>I think the module has been renamed from nvim-cmp to just cmp.

I achnowledge that there is new api with, probably, the same functionality (I haven't managed how to do  fallbacks in new mappings tho), but it's definitelly not ok to break public APIs without any warnings. At the very least, old options should still exist and be marked as deprecated for few months/years, with instructions about how to move to newer ones, as it's made in nixpkgs for example.

**Comment by GaetanLepage** [comment]
> I achnowledge that there is new api with, probably, the same functionality (I haven't managed how to do fallbacks in new mappings tho), but it's definitelly not ok to break public APIs without any warnings. Old options should still exist and be marked as deprecated for few months/years, with instructions about how to move to newer ones, as it's made in nixpkgs for example.

I am sorry to hear that you had a bad experience. We knew from the start that this refactor was going to break user configs.
[We have made our best to leverage the nix tools for warning/deprecation.](https://github.com/nix-community/nixvim/blob/ab3a8a28402574ee03fc104cb1db145b334b9c88/plugins/completion/cmp/deprecations.nix) You were supposed to face a warning telling you that `plugins.nvim-cmp.fooBar` was renamed  `plugins.cmp.settings.foo_bar`.
You will be able to find some examples and guidelines on the [documentation](https://nix-community.github.io/nixvim/plugins/cmp/index.html).
Also, if you wish to get more help, do not hesitate to ask your questions on our [matrix channel](https://nix-community.github.io/nixvim/plugins/cmp/index.html).

As this is not a "bug", I will close this issue.
Again, sorry for the inconvenience.

**Comment by BananchickPasha** [comment]
>[We have made our best to leverage the nix tools for warning/deprecation.](https://github.com/nix-community/nixvim/blob/ab3a8a28402574ee03fc104cb1db145b334b9c88/plugins/completion/cmp/deprecations.nix) You were supposed to face a warning telling you that plugins.nvim-cmp.fooBar was renamed plugins.cmp.settings.foo_bar.

As you can see from my log, there is no any warning, just an error without explanations.

 
If you don't see an issue in breaking APIs, I will switch back to more stable, old-fashioned raw lua/vimscript configuration, there is no point in configuration system which breaks every month IMHO

**Comment by GaetanLepage** [comment]
You are right, we were missing a warning for this option.
The config you shared would now still crash, but with a clearer message.

More generally, we really try our best to not break the users configs.
However, we are allowing ourselves to perform breaking changes when we feel like there are worth it.

Managing your config completely manually is certainly more "stable" and predictable. It is a matter of tradeoffs and if you feel like nixvim is not for you, it is perfectly fine.
Thank you for the feedback. I will keep it in mind for later changes.
