### ISSUE TITLE
[BUG] missing transparent-nvim after updating flake.lock

### ISSUE THREAD

**Issue by pact0** [nix-community/nixvim#1278]
| Field        | Description |
|--------------|-------------|
| Plugin       | `nixvim`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Hello, I have my nixvim installed like so

```nix
nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

and then imported in home manager 

```nix
  imports = [
    inputs.nixvim.homeManagerModules.nixvim
  ];
```

When I try to run `nix flake lock --update-input nixvim` I start getting errors which end with something like this

```nix
       … while evaluating the attribute 'value'

         at /nix/store/bjvqq8c79dbi59g7xzcc6lhl0f19m3d7-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'transparent-nvim' missing

       at /nix/store/vwlqf5kxxw6cwaqbw7vd1vqf4skvjfb6-source/plugins/ui/transparent.nix:12:22:

           11|     originalName = "transparent.nvim";
           12|     defaultPackage = pkgs.vimPlugins.transparent-nvim;
             |                      ^
           13
```

## Minimal, Reproducible Example (MRE)

Run `nix flake lock --update-input nixvim` and then `nixos-rebuild switch --flake .`

**Comment by GaetanLepage** [comment]
Could you try updating all the flake inputs, not just `nixvim` ? (especially `nixpkgs`).

**Comment by pact0** [comment]
Hey, I tried running `nix flake lock --update-input` and then `nixos-rebuild switch --flake ` a couple days ago but the outcome was the same. I ran `nix-channel --update` , `nix flake update` and then ` nixos-rebuild switch --flake` just now and I only got a warning 

```
The option `colorschemes.base16.customColorScheme' defined in `/nix/store/w48ijyc7k5g1h9yyz0x8ar655avpb8wp-modules/nixvim/hm.nix' has been renamed to `colorschemes.base16.colorscheme'.
```

which might be due to me using stylix, so I guess it somehow fixed itself.

**Comment by GaetanLepage** [comment]
> which might be due to me using stylix, so I guess it somehow fixed itself.

This is due to a change we have made to the `base16` module. You should simply rename this option in your config as the message suggest.
Glad that everything works now :)

**Comment by pact0** [comment]
Thanks!
