### ISSUE TITLE
[Feature] LSP inlay-hints

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#1306]
| Field    | Description |
|----------|-------------|
| Plugin   | `lsp-inlayhints.nvim` (archived)  | 
| Homepage | [`https://github.com/lvimuser/lsp-inlayhints.nvim`](https://github.com/lvimuser/lsp-inlayhints.nvim)     | 
| Nixpkgs  | `vimPlugins.lsp-inlayhints-nvim` | 

## Extra Information

I'm not sure if this should be considered a plugin request or a feature request... [Starting with neovim 0.10](https://github.com/neovim/neovim/pull/23984) plugins are no longer required to achieve this, and [lsp-inlayhints.nvim](https://github.com/lvimuser/lsp-inlayhints.nvim) has therefore been archived.

Upstream docs [here](https://neovim.io/doc/user/lsp.html#lsp-inlay_hint).

[This comment](https://github.com/lvimuser/lsp-inlayhints.nvim/issues/46#issuecomment-1949916683) documents one way the native functionality can be used directly:

```lua
vim.api.nvim_create_autocmd('LspAttach', {
    group = vim.api.nvim_create_augroup('UserLspConfig', {}),
    callback = function(ev)
        local client = vim.lsp.get_client_by_id(ev.data.client_id)
        if client.server_capabilities.inlayHintProvider and vim.lsp.inlay_hint then
            vim.lsp.inlay_hint.enable(ev.buf, true)
        end
    end,
)
```

For nixvim this could use [`autoCmd`](https://nix-community.github.io/nixvim/NeovimOptions/autoCmd/index.html):

```nix
autoGroups.LspInlayhints = {};
autoCmd = [
  {
    event = "LspAttach";
    group = "LspInlayhints";
    callback = helpers.mkRaw ''
      function(e)
        local client = vim.lsp.get_client_by_id(e.data.client_id)
        if client.server_capabilities.inlayHintProvider and vim.lsp.inlay_hint then
            vim.lsp.inlay_hint.enable(e.buf, true)
        end
      end
    '';
  }
];
```

Or better yet, [`plugins.lsp.onAttach`](https://nix-community.github.io/nixvim/plugins/lsp/index.html#pluginslsponattach):

```nix
plugins.lsp.onAttach = ''
  if client.server_capabilities.inlayHintProvider and vim.lsp.inlay_hint then
      vim.lsp.inlay_hint.enable(bufnr, true)
  end
'';
```

This could be exposed as an extra-option in `lsp`, for example `pluigins.lsp.inlayHints = true`.

This could replace, or perhaps augment, the current `clangd` and `rust-tools` inlay-hint support.

**Comment by ozwaldorf** [comment]
For more context, the [rust-tools](https://github.com/simrat39/rust-tools.nvim) project was unfortunately archived early this year, and one of it's successors, [rustaceanvim](https://github.com/mrcjkb/rustaceanvim), only provides inlay hints for nvim >=0.10 by default and must be hooked manually with this plugin to work on the current stable version

**Comment by ozwaldorf** [comment]
I like the [plugins.lsp.onAttach](https://nix-community.github.io/nixvim/plugins/lsp/index.html#pluginslsponattach)` approach, one thing to note though is that if accidentally using this on 0.10, it should display a warning

**Comment by MattSturgeon** [comment]
To detect the nvim version at build time (for warnings/assertions), we can probably do something like:

```nix
min = "0.10.0";
version = lib.getVersion config.finalPackage;
isSemver = lib.hasInfix "." version;
supported = isSemver -> lib.versionAtLeast version min;
```

Unfortunately, _any_ nightly version (even one from years ago) will be "supported", because version will look like `"849d82b"` so `lib.versionAtLeast` won't be able to handle it.

I don't think there's a sane way to get a (semver) "target version" from a nightly (hash) version...?

<details><summary>Example</summary>
<p>

```nix
nix-repl> nixpkgs = import <nixpkgs> {}

nix-repl> lib = nixpkgs.lib

nix-repl> :lf github:neovim/neovim?dir=contrib
Added 15 variables.

nix-repl> nvim9 = nixpkgs.neovim

nix-repl> nvim10 = outputs.defaultPackage.x86_64-linux

nix-repl> lib.getVersion nvim9
"0.9.5"

nix-repl> lib.getVersion nvim10
"849d82b"

nix-repl> wrapped9 = nixpkgs.wrapNeovimUnstable nvim9 (nixpkgs.neovimUtils.makeNeovimConfig {})

nix-repl> lib.getVersion wrapped9
"0.9.5"

nix-repl> wrapped10 = nixpkgs.wrapNeovimUnstable nvim10 (nixpkgs.neovimUtils.makeNeovimConfig {})

nix-repl> lib.getVersion wrapped10
"849d82b"
```

</p>
</details>

**Comment by GaetanLepage** [comment]
> [This comment](https://github.com/lvimuser/lsp-inlayhints.nvim/issues/46#issuecomment-1949916683) documents one way the native functionality can be used directly:

So this snippet only works for nvim >= 0.10 ?

**Comment by MattSturgeon** [comment]
> > [This comment](https://github.com/lvimuser/lsp-inlayhints.nvim/issues/46#issuecomment-1949916683) documents one way the native functionality can be used directly:
> 
> So this snippet only works for nvim >= 0.10 ?

Yes. It was added with [this PR](https://github.com/neovim/neovim/pull/20130).

**Comment by GaetanLepage** [comment]
It seems like [neovim 0.10.0 is just around the corner](https://github.com/neovim/neovim/milestone/36).
Let's just wait for it so that we don't have to bother with a conditional implementation.
