### ISSUE TITLE
[PLUGIN REQUEST] Qmk.nvim

### ISSUE THREAD

**Issue by xiro-codes** [nix-community/nixvim#1318]
| Field    | Description |
|----------|-------------|
| Plugin   | `qmk.nvim`  | 
| Homepage | `https://github.com/codethread/qmk.nvim`     | 
| Nixpkgs  | `awaiting merge https://github.com/NixOS/nixpkgs/pull/296208` | 

```nix 
plugins.qmk-nvim.keymaps = [{name = "<NAME>", layout = '''', .... }]

```
all the options are per keymap so this would probably be fine

**Comment by GaetanLepage** [comment]
Let's wait for it to land on `nixos-unstable`: https://nixpk.gs/pr-tracker.html?pr=300336

**Comment by xiro-codes** [comment]
> Let's wait for it to land on `nixos-unstable`: https://nixpk.gs/pr-tracker.html?pr=300336

Its been merged, under a different pr

**Comment by GaetanLepage** [comment]
> Its been merged, under a different pr

I know indeed, it's mine ;)

**Comment by xiro-codes** [comment]
lol opps thanks again

**Comment by GaetanLepage** [comment]
> all the options are per keymap so this would probably be fine

Calling the general `setup` function looks legit too, no ?

**Comment by xiro-codes** [comment]
Right
