### ISSUE TITLE
[PLUGIN REQUEST] vim-godot

### ISSUE THREAD

**Issue by charludo** [nix-community/nixvim#1359]
| Field    | Description |
|----------|-------------|
| Plugin   | `vim-godot`  | 
| Homepage | `https://github.com/habamax/vim-godot`     | 
| Nixpkgs  | `false` | 

## Extra Information
The plugin has basically no config options, but does provide instructions for enabling its completions in popular completion plugins like `cmp`. Maybe additional config options could be added there to auto-enable this plugin?

**Comment by GaetanLepage** [comment]
I am not sure to understand the link between this plugin and the godot language server.
Are both required ?

**Comment by charludo** [comment]
Hi,

thanks for looking into this. I think the main benefit the plugin offers is convenient access to running Godot scenes. 
You are right however, I mixed the instructions from the plugin page up somewhat, the `cmp` part of the README is completely detached from the actual plugin / already configurable in nixvim.

Not sure if it's still worth to package this just for the keybinds? 😅

**Comment by GaetanLepage** [comment]
Yes, I ended up getting that ^^
I haven't added explicit options for declaring keymappings, so the module is not _that_ useful...
At least you can `plugins.godot.enable = true` to install it.
You will have to use the global `keymaps` option to declare your bindings.

**Comment by charludo** [comment]
> Yes, I ended up getting that ^^ I haven't added explicit options for declaring keymappings, so the module is not _that_ useful... At least you can `plugins.godot.enable = true` to install it. You will have to use the global `keymaps` option to declare your bindings.

Right, but the plugin's nvim commands are available and easily keymap-able is what I meant :D

**Comment by MattSturgeon** [comment]
> I haven't added explicit options for declaring keymappings, so the module is not that useful...
> You will have to use the global `keymaps` option to declare your bindings.

I thought about mentioning this when reviewing, but didn't want to block merging. It'd be good to have a keymaps option, especially as we'd ideally register them only in `gdscript` buffers.

**Comment by moveonwasd** [comment]
> Note: The `gdscript` language server is already available in nixvim: `plugins.lsp.servers.gdscript.enable`.

```
       error: Nixvim (plugins.lsp.servers.gdscript.package): No package is known for gdscript, to resolve this either:
         - install externally and set this option to `null`
         - or provide a derviation to install this package
```
Seems like it's unpackaged, am I missing something?

**Comment by charludo** [comment]
> > Note: The `gdscript` language server is already available in nixvim: `plugins.lsp.servers.gdscript.enable`.
> 
> ```
>        error: Nixvim (plugins.lsp.servers.gdscript.package): No package is known for gdscript, to resolve this either:
>          - install externally and set this option to `null`
>          - or provide a derviation to install this package
> ```
> 
> Seems like it's unpackaged, am I missing something?

Ah, the package has been renamed / split into `gdtoolkit_3` and `gdtoolkit_4` in the meantime.
