### ISSUE TITLE
[BUG] `nixvim` refers to a package that does not exist in `nixpkgs` (`jupytext-nvim`)

### ISSUE THREAD

**Issue by computerscience-person** [nix-community/nixvim#1362]
| Field        | Description |
|--------------|-------------|
| Plugin       | `jupytext-nvim`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `Unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Minimal, Reproducible Example (MRE)

1. Update `flake.lock` file.

2. Inside `home-manager`.

```nix
programs.nixvim = {
  enable = true;
}
```

Error:
```
       error: attribute 'jupytext-nvim' missing

       at /nix/store/x2y9zkyak0qh2kksmfvaqllx57dgi6hr-source/plugins/languages/python/jupytext.nix:12:22:

           11|     originalName = "jupytext.nvim";
           12|     defaultPackage = pkgs.vimPlugins.jupytext-nvim;
```

@GaetanLepage seems like there's no package for `jupytext.nvim` in `nixpkgs-unstable`, nor open pull requests/issues there.

**Comment by GaetanLepage** [comment]
Hi !
It has been added recently. You have to update your channel/flake nixpkgs input to get a more recent revision of nixpkgs.
