### ISSUE TITLE
[HELP] standalone configuration in home-manager doesn't set path

### ISSUE THREAD

**Issue by w1kee** [nix-community/nixvim#1366]
hello, i have a standalone nixvim configuration as a flake based on the simple nixvim template, which is an input of my home-manager.
in my home-managers `home.pkgs` i have `inputs.nixvim-config.packages.${systemType}.default`

when i type `nvim` in the shell, it can't find it, but i see that it is built at `/nix/shell/...-nixvim/bin/nvim`
how can i include nixvim in my path?

i'm a nix noob so i apologise if this is the wrong place to post my question.

**Comment by w1kee** [comment]
ok, i made a copy of the `home.nix` file and pointed the `flake.nix` to it, removed some options from the copy, and somehow it started working. when i pointed `flake.nix` back to the original `home.nix` it continued working, so problem is fixed.

thank you @Bodleum for your help

**Comment by Bodleum** [comment]
Glad you got it fixed, happy to help!
