### ISSUE TITLE
[BUG] `nvim-dap-ui` requieres `nvim-nio` to be installed

### ISSUE THREAD

**Issue by pinarruiz** [nix-community/nixvim#1378]
| Field        | Description |
|--------------|-------------|
| Plugin       | `nvim-dap-ui`  | 
| Nixpkgs      | `unstable` (`fd281bd6b7d3e32ddfa399853946f782553163b5`) | 
| Home Manager | `unstable` (`c0ef0dab55611c676ad7539bf4e41b3ec6fa87d2`) | 

- [X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When enabling `nvim-dap-ui`, i get the next error:
```
Se ha detectado un error al procesar /nix/store/aj04vfh0l6ibgb6jr05zsy3lz4kiks4h-init.lua:
E5113: Error while calling lua chunk: ...ck/myNeovimPackages/start/nvim-dap-ui/lua/dapui/init.lua:36: nvim-dap-ui requires nvim-nio to be installed. Install from https://github.com/nvim-neotest/nvim-nio
stack traceback:
        [C]: in function 'error'
        ...ck/myNeovimPackages/start/nvim-dap-ui/lua/dapui/init.lua:36: in main chunk
        [C]: in function 'require'
        /nix/store/aj04vfh0l6ibgb6jr05zsy3lz4kiks4h-init.lua:272: in main chunk
```

## Minimal, Reproducible Example (MRE)

```nix
{
  config = {
    plugins.dap = {
      enable = true;
      extensions = {
        dap-ui.enable = true;
        dap-go.enable = true;
        dap-python.enable = true;
      };
    };
    keymaps = [{
      key = "<leader>dt";
      action = "<cmd>DapToggleBreakpoint<CR>";
      options.desc = "Toggle Breakpoint";
    }{
      key = "<leader>dc";
      action = "<cmd>DapContinue<CR>";
      options.desc = "Dap Continue";
    }];
  };
}
```

I have `nixvim` installed as an standalone-flake.
If more information/files needed just let me know.
Thanks.

**Comment by Bodleum** [comment]
This should be fixed when https://github.com/NixOS/nixpkgs/pull/301478 reaches nixos-unstable.
Track [here](https://nixpk.gs/pr-tracker.html?pr=301478).

**Comment by oddlama** [comment]
FYI: The PR has now reached nixos-unstable
