### ISSUE TITLE
[BUG] `viAlias` and `vimAlias` No Longer Work

### ISSUE THREAD

**Issue by RyanPrussin** [nix-community/nixvim#1384]
| Field        | Description |
|--------------|-------------|
| Plugin       | `N/A` (bug reproducible without plugins)  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 
| System | `aarch64-darwin` | 
| OS Version | `macOS 14.4.1 (23E224)` |

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Recently I've been noticing that the `viAlias` and `vimAlias` options no longer appear to be working, where they used to work all the time. When I use `nvim` via CLI it works as expected, but when using `vi` or `vim` I noticed my themes and settings were no longer being applied.

Using `which vi` reveals it is using `/usr/bin/vi` (VIM - Vi IMproved, version 9.0.2136) and `which vim` reveals it is using `/usr/bin/vim` (VIM - Vi IMproved, version 9.0.2136), both of which appear to be the macOS implementations.

On further investigating, `~/.nix-profile/bin` contains both `vi` and `vim` symlinks. Here are the symlinks in that directory that look like they might be related to nvim / vim / vi / nixvim and therefore could be relevant:

```
nixvim-print-init -> /nix/store/f0as27alblj4glg8ddd27sdaifrcvybv-nixvim-print-init/bin/nixvim-print-init
nvim -> /nix/store/plkr8s6hmvpdddsvmqakji290w1n5675-neovim-0.9.5/bin/nvim
nvim-python3 -> /nix/store/plkr8s6hmvpdddsvmqakji290w1n5675-neovim-0.9.5/bin/nvim-python3
nvim-ruby -> /nix/store/plkr8s6hmvpdddsvmqakji290w1n5675-neovim-0.9.5/bin/nvim-ruby
vi -> /nix/store/plkr8s6hmvpdddsvmqakji290w1n5675-neovim-0.9.5/bin/vi
vim -> /nix/store/plkr8s6hmvpdddsvmqakji290w1n5675-neovim-0.9.5/bin/vim
```

<img width="1502" alt="image" src="https://github.com/nix-community/nixvim/assets/3878957/9ef8f528-3f6c-46d7-a6b6-6a0752c83dfc">

In both cases of `vi` and `vim`, the symlink to their binary is pointing back to the nvim binary stored in `~/.nix-profile/bin/nvim`, which itself is a symlink to `/nix/store/plkr8s6hmvpdddsvmqakji290w1n5675-neovim-0.9.5/bin/nvim`.

I'm using a MacBook Air with an M1 ARM chip. My `home-manager` setup is [standalone via flakes](https://nix-community.github.io/home-manager/index.xhtml#sec-flakes-standalone), so I am not using nix channels at all.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
  viAlias = true;
  vimAlias = true;
};
```

## My flake inputs:
```nix
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nix-index-database = {
      url = "github:Mic92/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    nixvim = {
      url = "github:nix-community/nixvim";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
```

**Comment by RyanPrussin** [comment]
Additional note: this issue might have some overlap with #1270, but that issue involves a conflict between `programs.neovim` and `programs.nixvim` when setting `vimAlias`, so it's a conflict exclusively between home-manager programs. In my case it is an operating system vim binary alias that is taking precedence over the nixvim alias declared in home-manager, which never used to happen.

**Comment by traxys** [comment]
Could you check what is the content of your `PATH` variable (i.e is `/usr/bin` before `~/.nix-profile/bin`) ?

**Comment by RyanPrussin** [comment]
Thank you, that is exactly the problem! Yes, `/usr/bin` is before `~/.nix-profile/bin`. On flipping the order manually it solves the problem. I will explain more for anyone who might happen to have a similar issue in the future, but ostensibly the issue was my fault and it can be closed.

I dug deeper into this and it is related to a hack that I introduced into `programs.zsh.envExtra` in `home-manager` to fix the nix daemon breaking in macOS after on every upgrade (as Apple overwrites `/etc/zshrc` each time, removing the sourcing of the nix daemon, so I added a fallback sourcing just in case that happened):

```nix
envExtra = ''
  # Ensure Nix is sourced. Necessary when /etc/zshrc file loses this same code block on macOS upgrades
  if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
  fi

'';
```
The above code block would cause the daemon to be sourced a second time in `~/.zshenv`, which would seemingly alter the order in which `~/.nix-profile/bin` was added to the `PATH` variable.

I've removed the offending block above because the macOS breaking zsh on upgrade problem should no longer be an issue going forward now that I've started using the [Determinate Systems Nix Installer](https://determinate.systems/posts/nix-survival-mode-on-macos/), which supposedly overcomes this problems. And after doing so everything is working as expected again.
