### ISSUE TITLE
Extract all available sources from null ls

### ISSUE THREAD

**Issue by traxys** [nix-community/nixvim#139]
null-ls has a large number of builtins, and it's going to be complicated to support all of them.

We could try and use the scripts they use to extract the documentation, and maybe use something like 'nix-index' in order to find the correct packages to use.

**Comment by anriha** [comment]
Null-ls is being archived. https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621 So if there is no fork not sure if this will be still relevant in the future.

**Comment by GaetanLepage** [comment]
> Null-ls is being archived. [jose-elias-alvarez/null-ls.nvim#1621](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621) So if there is no fork not sure if this will be still relevant in the future.

Indeed, I will close this issue for this reason.
