### ISSUE TITLE
[BUG] Neorg does not work due to missing dependency

### ISSUE THREAD

**Issue by vendion** [nix-community/nixvim#1395]
| Field        | Description |
|--------------|-------------|
| Plugin       | `neorg`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

It seems the version of the neorg plugin got bumpped and now no longer works due to a missing dependency. on `lua-utils`. It seems this dependency was added in [v8.0.0](https://github.com/nvim-neorg/neorg/releases/tag/v8.0.0) but the change must have only recently hit nixpkgs unstable.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    plugins.neorg.enable = true;
}
```

**Comment by amalgame21** [comment]
I think this is the related discussion: https://github.com/nvim-neorg/neorg/issues/1342
I just use the neorg from nixos-23.11 branch
For standalone configuration: https://github.com/nix-community/nixvim/discussions/1397#discussioncomment-9054044

**Comment by vendion** [comment]
In the mean time yes I know I can use the Neorg package from stable, but at the same time it would be nice for the latest version be fixed as well.

**Comment by Kintaro** [comment]
I think a fix for that needs to be landed in `nixpkgs` for a proper fix, not in nixvim. I'd love for a simple way to fix it without resorting to the stable fix, cause it kinda doesn't work on my end.

**Comment by GaetanLepage** [comment]
Thank you for reporting. I am aware about this.
However, we cannot do much on the nixvim side.

The solution has to be implemented on the nixpkgs side: we should package `neorg` as a lua package (`luaPackages.neorg`) there and build `vimPlugins.neorg` on top of it.
This is worked on [here](https://github.com/NixOS/nixpkgs/pull/302442).

**Comment by 71zenith** [comment]
Another solution is found is to declare their official overlay to override the bugged package
https://github.com/nvim-neorg/nixpkgs-neorg-overlay

**Comment by sachinchaudhary1808** [comment]
they updated there pkg 
![image](https://github.com/nix-community/nixvim/assets/138745629/8a47626e-18a0-4448-987c-c9e5fbd6a30e)
now it should work ha ?

**Comment by GaetanLepage** [comment]
> I'll close this then. We can re-open if the issue is still present.

The update has nothing to do with the general issue which is not neorg-specific.
Indeed, the core problem here is that the lua dependencies of "neovim plugins" in nixpkgs (i.e. built from a `luaPackage.*`) are not propagated.
This is the same reason why luasnip complains with missing the `jsregexp` library.

**Comment by Thiago-Assis-T** [comment]
Is there something still needed for this to work?

**Comment by MattSturgeon** [comment]
> Is there something still needed for this to work?

This PR is where it's being worked on: https://github.com/NixOS/nixpkgs/pull/302442

As mentioned above, you can use the overlay as a temporary workaround.

**Comment by Thiago-Assis-T** [comment]
sorry, came out rude, thank you for the response

**Comment by menixator** [comment]
For a temporary solution on 24.05 you can just add the dependencies as extraPlugins to nixvim.

```nix
programs.nixvim.extraPlugins = [
    (pkgs.vimUtils.buildVimPlugin {
      inherit (pkgs.luaPackages.lua-utils-nvim) pname version src;
    })

    (pkgs.vimUtils.buildVimPlugin {
      inherit (pkgs.luaPackages.pathlib-nvim) pname version src;
    })

    (pkgs.vimUtils.buildVimPlugin {
      inherit (pkgs.luaPackages.nvim-nio) pname version src;
    })
];
```
This alone will get it to work on nixos-24.05 (as of writing rev `cf05eeada35e122770c5c14add958790fcfcbef5` ).
And if you want to bring in the more recent neorg from the current unstable(rev `c3392ad349a5227f4a3464dce87bcc5046692fce`), you can just swap out the neovim package of through nixvim to meet the 0.10 minimum requirement like so:

```nix
programs.nixvim.package = nixpkgs-unstable.legacyPackages.${pkgs.system}.neovim-unwrapped;
programs.nixvim.plugins.neorg.package = nixpkgs.unstable.legacyPackages.${pkgs.system}.vimPlugins.neorg;
```

**Comment by GaetanLepage** [comment]
https://github.com/NixOS/nixpkgs/pull/302442 has been merged so we should have a `neorg` plugin working out of the box very soon !
Sorry for the massive delay...

**Comment by GaetanLepage** [comment]
The patch has landed in `nixos-unstable` and this issue is now solved.
You don't need to use the overlay anymore.

## Warning
If you have `performance.combinePlugins` enabled, make sure to add `"neorg"` to `performance.combinePlugins.standalonePlugins`.
Otherwise, it will keep complaining about missing dependencies.
