### ISSUE TITLE
[BUG] undefine variabel 'nixfmt-classic' at /nix/store/wkymfdvdgz0lfwbjn7gh2gkssvnxk2l7-source/plugins/lsp/language-servers/efmls-configs.nix:124:1 4:<BUG>

### ISSUE THREAD

**Issue by sphamtambo** [nix-community/nixvim#1405]
| Field        | Description |
|--------------|-------------|
| Plugin       | `<PLUGIN>`  | 
| Nixpkgs      | `<VERSION>` | 
| Home Manager | `<VERSION>` | 

- [ ] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
}
```

**Comment by GaetanLepage** [comment]
Hello,
Please, make sure that you use a recent enough revision of an unstable channel of `nixpkgs`.
If you are using a flake, run `nix flake update`.

**Comment by sphamtambo** [comment]
awesome everything works now.
