### ISSUE TITLE
[PLUGIN REQUEST] Make `vimPlugins.cmp-async-path` available in `cmp.settings.sources`

### ISSUE THREAD

**Issue by becknik** [nix-community/nixvim#1413]
| Field    | Description |
|----------|-------------|
| Plugin   | `cmp-async-path`  | 
| Homepage | https://github.com/FelipeLema/cmp-async-path     | 
| Nixpkgs  | [`vimPlugins.cmp-async-path`](https://search.nixos.org/packages?channel=unstable&show=vimPlugins.cmp-async-path) | 

## Extra Information

Plugin is archived, but at least it received some commits in the last 2 years (`cmp-path` did not).

Haven't tested if it actually works..

**Comment by traxys** [comment]
It was archived in favour of https://codeberg.org/FelipeLema/cmp-async-path
