### ISSUE TITLE
[PLUGIN REQUEST] `gitignore.nvim`

### ISSUE THREAD

**Issue by pinarruiz** [nix-community/nixvim#1418]
| Field    | Description |
|----------|-------------|
| Plugin   | `gitignore.nvim`  | 
| Homepage | `https://github.com/wintermute-cell/gitignore.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information

From the README:

> A neovim plugin for generating .gitignore files in seconds, by allowing you to select from a huge number of different technologies.

**Comment by GaetanLepage** [comment]
PR created upstream: https://github.com/NixOS/nixpkgs/pull/304191

**Comment by pinarruiz** [comment]
Hi @GaetanLepage https://github.com/NixOS/nixpkgs/pull/304191 jusy made it to unstable :smile: 
[Tracker](https://nixpk.gs/pr-tracker.html?pr=304191)
[Search](https://search.nixos.org/packages?channel=unstable&show=vimPlugins.gitignore-nvim)
