### ISSUE TITLE
[BUG] Gruvbox settings don't work

### ISSUE THREAD

**Issue by Creonico** [nix-community/nixvim#1424]
| Field        | Description |
|--------------|-------------|
| Nixpkgs      | `<23.11>` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

None of the gruvbox colorscheme settings work. I added my desired gruvbox settings to my configuration based on the nixvim man pages, but none of the settings, other than enable, had an effect after rebuilding.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    enable = true;
    colorschemes.gruvbox = {
      enable = true;
      colorColumn = "bg0_h";
      numberColumn = "bg2";
      contrastDark = "medium";
      trueColor = true;
      undercurl = false;
      italics = false;
      underline = false;
      italicizeComments = false;
      italicizeStrings = false;
    };
};
```

**Comment by GaetanLepage** [comment]
Please, update your flake inputs and retry, it should be working now.
If not, go on and re-open the issue :)
