### ISSUE TITLE
[PLUGIN REQUEST] CopilotChat.nvim

### ISSUE THREAD

**Issue by Industrial** [nix-community/nixvim#1425]
| Field    | Description |
|----------|-------------|
| Plugin   | `CopilotChat.nvim`  | 
| Homepage | `https://github.com/CopilotC-Nvim/CopilotChat.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information
The missing piece to copilot powered editing in vim! I still have to fire up VSCode only for this feature..

**Comment by MikaelFangel** [comment]
I have added a PR in Nixpkgs to add the plugin:
https://github.com/NixOS/nixpkgs/pull/310697

**Comment by PowerUser64** [comment]
Duplicate of #992
