### ISSUE TITLE
[FEATURE REQUEST] include plugin homepage link in documentation

### ISSUE THREAD

**Issue by idrisr** [nix-community/nixvim#1434]
One of the things I use nixpkgs for is discovery of interesting packages I wouldn't have encountered otherwise. Similarly, I'm excited about switching to nixvim because in a way it has a list of interesting, curated neovim plugins I can discover and try.

If the documentation had links to the plugins, then it would make this discovery process much easier. Currently, when trying to learn about what one of the available plugins does, I go to search.nixos.org, find the package, and then visit the homepage link.  It would be much more convenient if nixvim provided that homepage link instead. 

For example, for the `oil-nvim` plugin, the docs could include the link in `meta.homepage`, and then the discovery process could be much improved.

```
  oil-nvim = buildVimPlugin {
    pname = "oil.nvim";
    version = "2023-11-15";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "oil.nvim";
      rev = "af04969c437e0c46a2b3c86d7892458e878ecc40";
      sha256 = "17mi1hs3jmmrxqxhykqf0xj91ssxzzzig7gmdlyak6pgwln2ziyr";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/stevearc/oil.nvim/";
  };
```

**Comment by MattSturgeon** [comment]
[The docs](https://nix-community.github.io/nixvim/plugins/oil/index.html) already link to the homepage, so I'm not sure what you're asking us to change?

**Comment by GaetanLepage** [comment]
> [The docs](https://nix-community.github.io/nixvim/plugins/oil/index.html) already link to the homepage, so I'm not sure what you're asking us to change?

True, but this is done through the `mk[Neo]vimPlugin` helpers, so it is not available for all plugins.

As we will tend to using those helpers more and more broadly, I will close this issue.
I'm afraid that we won't change the existing plugins manually.

**Comment by MattSturgeon** [comment]
> I'm afraid that we won't change the existing plugins manually.

Most existing plugins will eventually be ported to the helpers.

Any that are better suited to not using the helpers may benefit from a docs-helper that simply adds the URL/maintainer/description docs for the plugin...
