### ISSUE TITLE
Nginx LSP does not exist

### ISSUE THREAD

**Issue by joaopedroaat** [nix-community/nixvim#1435]
I trying to setup nginx_language_server but i get the following error:

       `error: The option 'programs.nixvim.plugins.lsp.servers.nginx_language_server' does not exist. Definition values:
       - In '/nix/store/c48l8qfaiigv7f7f1inwdyqdbpkk3cky-source/modules/nvim/plugins/lsp.nix':
           {
             enable = true;
           }`

If the LSP is not supported by default, how can I workaround to enable it?

**Comment by MattSturgeon** [comment]
Doesn't look like we currently support it. [Upstream repo](https://github.com/pappasam/nginx-language-server), not in nixpkgs yet.

There's also [nginx.vim](https://github.com/chr4/nginx.vim/) (not a LS), which is packaged as `vimPlugins.nginx-vim`.

As for how you can use something that NixVim doesn't include, that's in the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html#how-do-i-use-a-plugin-not-packaged-in-nixpkgs), though you'd also have to do some LSP specific stuff in `extraConfigLua`

**Comment by joaopedroaat** [comment]
Thanks

**Comment by GaetanLepage** [comment]
I have opened a PR on nixpkgs to upstream this LS: https://github.com/NixOS/nixpkgs/pull/305262

Once it'll be merged, I will be able to add the support in nixvim.
