### ISSUE TITLE
[BUG] <BUG> Issues showing documentation in cmp plugin

### ISSUE THREAD

**Issue by cachedpotato** [nix-community/nixvim#1457]
| Field        | Description |
|--------------|-------------|
| Plugin       | `cmp and/or lsp`  |  
| Nixpkgs      | `unstable` |  
| Home Manager | `<VERSION>` |  unstable

- [x ] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
Hello, I'm quite new to NixOS and Neovim, and I'm not sure if this is a bug but I'm encountering problems with cmp and/or lsp.
Mainly, the cmp list does not show any documentation. Copied below are my settings for cmp/lsp related plugins.
Is there anything else I should do to make this work? Any advice would be greatly appreciated. Thanks!

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim.plugins = {
      lsp = {
        enable = true;
        servers = {
          bashls.enable = true; #bash
          ccls.enable = true; #c/c++
          dockerls.enable = true; #Docker
          gleam.enable = true; #gleam
          marksman.enable = true; #markdown
          nixd.enable = true; #nix
          ruff-lsp.enable = true; #python
          rust-analyzer = {
            enable = true;
            installCargo = true;
            installRustc = true;
          };
          yamlls.enable = true; #YAML
        };
      };      
      cmp = {
        enable = true;
        autoEnableSources = true;
        settings = {
          sources = [
            {name = "nvim_lsp";}
            {name = "buffer";}
            {name = "path";}
            {name = "cmdline";}
            {name = "cmp";}
            {name = "luasnip";}
          ];

          snippet.expand = ''
            function(args)
              require('luasnip').lsp_expand(args.body)
            end
          '';

          mapping = {
            "<C-b>" = "cmp.mapping.scroll_docs(-4)";
            "<C-f>" = "cmp.mapping.scroll_docs(4)";
            "<C-Space>" = "cmp.mapping.complete()";
            "<Alt-Tab>" = "cmp.mapping.abort()";
            "<CR>" = "cmp.mapping.confirm({select = true})";
            "<Alt-`>" = "cmp.mapping.confirm({select = false})";
            "<S-Tab>" = "cmp.mapping(cmp.mapping.select_prev_item(), {'i', 's'})";
            "<Tab>" = "cmp.mapping(cmp.mapping.select_next_item(), {'i', 's'})";
          };
          view.docs.auto_open = true;

          window = {
            documentation.winhighlight = "Normal:NormalNC,FloatBorder:NormalNC,CursorLine:PmenuSel,Search:None";
            documentation.max_height = "math.floor(40 * (40 / vim.o.lines))";
            documentation.max_width = "math.floor((40 * 2) * (vim.o.columns / (40 * 2 * 16 / 9)))";
            completion.winhighlight = "Normal:NormalNC,FloatBorder:NormalNC,CursorLine:PmenuSel,Search:None";
          }; 
        };
      };

      cmp-nvim-lsp.enable = true;
      cmp-buffer.enable = true;
      cmp-path.enable = true;
      cmp-cmdline.enable= true;
      cmp_luasnip.enable = true;
      luasnip.enable = true;
      lspkind.enable = true;
      lspkind.cmp.enable = true; #icons

}
```

**Comment by GaetanLepage** [comment]
First and foremost, the following lines in your config are not necessary:
```nix
      cmp-nvim-lsp.enable = true;
      cmp-buffer.enable = true;
      cmp-path.enable = true;
      cmp-cmdline.enable= true;
      cmp_luasnip.enable = true;
```
Indeed, the plugins of the sources you enable in `plugins.cmp.settings.sources` are automatically installed by nixvim.

Now, what do you mean by "cmp does not show documentation" ?
You mean that the completion list you get while writting doesn't contain elements from the LSP ? (i.e. it does not autocomplete function/variable names).
If so, have you checked that your language server is attached to the buffer (`:LspInfo`).

Does this happens for all languages ?

**Comment by cachedpotato** [comment]
I apologize for not being specific, I'll try my best specifying exactly what the issue is.
As for the plugins that I explicitly enabled, I did it as an effort to see if that was the problem. I did read the NixVim doc, but I wasn't sure where the problem lied so I tried to do everything I can think of, which included explicitly telling NixVim to enable those plugins.
By documentation I meant those little docs that normally appear right next to the completion list. Just like how in VSCode if you hover your cursor over to a function it will give a detailed explanation of what it does. From the videos I've seen on neovim, I assumed if I install LSP and cmp the completion list and the documents will show up simultaneously right next to each other.
I haven't tried out all languages, but I did try out nix and python. I did check if the LSP is being attached, if I'm not mistaken it is, here's the text below (I was editing my nixvim.nix):
```
Language Client Log: /home/..../nvim/lsp.log
Detected language: nix
Client: nixd (id:1, bufnr: [1])
  filetypes: nix
  autostart: true
  root directory: /../.flake_configs (I store my flake.nix, home.nix etc here)
  cmd: /nix/store/..../bin/nixd
``` 
the LspInfo also gave me list of all configured servers list, and I didn't see any problem there.
Maybe there is a setting I forgot to adjust, or I need to make a custom lua function for this to happen, but like I said I'm new to neovim so I'm not sure what to do.

Again, sorry for being too general. If you need any more information please let me know.
Thanks!

**Comment by GaetanLepage** [comment]
Oh I see. So this has nothing to do with completion. It is a feature called _hover documentation_.
You can show documentation for the item under your cursors by running `:lua vim.lsp.buf.hover()`. This will open a pop-up window showing the docs.
Usually people create a keymap for this (often `K`, as vscode does I guess). See [here](https://github.com/GaetanLepage/nix-config/blob/9bcb30a758624a3e6a83133ed4dc7aa3b631eadb/home/modules/tui/neovim/plugins/lsp.nix#L20) fr an example.

If you want it to appear _as you type_, you will most likely need an extra plugin. I am not aware of such a plugin, but feel free to explore !

**Comment by GaetanLepage** [comment]
Apparently, it is possible. Not clear to me how.
Have a look at this as a starting point: https://github.com/neovim/neovim/issues/1934#issuecomment-399270196

**Comment by cachedpotato** [comment]
Thank you so much for your help! Really appreciate it.
I'll close the issue, though I guess it wasn't even an issue of nixvim in the first place haha, just need a few tweaks here and there.
Again thank you for helping!
