### ISSUE TITLE
[BUG] Treesitter error when running rest plugin

### ISSUE THREAD

**Issue by mrityunjaygr8** [nix-community/nixvim#1466]
| Field        | Description |
|--------------|-------------|
| Plugin       | `rest`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I have enabled the rest.nvim plugin, and when i try to send a request using `:Rest run` I am getting an error saying that `Error executing Lua callback: ...0.9.5/share/nvim/runtime/lua/vim/treesitter/language.lua:93: no parser for 'conf' language, see :help treesitter-parsers` 

Please see the attached screenshot
![image](https://github.com/nix-community/nixvim/assets/14573967/c54e699c-62e6-4b2a-ad7a-87eaf6de9ddd)

Let me know what other information is required from my side to help fix this issue

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.rest.enable = true;
  plugins.treesitter.enable = true;
  plugins.treesitter.ensureInstalled = ["lua" "xml" "http" "json" "graphql"];
}
```

**Comment by traxys** [comment]
Maybe you need "conf" in ensureInstalled ?

**Comment by khaneliman** [comment]
It looks like there's no `conf` treesitter parser and your neovim configuration has associated the `.http` file with that fieltype. From what I can see, you need to setup a filetype associate for the .http files to http and use the tree-sitter-http parser. 

```nix
  filetype = {
    extension = {
      "http" = "http";
    };
  };
```
