### ISSUE TITLE
[BUG] Lualine section separators background is weird

### ISSUE THREAD

**Issue by ArtemChandragupta** [nix-community/nixvim#1478]
| Field        | Description |
|--------------|-------------|
| Plugin       | `Lualine`  | 
| Nixpkgs      | `Unstable` | 
| Home Manager | `Unstable` | 

- [+] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

![image](https://github.com/nix-community/nixvim/assets/90765302/1e277d4a-caa2-4fe2-a58b-31cdc81d4006)

Then I try to reproduce bubbles lualine theme, glyphs on the edges of the line have weird background. This issue have some mentions on [reddit](https://www.reddit.com/r/neovim/comments/15yw4od/lualine_black_background_on_ends_of_statusline/) and [lualine github](https://github.com/nvim-lualine/lualine.nvim/issues/867). They resolved it by 

> Link StatusLine and StatusLineNC highlight groups to Normal
`:hi! link StatusLine Normal
:hi! link StatusLineNC Normal`

What is it and how can I do this in nixvim?

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim.plugins = {
  lualine = {
    enable = true;
    sectionSeparators = {
      left  = "";
      right = "";
    };
    sections = {
      lualine_a = [
        {
          separator.left = "";
          separator.right = "";
          extraConfig.padding.right = 2;
          extraConfig.padding.left = 2;
        }
      ];
      lualine_z = [
        {
          separator.right = "";
          extraConfig.padding.left = 2;
          extraConfig.padding.right = 2;
        }
      ];
    };
  };

}
```

**Comment by GaetanLepage** [comment]
Hello, thanks for the detailed report.

> What is it and how can I do this in nixvim?

This solution consists in linking highlight groups.
You can do so in nixvim by setting:
```nix
extraConfigVim = ''
  hi! link StatusLine Normal
  hi! link StatusLineNC Normal
'';
```

**Comment by GaetanLepage** [comment]
> Working as expected!

Great !
