### ISSUE TITLE
[BUG]  Alpha "attempt to index a boolean" error on load on aarch64-linux

### ISSUE THREAD

**Issue by edrobertsrayne** [nix-community/nixvim#1486]
| Field        | Description |
|--------------|-------------|
| Plugin       | `alpha`  | 
| Nixpkgs      | `unstable` | 

- [X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

My Nixvim config works absolutely fine on my x86_64-linux and x86_64-darwin systems. However, on my Raspberry Pi 4, nixvim complains about an error in the generated init.lua file if the alpha plugin is enabled.

```
Error detected while processing /nix/store/jdzq7nyk6a1azxs535agrrxawp4mxlbg-init.lua:
E5113: Error while calling lua chunk: /nix/store/jdzq7nyk6a1azxs535agrrxawp4mxlbg-init.lua:18: attempt to index a bo
olean value
stack traceback:
        /nix/store/jdzq7nyk6a1azxs535agrrxawp4mxlbg-init.lua:18: in main chunk
Press ENTER or type command to continue
```

The generated init.lua looks like this:

```lua
vim.cmd([[




]])

vim.loader.disable()

-- Ignore the user lua configuration
vim.opt.runtimepath:remove(vim.fn.stdpath("config")) -- ~/.config/nvim
vim.opt.runtimepath:remove(vim.fn.stdpath("config") .. "/after") -- ~/.config/nvim/after
vim.opt.runtimepath:remove(vim.fn.stdpath("data") .. "/site") -- ~/.local/share/nvim/site

vim.cmd([[

]])
require("alpha").setup(require("alpha.themes.vim-startify-theme").config)
```

These are my current configurations for NixOS and the full MRE for this bug.

* https://github.com/edrobertsrayne/nixvim/tree/alpha-bug
* https://github.com/edrobertsrayne/dotfiles

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.alpha = {
    enable = true;
    theme = "vim-startify-theme";
  }
}
```

**Comment by GaetanLepage** [comment]
Hello !
Is this issue still happening ?

**Comment by edrobertsrayne** [comment]
Everything is building and working fine now both in home manager and a flake.
