### ISSUE TITLE
i don't understand what happened

### ISSUE THREAD

**Issue by Zm94ZGV2** [nix-community/nixvim#1489]
i don't understand what happened
![Snapshot_2024-05-05_22-22-59](https://github.com/nix-community/nixvim/assets/112862918/e3083cad-96fd-416d-abc9-114e6046f1c2)
![Snapshot_2024-05-05_22-23-31](https://github.com/nix-community/nixvim/assets/112862918/3f4488d5-d3d9-4221-b02c-464848ecfca6)

**Comment by traxys** [comment]
You don't seem to have `git` in the PATH, a lot of flake stuff requires it

**Comment by Zm94ZGV2** [comment]
should i use flakes for install nixvim?

**Comment by traxys** [comment]
It is not required, we provide a compatibilty layer if you are not using flakes

**Comment by GaetanLepage** [comment]
@Zm94ZGV2 were you able to solve your problem ?
