### ISSUE TITLE
[BUG] Multiple errors on `rest.nvim` regarding dependencies

### ISSUE THREAD

**Issue by pinarruiz** [nix-community/nixvim#1492]
| Field        | Description |
|--------------|-------------|
| Plugin       | `rest.nvim`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

![Missing dependencies on rest nvim](https://github.com/nix-community/nixvim/assets/37040888/eae264be-f2e9-4bbf-84ee-01eb8a1fee61)
The dependencies that seem to be missing are:
- `lua-curl`
- `xml2lua`
- `mimetypes`

## Minimal, Reproducible Example (MRE)

```nix
{
  plugins.rest.enable = true;
}
```

Can confirm that disabling the plugin stops the messages.

**Comment by GaetanLepage** [comment]
I think this is the same problem as luasnip (https://github.com/NixOS/nixpkgs/issues/306367).
@teto is working on the lua dependencies propagation problem.

Thank you for reporting it anyway.
