### ISSUE TITLE
[BUG] keymaps: mapping telescope's undo extension breaks custom keymaps

### ISSUE THREAD

**Issue by PowerUser64** [nix-community/nixvim#1493]
| Field        | Description |
|--------------|-------------|
| Plugin       | `telescope`  | 
| Nixpkgs      | `63c3a29ca82437c87573e4c6919b09a24ea61b0f` | 
| Home Manager | `9036fe9ef8e15a819fa76f47a8b1f287903fb848` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Binding a key to Telescope's `undo` plugin causes custom keymaps to stop working.

## Minimal, Reproducible Example

```nix
programs.nixvim = {
  plugins.which-key.enable = true; # helps see what's happening
  plugins.telescope = {
    enable = true;
    keymaps = {

        ###### the problematic line - comment this to "fix" the bug
        "<leader>fu" = { action = "undo";         options.desc = "Telescope Undo"; };

        # These should work fine
        "<leader>ff" = { action = "builtin";      options.desc = "Telescope Builtin"; };
        "<leader>fg" = { action = "live_grep";    options.desc = "Telescope Live Grep"; };
    };
    # NOTE: the undo plugin doesn't have to be enabled
    #extensions.undo.enable = true;
  };

  # test keymaps
  globals.mapleader = " ";
  keymaps = [
    {
      action = "<cmd>help<CR>";
      key = "gh";
      mode = [ "n" ];
    }
    {
      action = "<cmd>help<CR>";
      key = "yu";
      mode = [ "n" ];
    }
    {
      action = "<cmd>help<CR>";
      key = "<leader>g";
      mode = [ "n" ];
    }
  ];
}
```
### Steps to reproduce
1. load nixvim with the config above
2. try using any of the custom keymaps (`gh`, `yu`, `<leader>g`)
	- they don't work (help page doesn't open)
	- note that `<leader>ff` and the other `telescope.keymaps` options work (as they should)
3. comment line 8 (the problematic line)
4. try using the custom keymaps from before
	- help page opens, they work
	- all other `telescope.keymaps` options still work 

<sub> it took me 2 days to find this :sob:</sub>

**Comment by MattSturgeon** [comment]
I can't see how the keymap code could lead to one keymap effecting others...

https://github.com/nix-community/nixvim/blob/40598fc1bd8c93adc3759aff5d5a39d4e66790e5/plugins/telescope/default.nix#L76-L90

So this is a bit of a head scratchier :thinking: 

Is there anything suspicious in the generated `init.lua`?

Using nix repl, is there anything suspicious when you inspect the resolved config options `keymaps` and `plugins.telescope.keymaps`?

All the telescope keymaps should get added to the "main" keymaps options, with their `action` converted to a `__raw` lua string.

**Comment by PowerUser64** [comment]
Here are the generated files: [generated-inits.zip](https://github.com/nix-community/nixvim/files/15360888/generated-inits.zip).

Here's the result of running `diff` on them:
```console
$ diff generated-broken-init.lua generated-working-init.lua
57,62d56
<         {
<             ["action"] = require("telescope.builtin").fdsafsda,
<             ["key"] = "<leader>fu",
<             ["mode"] = "n",
<             ["options"] = { ["desc"] = "Telescope Undo" },
<         },
```

It might be worth noting the error that is generated by neovim when the MRE is loaded with the line uncommented.

```nix
Error detected while processing /nix/store/fqx9ngcpbvz390804l1nav113iwql4xf-init.lua:
E5113: Error while calling lua chunk: vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        /nix/store/fqx9ngcpbvz390804l1nav113iwql4xf-init.lua:68: in main chunk

**Comment by MattSturgeon** [comment]
> `rhs: expected string|function, got nil`

That's saying the keymap's "right hand side" (action) should be a string or a lua function. Instead it was `nil`.

That's the expected result for `fdsafsda`, and anything else that doesn't exist in the table returned from `require("telescope.builtin")`.

Undo is not a telescope built-in (it's a 3rd party extension), so it won't be present in `telescope.builtins`. Maybe NixVim should handle this better... :thinking:

The extension's readme suggests it can be involved as follows:

```vim
" Directly by calling it through Telescope's extension interface:

" using lua
:lua require("telescope").extensions.undo.undo()

" using custom options for just this call
:lua require("telescope").extensions.undo.undo({ side_by_side = true })

" using legacy Vim script
:Telescope undo

" Using the optional mapping:

" using lua
:lua vim.keymap.set("n", "<leader>u", "<cmd>Telescope undo<cr>")
" using legacy Vim script
:nmap <leader>u <cmd>Telescope undo<cr>
```

So, in this case the action should be `require("telescope").extensions.undo.undo` (raw string).

```nix
"<leader>fu" = {
 action.__raw = "require("telescope").extensions.undo.undo";
 options.desc = "Telescope Undo";
};
```

@GaetanLepage should we be using `require("telescope").extensions` instead of `require("telescope.builtin")` [here](https://github.com/nix-community/nixvim/blob/40598fc1bd8c93adc3759aff5d5a39d4e66790e5/plugins/telescope/default.nix#L76-L90)? Or perhaps `"<cmd>Telescope ${actionStr}<cr>"`?

**Comment by GaetanLepage** [comment]
Thanks @MattSturgeon for the precise troubleshooting on this.

> @GaetanLepage should we be using `require("telescope").extensions` instead of `require("telescope.builtin")` [here](https://github.com/nix-community/nixvim/blob/40598fc1bd8c93adc3759aff5d5a39d4e66790e5/plugins/telescope/default.nix#L76-L90)? Or perhaps `"<cmd>Telescope ${actionStr}<cr>"`?

Hmm, are the "builtin" actions also part of `require('telescope').extensions` ?

**Comment by MattSturgeon** [comment]
> Hmm, are the "builtin" actions also part of `require('telescope').extensions` ?

Not sure, but even if they are it appears the actual functions are nested in the table; e.g. `extensions.undo.undo()`.

I think `<cmd>Telescope ${actionStr}<cr>` is the way to go, unless there's any reason to prefer calling the lua functions directly?
