### ISSUE TITLE
[BUG] Ruby development broken

### ISSUE THREAD

**Issue by michaelfranzl** [nix-community/nixvim#1495]
| Field        | Description |
|--------------|-------------|
| Plugin       | -  | 
| Nixpkgs      | `unstable` | 
| Home Manager | - | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Modern Ruby development defines dependencies in a project's committed `Gemfile` and `Gemfile.lock`. The dependencies are then installed by `bundler` into a default location in `$(HOME)/.local/share`. However, because nixvim uses `pkgs.neovimUtils.makeNeovimConfig`, and [nixpkgs' default for `withRuby` is true](https://github.com/NixOS/nixpkgs/blob/24.05-pre/nixos/modules/programs/neovim.nix#L51), the environment variable `GEM_HOME` is set for the neovim process, pointing somewhere into the Nix store at `/nix/store/...-neovim-ruby-env/lib/ruby/gems`. `GEM_HOME` is recognized by `bundler`, which will try to write into that path, which is naturally forbidden. So, commands like `bundle install` cannot be run from inside neovim, only from outside, which is inconvenient at best, but mostly confusing and concerning.

A pristine Ruby environment is really important for Ruby software development, and setting GEM_HOME is a big no-no in regards to that (I know that this doesn't come from nixvim). So, currently a user will have to decide between mutually exclusive use cases: 1) Use neovim's Ruby provider for neovim's purposes (`withRuby = true`) or 2) do Ruby software development in a pristine Ruby environment (`withRuby = false`).

I'll create a Pull request to allow configuration of `withRuby`, what has already been foreseen here: https://github.com/nix-community/nixvim/pull/1198#issuecomment-1975460528

## Minimal, Reproducible Example (MRE)

```sh
mkdir /tmp/test
cd /tmp/test
nix-shell -p ruby
bundle init
echo "gem 'solargraph', '0.49.0'" >> Gemfile
bundle install # works
nvim +'! bundle install' # broken:  Bundler::GenericSystemCallError Errno::EROFS: Read-only file system @ dir_s_mkdir
```

**Comment by GaetanLepage** [comment]
Thank you for this very detailed report !
