### ISSUE TITLE
[BUG] `none-ls.sources.diagnostics.commitlint` throws an error about missing dependency

### ISSUE THREAD

**Issue by vendion** [nix-community/nixvim#1503]
| Field        | Description |
|--------------|-------------|
| Plugin       | `none-ls`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

With `none-ls.sourcens.diagnostics.commitlint` enabled, when ever I go to write a git commit message, an error gets throws due to `commitlint-format-json` node module in not installed.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.none-ls.sources.diagnostics.commitlint.enable = true;
}
```

**Comment by khaneliman** [comment]
Still seeing this? Unable to reproduce.

**Comment by vendion** [comment]
No it seems this was fixed, closing.
