### ISSUE TITLE
[PLUGIN REQUEST] vim-terminator

### ISSUE THREAD

**Issue by sachinchaudhary1808** [nix-community/nixvim#1508]
plugin -->> vimPlugins.vim-terminator
github -->> [vim-terminator](https://github.com/erietz/vim-terminator/)

nixos.unstable.url -->> [link](https://search.nixos.org/packages?channel=unstable&show=vimPlugins.vim-terminator&from=0&size=50&sort=relevance&type=packages&query=vimPlugins.vim-terminator)

## info 
*🗡️ Run your code in an output buffer or a vim terminal conveniently*

**Comment by GaetanLepage** [comment]
@sachinchaudhary1808 why have you closed this issue ?

**Comment by sachinchaudhary1808** [comment]
> @sachinchaudhary1808 why have you closed this issue ?

i found another plugin in nixvim repo works fine and this plugin kinda not maintained..

**Comment by GaetanLepage** [comment]
Ok fine ! Thanks for the info :)
