### ISSUE TITLE
[PLUGIN REQUEST] CodeSnap.nvim

### ISSUE THREAD

**Issue by MATOO-Dev** [nix-community/nixvim#1514]
| Field    | Description |
|----------|-------------|
| Plugin   | `codesnap.nvim`  | 
| Homepage | [`codesnap`](https://github.com/mistricky/codesnap.nvim)     | 
| Nixpkgs  | `false` | 

## Extra Information
From the repo's README:

>📸 Snapshot plugin with rich features that can make pretty code snapshots for Neovim

**Comment by GaetanLepage** [comment]
Made a PR usptream: https://github.com/NixOS/nixpkgs/pull/321030
