### ISSUE TITLE
Telescope man_pages picker does not work [BUG] <BUG>

### ISSUE THREAD

**Issue by nebunebu** [nix-community/nixvim#1517]
| Field        | Description |
|--------------|-------------|
| Plugin       | `vimPlugins.telescope-nvim`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
Telescope's picker for man pages does not display man pages. Other pickers (I've tried) work.
![2024-05-14_01-05-1715663540](https://github.com/nix-community/nixvim/assets/87451010/be961b08-07c5-4ab3-80c8-ec4d0edc7cbf)
![2024-05-14_01-05-1715663604](https://github.com/nix-community/nixvim/assets/87451010/63ded73d-7528-42c3-aa09-b4f01514ebe3)

I'm using a standalone configuration, but had this same issue using nixvim as a homeMangerModule, nixosModule.

## Minimal, Reproducible Example (MRE)

```nix
{
  description = "A nixvim configuration";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixvim.url = "github:nix-community/nixvim";
    flake-parts.url = "github:hercules-ci/flake-parts";
  };

  outputs =
    { nixvim, flake-parts, ... }@inputs:
    flake-parts.lib.mkFlake { inherit inputs; } {
      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      perSystem =
        { pkgs, system, ... }:
        let
          nixvimLib = nixvim.lib.${system};
          nixvim' = nixvim.legacyPackages.${system};
          nixvimModule = {
            inherit pkgs;
            module = { plugins.telescope.enable = true; };
          };
          nvim = nixvim'.makeNixvimWithModule nixvimModule;
        in
        {
          checks = {
            default = nixvimLib.check.mkTestDerivationFromNixvimModule nixvimModule;
          };
          packages = {
            # Lets you run `nix run .` to start nixvim
            default = nvim;
          };
        };
    };
}
```
Issue is present when using as nixosModule or homeManagerModule

**Comment by 4lxs** [comment]
i'm unable to reproduce the issue with

```nix
{
  plugins.telescope = {
    enable = true;

    keymaps = {
      "<leader>fM" = {
        action = "man_pages, {}";
        options.desc = "Man pages";
      };
    };
  };
}
```

<img src="https://github.com/nix-community/nixvim/assets/66408983/922aa582-b94a-4cc8-99dc-957ad29da9d2" width="50%">

**Comment by 4lxs** [comment]
are you sure you have man pages installed?

**Comment by nebunebu** [comment]
From the command line, fzf completion works for the `man` command.

In nixvim, tab completions do not seem to work for `:Man`. For instance, `:Man <TAB>` does not give suggested completions. I can, however, enter `:Man <a specific manpage>` and it will open the specified manpage in a split window.

**Comment by 4lxs** [comment]
what do you get when you execute `apropos` or `apropos .`?

**Comment by nebunebu** [comment]
Thanks. Adding `documentation.man.generateCaches = true;` to my nix-config seems to have fixed it. Some pages seem to be missing from those listed in Telescope's picker.

There are some manpages that are accessible via commandline or `:Man` in nixvim that are not populated in the Telescope picker, specifically "nixvim", "configuration.nix", and "home-configuration.nix".

```nix
  documentation = {
    enable = true;
    dev = {
      enable = true;
    };
    info.enable = true;
    man = {
      generateCaches = true;
    };
  };
```

**Comment by 4lxs** [comment]
seems like it's the same for me. i'd guess it's a telescope bug, as apropos indexes these files

**Comment by nebunebu** [comment]
thanks for the help
