### ISSUE TITLE
[PLUGIN REQUEST] Compiler.nvim

### ISSUE THREAD

**Issue by PowerUser64** [nix-community/nixvim#1527]
| Field    | Description |
|----------|-------------|
| Plugin   | Compiler.nvim  | 
| Homepage | https://github.com/Zeioth/compiler.nvim | 
| Nixpkgs  | false | 

## Extra Information

This plugin depends on [overseer.nvim](https://github.com/stevearc/overseer.nvim), which is in nixpkgs but not in nixvim (#1528).

**Comment by sachinchaudhary1808** [comment]
this is a good one i think i wanted this but it was not in nixpkgs 
so someone has to add compiler.nvim as nix pkgs ?

**Comment by PowerUser64** [comment]
I asked @GaetanLepage how to add vim plugins to nixpkgs and apparently it's not that hard, but when I followed these steps (linked later) to try submitting a PR, I didn't get the same result as what was in some of the PR's I was seeing. Maybe if you try you'll get different results? The comment with how to do it is here: https://github.com/nix-community/nixvim/issues/1338#issuecomment-2025118208

**Comment by GaetanLepage** [comment]
> I asked @GaetanLepage how to add vim plugins to nixpkgs and apparently it's not that hard, but when I followed these steps (linked later) to try submitting a PR, I didn't get the same result as what was in some of the PR's I was seeing. Maybe if you try you'll get different results? The comment with how to do it is here: [#1338 (comment)](https://github.com/nix-community/nixvim/issues/1338#issuecomment-2025118208)

What method have you tried ? Running the script or manually appending the relevant snippet to `generated.nix` ?

**Comment by PowerUser64** [comment]
https://github.com/NixOS/nixpkgs/pull/312410 a PR has been made :white_check_mark:
