### ISSUE TITLE
[PLUGIN REQUEST] overseer.nvim

### ISSUE THREAD

**Issue by PowerUser64** [nix-community/nixvim#1528]
| Field    | Description |
|----------|-------------|
| Plugin   | overseer.nvim  | 
| Homepage | https://github.com/stevearc/overseer.nvim | 
| Nixpkgs  | vimPlugins.overseer-nvim | 

## Extra Information

Required for Compiler.nvim.

**Comment by GaetanLepage** [comment]
@PowerUser64 wouldn't you want to give it a shot ?
Honestly, it is not that hard to do and I can help you getting a PR merged :)
Feel free to ask any question on matrix also.

(If you do not want to try or don't have time, no worry, I'll do it)

**Comment by PowerUser64** [comment]
Yeah, I'd be interested to learn how. I'll send you a message later!
