### ISSUE TITLE
[BUG] cmp not recognized as a library

### ISSUE THREAD

**Issue by gjurajlatwit** [nix-community/nixvim#1537]
| Field        | Description |
|--------------|-------------|
| Plugin       | `cmp`  | 
| Nixpkgs      | `plugins.cmp.enable` | 
| Home Manager | `None` | 

- [Y] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
When adding 'cmp.enable = true;' to the nixvim plugins in the nixos configuration file, I get this error when rebuilding the system.

       error: The option `programs.nixvim.plugins.cmp' does not exist. Definition values:
       - In `/etc/nixos/configuration.nix':
           {
             enable = true;
           }
I was trying to add it using the documentation provided [here](https://nix-community.github.io/nixvim/plugins/cmp/index.html). Not sure if the documentation is not updated, or if it's a bug in the way the nvim-cmp nix package is set up, or if it's a misunderstanding in my part.

I am in the stable 23.11 version, and was trying to set up lsp and autocomplete for my neovim configuration. I was able to get around it by looking at the examples provided by Gaetan Lepage in [this](https://github.com/nix-community/nixvim/discussions/928) discussion([This](https://github.com/nix-community/nixvim/discussions/523) one helped too).

I don't use home manager and flakes. Part of it is because I am relatively new to neovim and nixos altogether, but also because I haven't needed them for my use case so far. Just putting that fact in here in case that could cause some issues. 
```nix
luasnip.enable= true;
        lspkind =
        {
          enable = true;
          cmp = 
          {
            enable = true;
          };
        };
        nvim-cmp =
        {
          enable = true;
          snippet.expand = "luasnip";  
          mapping =
          {
            "<C-d>" = "cmp.mapping.scroll_docs(-4)";
            "<C-f>" = "cmp.mapping.scroll_docs(4)";
            "<C-Space>" = "cmp.mapping.complete()";
            "<C-e>" = "cmp.mapping.close()";
            "<Tab>" = 
            {
              modes = ["i" "s"];
              action = "cmp.mapping.select_next_item()";
            };
            "<S-Tab>" = 
            {
              modes = ["i" "s"];
              action = "cmp.mapping.select_prev_item()";
            };
            "<CR>" = "cmp.mapping.confirm({ select = true })";
          };
          sources = 
          [ 
            {name = "path";}
            {name = "nvim_lsp";}
            {name = "luasnip";}
          ];

        };
        lsp =
        {
          enable = true;
          servers =
          {
            bashls.enable = true;
            lua-ls.enable = true;
            gopls = 
            {
              enable = true;
              autostart = true;
            };
          };
        };
```
## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins = {
    cmd.enable = true;
}
```

**Comment by sachinchaudhary1808** [comment]
hey can u try nvim-cmp or cmp-nvim ?

**Comment by sachinchaudhary1808** [comment]
plugins.nvim-cmp.enable = true;
this the option i think plz close the bug if this works

**Comment by 4lxs** [comment]
additional information for @sachinchaudhary1808's answer:

nixvim user guide is updated for the master branch. you're using using stable in which some options may not have been added. in this case, `nvim-cmp` key was renamed to `cmp` recently, but the 23.11 branch (that you're using) is still using `nvim-cmp` as can be seen [here](https://github.com/nix-community/nixvim/blob/7c59615585f691b560d9522c94d8f3195853ca8e/plugins/completion/nvim-cmp/default.nix#L19)

**Comment by gjurajlatwit** [comment]
Hi @4lxs Thank you very much, that makes a lot more sense now. I wasn't aware of the different versions before and that the documentation is following the unstable version.

Thank you and @sachinchaudhary1808 for your responses!
