### ISSUE TITLE
[PLUGIN REQUEST] nvim-neoclip-lua

### ISSUE THREAD

**Issue by sachinchaudhary1808** [nix-community/nixvim#1543]
| Field    | Description |
|----------|-------------|
| Plugin   | `nvim-neoclip-lua`  | 
| Homepage | [github](https://github.com/AckslD/nvim-neoclip.lua)     |
| Nixpkgs  | [unstable](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=vimPlugins.nvim-neoclip-lua) |

## Extra Information

**Clipboard manager neovim plugin with telescope integration**

**Comment by Bullish-Design** [comment]
@GaetanLepage -  I'm getting a "The option 'plugins.neoclip' does not exist" error when trying to install this package. Is this on my end? I'm admittedly new to nixos, so I'd be more than happy to keep digging if this package seems to be working for others. 

I have not seen a github repo using the nixvim version of this package yet, so I figured I'd ask. 

Thanks!

**Comment by MattSturgeon** [comment]
> @GaetanLepage - I'm getting a "The option 'plugins.neoclip' does not exist" error when trying to install this package. Is this on my end? I'm admittedly new to nixos, so I'd be more than happy to keep digging if this package seems to be working for others.
> 
> I have not seen a github repo using the nixvim version of this package yet, so I figured I'd ask.
> 
> Thanks!

Are you using nixos-24.05? This plugin was added in July, so it won't be in a stable release until 24.11.

**Comment by Bullish-Design** [comment]
Of course, thank you! 

Question - I was under the impression that using nixpkgs-unstable would still enable this to be installed on my system. Do you have any recommendations for resources to learn how nixpkgs and nixos versions interact?

**Comment by MattSturgeon** [comment]
NixOS is part of the nixpkgs repo, so there isn't really a difference between nixos and nixpkgs version.

There is a difference between nixos-unstable and nixpkgs-unstable though. They are both nixpkgs channels; you usually want the former, not the latter.

Nixvim's `main` branch is built to be used with `nixos-unstable`, while we also have a `nixos-24.05` branch designed to be used with nixpkg's `nixos-24.05` channel.

If you're getting an option doesn't exist error then you're not using an up to date version of nixvim; either you're using an old revision of the `main` branch (and need to update it) or you're using another branch like our `nixos-24.05` branch.
