### ISSUE TITLE
Support for Nix 24.05?

### ISSUE THREAD

**Issue by Azeirah** [nix-community/nixvim#1551]
I'm not using nixpkgs unstable, and I just installed nixOS on my system, so I have 24.05.

According to the readme, I need to specify the nixpkgs version in the flake, but I'm getting an error that it cannot be found (because the branch doesn't exist!)

```sh
sudo nixos-rebuild test --flake /etc/nixos#default       
error:
       … while updating the lock file of flake 'path:/etc/nixos?lastModified=1716405479&narHash=sha256-jVjsvFjxUMz6Pao9QfsG2pqPEArHARpB2ILTUVqdZ6U%3D'

       … while updating the flake input 'nixvim'

       … while fetching the input 'github:nix-community/nixvim/nixos-24.05'

       error: unable to download 'https://api.github.com/repos/nix-community/nixvim/commits/nixos-24.05': HTTP error 422

       response body:

       {
         "message": "No commit found for SHA: nixos-24.05",
         "documentation_url": "https://docs.github.com/rest/commits/commits#get-a-commit"
       }
```

**Comment by MattSturgeon** [comment]
We've not yet made a 24.05 branch. I'm sure we will soon.

In the meantime, you could build a standalone nixvim derivation (using unstable) as a workaround.

**Comment by GaetanLepage** [comment]
The stable branch has been created: https://github.com/nix-community/nixvim/tree/nixos-24.05
