### ISSUE TITLE
[PLUGIN REQUEST] `Preview.nvim` (+ md-tui)

### ISSUE THREAD

**Issue by srid** [nix-community/nixvim#1577]
| Field    | Description |
|----------|-------------|
| Plugin   | `Preview.nvim`  | 
| Homepage | `https://github.com/henriklovhaug/Preview.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information

Demo of markdown preview in terminal, which is pretty cool:

https://x.com/orhundev/status/1795080714192347445

Package used,
https://github.com/henriklovhaug/md-tui

**Comment by GaetanLepage** [comment]
I have packaged `md-tui` in nixpkgs: https://github.com/NixOS/nixpkgs/pull/318492
Let's wait for it to make its way in `nixos-unstable`.

**Comment by GaetanLepage** [comment]
https://github.com/NixOS/nixpkgs/pull/323735
