### ISSUE TITLE
[PLUGIN REQUEST] ruby-lsp support

### ISSUE THREAD

**Issue by tknawara** [nix-community/nixvim#1604]
| Field    | Description |
|----------|-------------|
| Plugin   | `ruby-lsp`  | 
| Homepage | https://github.com/Shopify/ruby-lsp     | 
| Nixpkgs  | [`ruby-lsp`](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/top-level/ruby-packages.nix#L3294) | 

## Extra Information

Hi, I'm wondering if by any chance you can add support for ruby-lsp, it is a newer alternative to solargraph that is supposed to be more accurate. I'm very new to nixos and nixvim, so apologies if I'm missing details in the issue description.

**Comment by MattSturgeon** [comment]
Here's [upstream's nvim docs](https://github.com/Shopify/ruby-lsp/blob/main/EDITORS.md#Neovim) and nvim-lspconfig's [example](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/ruby_lsp.lua) for reference.
