### ISSUE TITLE
[PLUGIN REQUEST] Stylix theme

### ISSUE THREAD

**Issue by GideonWolfe** [nix-community/nixvim#1628]
| Field    | Description |
|----------|-------------|
| Plugin   | `N/A`  | 
| Homepage | `https://github.com/danth/stylix`     | https://github.com/danth/stylix 
| Nixpkgs  | `false` | false 

## Extra Information

I really like how you've integrated themes like `catppuccin` into `nixvim`, allowing it to be enabled and disabled for various integrations with other plugins. My idea is to utilize the strong templating capabilities of `stylix`, to allow the user to have this deep level of integration with the theme selected with `stylix`.

In practice, this would be similar to allowing the user to define their own `base16` scheme, but hopefully would require less manual theming/highlight application by the user. The theme could just access `config.stylix.colors.withHashtag` or whatever variables the plugins need, and then you would be able to have a nice, consistent looking theme that can be generated dynamically every time you use `stylix`.

**Comment by 4lxs** [comment]
it seems to be an option provided with stylix. see [this](https://danth.github.io/stylix/options/nixos.html#stylixtargetsnixvimenable)

what additional features would you want?

**Comment by MattSturgeon** [comment]
Looks like they have support for most nixvim installation methods, so I think this can be closed as out of our scope. See: https://github.com/danth/stylix/tree/master/modules/nixvim

I can't see anything obvious referring to a standalone nixvim build, nor can I imagine how that ought to work.\
I guess stylix would have to provide read-only access to a nixvim [config attrset](https://github.com/danth/stylix/blob/c760f63a44a98b2324fdebaee32831b1297172a1/modules/nixvim/nixvim.nix#L18), that you'd then pass to standalone-nixvim's [`<derivation>.nixvimExtend`](https://nix-community.github.io/nixvim/modules/standalone.html#extending-an-existing-configuration) function.
