### ISSUE TITLE
[BUG] Can't deploy from aarch64-darwin to x86_64-linux

### ISSUE THREAD

**Issue by notthebee** [nix-community/nixvim#1644]
| Field        | Description |
|--------------|-------------|
| Plugin       | `N/A`  | N/A
| Nixpkgs      | `24.05` | 24.05
| Home Manager | `24.05` | 24.05

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Trying to deploy a flake which includex nix-community/nixvim from an M1 Mac to an x86-64 NixOS machine using `deploy-rs` produces the following error:
```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/dknd53ikkkjvk5jgw0hcwmby9ddpj9v1-init.lua.drv', but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

[#1637 ](https://github.com/nix-community/nixvim/pull/1637) seemed to fix a similar error in the file `nixpkgs-nixvim-doc.drv`, but the issue with `init.lua.drv` remains.

It seems to be related to the IFDs mentioned in this issue:  #1154

## Minimal, Reproducible Example (MRE)

1. Include the nix-community/nixvim flake in flake.nix inputs
2. Run `nix flake update`
3. Attempt to deploy your flake from an aarch64 Mac to a x86-64 NixOS machine using `deploy-rs`, for instance:
```
deploy -s --remote-build ".?submodules=1#spencer" 
```

**Comment by notthebee** [comment]
Additionally, same error happens when deploying with plain `nixos-rebuild`:

```
nixos-rebuild switch --fast -j auto --use-remote-sudo --impure --flake .\?submodules=1#emily --target-host emily --build-host emily
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/l9ghpp1wk6hyng0g56vqzc923mdmwrsn-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/l9ghpp1wk6hyng0g56vqzc923mdmwrsn-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: a 'x86_64-linux' with features {} is required to build '/nix/store/dknd53ikkkjvk5jgw0hcwmby9ddpj9v1-init.lua.drv', but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

**Comment by MattSturgeon** [comment]
Just to confirm: removing nixvim from your config resolves the issue?

I have a feeling this is related to how flakes have one "system" variable, while nixpkgs actually needs a distinct host and target system. See https://nix.dev/tutorials/cross-compilation.html and https://nixos.wiki/wiki/Cross_Compiling

Flakes usually just assume system is the same for both host & target.

**Comment by notthebee** [comment]
Yes, removing nixvim from the config resolves the issue:

Without nixvim:
```
deploy --dry-activate  -s --remote-build ".?submodules=1#emily"                                                                                                                                                                                                                                       ~~~
🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `emily` on remote host
would activate the configuration...
would restart systemd
would reload the following units: dbus.service
would restart the following units: home-manager-notthebee.service
🚀 ℹ️ [deploy] [INFO] Completed dry-activate!
```

With nixvim:
```
deploy --dry-activate  -s --remote-build ".?submodules=1#emily"                                                                                                                                                        
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .?submodules=1
error:
       … while evaluating attribute 'nodes'

         at «string»:4:25:

            3|                       (deploy // {
            4|                         nodes = {
             |                         ^
            5|                           inherit (deploy.nodes) "emily";

       … while evaluating attribute 'emily'

         at «string»:5:49:

            4|                         nodes = {
            5|                           inherit (deploy.nodes) "emily";
             |                                                 ^
            6|                         };

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: a 'x86_64-linux' with features {} is required to build '/nix/store/dknd53ikkkjvk5jgw0hcwmby9ddpj9v1-init.lua.drv', but I am a 'aarch64-darwin' with features {apple-virt, benchmark, big-parallel, nixos-test}
```

**Comment by notthebee** [comment]
I came up with a simple workaround. This shell script runs `nix flake update`, rsyncs the current folder to the machine's /etc/nixos, and runs `nixos-rebuild switch --upgrade`. It takes the machine's hostname as an argument

```bash
#!/usr/bin/env zsh

nix flake update
rsync -q -avx --delete ./ $1:/etc/nixos/
ssh -t $1 'cd /etc/nixos && sudo nixos-rebuild switch --impure --upgrade --flake .\?submodules=1#$1'
```

**Comment by GaetanLepage** [comment]
Thank you @notthebee for sharing this workaround.
I am having trouble seeing if nixvim really is the problem here...
I have never tried doing cross-architecture deployment.
The only thing I know is that our entire test suite succeeds on all four main architectures.

**Comment by MattSturgeon** [comment]
Does [this commit](https://github.com/MattSturgeon/nixvim/commit/d6e4c98fa767fd1eb6032ca1b0e8d2552590e014) help at all?

```
nix flake lock --override-input nixvim github:MattSturgeon/nixvim/d6e4c98fa767fd1eb6032ca1b0e8d2552590e014
```

**Comment by notthebee** [comment]
Unfortunately it doesn't

```
error: attribute 'pkgs' missing

       at /nix/store/6p95y71c4baahvhf13pj7nyjdn0q9g1z-source/lib/modules.nix:508:28:

          507|         builtins.addErrorContext (context name)
          508|           (args.${name} or config._module.args.${name})
             |                            ^
          509|       ) (lib.functionArgs f);
```

**Comment by MattSturgeon** [comment]
This _might_ be fixed by #1818

**Comment by Aehmlo** [comment]
> This may have been fixed by #1818.

I can confirm that 367380b seems to fix this problem for me (very similar situation to the original issue). Furthermore, using the parent (8fbcfcb) fails. I would love to see this backported to 24.05; is there anything I can do to help this process along? I haven't contributed to this project before but would happily do so.

**Comment by MattSturgeon** [comment]
> I can confirm that 367380b seems to fix this problem for me

Thanks for confirming!

I'll mark this as closed, but it can be reopened if others find they can still reproduce the issue.

> I would love to see this backported to 24.05

Realistically, I think you'll have to wait for 24.11.

We would have to remove all instances of IFD (#1818 was the last IFD in `main`, but there were others before).

We'd have to be careful backporting to 24.05 to ensure there are no breaking changes, too. E.g. we removed the (internal) option `initContent` in another PR.

**Comment by Aehmlo** [comment]
> Realistically, I think you'll have to wait for 24.11.
> 
> We would have to remove all instances of IFD (#1818 was the last IFD in `main`, but there were others before).

Ah, makes sense. I'll switch to unstable/`main` in the interim. Thanks!
