### ISSUE TITLE
[nvim-cmp] preselect setting is not effective

### ISSUE THREAD

**Issue by atimofeev** [nix-community/nixvim#1656]
| Field        | Description |
|--------------|-------------|
| Plugin       | `nvim-cmp`  | 
| Nixpkgs      | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Setting `preselect = "cmp.PreselectMode.None";` (or `preselect = "None";`) does not change cmp behavior when you just type text and press enter. If there are any completions at this point, the first one from the list will always be selected, instead of going to newline.

## Minimal, Reproducible Example (MRE)

```nix
 plugins.cmp = {
  enable = true;
  autoEnableSources = true;
  settings = {
    preselect = "cmp.PreselectMode.None";
    snippet.expand =
      "function(args) require('luasnip').lsp_expand(args.body) end";
    mapping = {
      "<C-Space>" = "cmp.mapping.complete()";
      "<C-d>" = "cmp.mapping.scroll_docs(-4)";
      "<C-e>" = "cmp.mapping.close()";
      "<C-f>" = "cmp.mapping.scroll_docs(4)";
      "<CR>" = "cmp.mapping.confirm({ select = true })";
      "<S-Tab>" = "cmp.mapping(cmp.mapping.select_prev_item(), {'i', 's'})";
      "<Tab>" = "cmp.mapping(cmp.mapping.select_next_item(), {'i', 's'})";
    };
  };
};
```

**Comment by MattSturgeon** [comment]
Any option under `plugin.<name>.settings` is passed directly to the plugin's `setup` function, without any interference on our end. So it's likely this is an issue with the plugin or your config, but we'd still need to investigate a bit to be sure.

**Comment by atimofeev** [comment]
Issue was in my `cmp.mapping.confirm` config, which I took from docs:
`"<CR>" = "cmp.mapping.confirm({ select = true })";`
Removing `{select = true}` has resolved the issue without the need for `preselect` setting.

I better read official plugin docs next time :)

https://github.com/hrsh7th/nvim-cmp/issues/557
