### ISSUE TITLE
[BUG]  gdtoolkit is now (gdtoolkit_3|gdtoolkit_4)

### ISSUE THREAD

**Issue by dezren39** [nix-community/nixvim#1660]
| Field        | Description |
|--------------|-------------|
| Plugin       | `gdtoolkit`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

gdtoolkit is now gdtoolkit_3 and gdtoolkit_4

I am not actually using this lsp, but it's causing the flake to fail to build.
#1659 attempts to fix this but may need some changes.

**Comment by Thiago-Assis-T** [comment]
I really don't follow, why is this breaking my build if I'm not using gdformat nor gdlint, I even removed the ts grammar, can you explain it to me? I'm confused

**Comment by GaetanLepage** [comment]
This is quite weird as our CI (and to a lesser extent my personal config) is not suffering from any crash...
Are you sure to use the latest versions of nixvim and nixpkgs ?

**Comment by Thiago-Assis-T** [comment]
yes, it doesn't allow me to upgrade, using flakes and on nixos-unstable-small

**Comment by MattSturgeon** [comment]
> yes, it doesn't allow me to upgrade

Just to clarify, you're using `nix flake update` to check for upgrades?

> using flakes and on nixos-unstable-small

If you're on nixos-unstable-small it's possible you're _ahead_ of us, assuming it is ahead of nixos-unstable at the moment (it usually is).

Do you get the same issue if you add/remove any `inputs.nixvim.inputs.follows.*` from your flake? (I think these only really affect standalone builds of nixvim though)

**Comment by Thiago-Assis-T** [comment]
I commented out the follows statement and it build, it was following my nixpkgs... maybe that was the issue

**Comment by MattSturgeon** [comment]
[It looks like](https://status.nixos.org/) unstable-small is only a day or so newer than unstable; let's revisit this after the our next flake.lock update.

Please re-open if this is still an issue then.

**Comment by MattSturgeon** [comment]
Opps, I meant to close the PR. We can keep the issue open for visibility

**Comment by Davincible** [comment]
Can confirm, also had to comment out the `follows` for nixvim

**Comment by michaelhthomas** [comment]
I'm still having this issue on the 24.05 branch, regardless of if I follow my own `nixpkgs` or not. Does something need to be backported?

**Comment by MattSturgeon** [comment]
> I'm still having this issue on the 24.05 branch, regardless of if I follow my own `nixpkgs` or not. Does something need to be backported?
> 
> To be clear, this just started being an issue after running `nix flake update`, so it's probably related to one of the recent lockfile updates.

What is your nixvim url? Are you using `nix-community/nixvim/nixos-24.05`?

**Comment by michaelhthomas** [comment]
Yes, I'm using the following
```nix
    nixvim = {
      url = "github:nix-community/nixvim/nixos-24.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```
though commenting out the `follows` line produces the same result.

**Comment by GaetanLepage** [comment]
This is weird because our CI hasn't caught anything and we updated the flake inputs no earlier than this morning...

**Comment by MattSturgeon** [comment]
> though commenting out the `follows` line produces the same result.

Just to confirm, you run `nix flake lock` again after removing the follows?

**Comment by michaelhthomas** [comment]
That's correct. There must be something weird going on, since https://github.com/NixOS/nixpkgs/pull/291040 wasn't backported to 24.05, so I shouldn't even be getting this error, especially with the follows line present.
