### ISSUE TITLE
[BUG] Keymaps having lua funtions in action is not working as expected.

### ISSUE THREAD

**Issue by niksingh710** [nix-community/nixvim#1684]
| Field        | Description |
|--------------|-------------|
| Plugin       | `N/A`  | 
| Nixpkgs      | `Nixos-unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Minimal, Reproducible Example (MRE)

I am using flake template `nix flake init -t github:nix-community/nixvim`
```nix
# content inside config/default.nix
globals = {
    mapleader = " ";
};

keymaps = [
    {
      action  = "vim.notify('hi)";
      key = "<leader><cr>";
      mode = "n";
    }
  ];

```

for testing i am using `nix run -- file.txt`.

now if i am using my keymap, no notification is shown and nvim goes in `--VISUAL--` mode

**Comment by GaetanLepage** [comment]
By default, strings are translated as lua strings.
If you want to provide raw lua code, do the following:
```nix
action.__raw = "vim.notify('hi')";
```

This works almost everywhere in nixvim by the way.

**Comment by niksingh710** [comment]
@GaetanLepage 
```
# test.nix
```nix
{
  globals = {
    mapleader = " ";
  };

  keymaps = [
    {
      action.__raw  = "vim.notify('hi)";
      key = "<leader><cr>";
      mode = "n";
    }
  ];
}
```

this snippet throwing error
```bash
error: builder for '/nix/store/sv1igj41w7v4gvgmri88g66qwpybyj8g-init.lua.drv' failed with exit code 2;
       last 1 log lines:
       > error: could not format file /nix/store/iikzl0jnbm99rqq6fkw2v82wbs02afwp-init.lua: error parsing: error occurred while tokenizing: unclosed string at line 27, column 52
       For full logs, run 'nix-store -l /nix/store/sv1igj41w7v4gvgmri88g66qwpybyj8g-init.lua.drv'.
error: 1 dependencies of derivation '/nix/store/y66qld0df0g551hsax3q8ybac2spy621-neovim-0.10.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mh59c3yr472p6if6c26xjnbvajd0lq1w-nixvim.drv' failed to build
```

**Comment by niksingh710** [comment]
Okay so i figured it out.

```nix
action.__raw = "function()vim.notify('hi')end";
```
as it executes the inner string so it needs to be wrapped around.
