### ISSUE TITLE
[BUG] ts-autotag should use `require('...').setup` (treesitter setup is deprecated)

### ISSUE THREAD

**Issue by niksingh710** [nix-community/nixvim#1707]
| Field        | Description |
|--------------|-------------|
| Plugin       | `nvim-ts-autotag`  | 
| Nixpkgs      | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

![image](https://github.com/nix-community/nixvim/assets/60490474/525d45d5-fd2e-48b9-8983-ff11e65c9f25)

**Comment by MattSturgeon** [comment]
Offending code here: https://github.com/nix-community/nixvim/blob/7a2a25af02be25987aa43cd681312f4b5ba12317/plugins/languages/treesitter/ts-autotag.nix#L72-L76

This would be a good opportunity to migrate the module to use `mkNeovimPlugin`

**Comment by niksingh710** [comment]
Yep, auto-requiring the plugin should be a must. While setting up my config, I was lost for a while wondering why the plugin was not working, until I realized I needed to manually invoke the setup method.
