### ISSUE TITLE
keymaps marked as silent appear in which-key

### ISSUE THREAD

**Issue by aidigital** [nix-community/nixvim#1730]
## Description

`options.silent = true;` in they keymaps seems to have no effect.
In the below example, when I press leader, the mapping for <leader>1 appears in which key, even though it shouldn't (it's marked to be silent).
I haven't messed with the `which-key.hidden` settings, so `<silent>` is part of the mappings that shout not be displayed.

```nix
{
      mode = "n";
      key = "<leader>1";
      action.__raw = ''function() vim.cmd("tabn " .. 1) end'';
      options = {
        desc = "should not appear";
        silent = true;
      };
    }
```

The only way to make the key not appear that I found is to not give it a `desc`, and which  `which-key.ignoreMissing=true`, but that makes other keymaps that I want to see, disappear.

I thought perhaps is an issue related to __raw or to using numbers in they key, but none of those seem to be the case.

[nixvim version](https://github.com/nix-community/nixvim/commit/744dfea48bdd331e66b9e874822559fa6fae98af)

**Comment by MattSturgeon** [comment]
I think you're misunderstanding what "silent" is supposed to do. It has nothing to do with which-key, rather it is about whether or not the mapping is printed in the status line.

See [:map-silent](https://neovim.io/doc/user/map.html#%3Amap-%3Csilent%3E)

**Comment by aidigital** [comment]
Thanks @MattSturgeon I see. I though it was a setting for which-key to ignore displaying certain mappings.
Think we can close this then.
