### ISSUE TITLE
[BUG] "global prefix" boolean settings are not converted to int

### ISSUE THREAD

**Issue by henrispriet** [nix-community/nixvim#1741]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lazygit`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When `plugins.lazygit.settings.use_custom_config_file_path` is set to `true`, lazygit.nvim does not recognize it.

[NixVim says this option is a bool](https://github.com/nix-community/nixvim/blob/main/plugins/git/lazygit.nix#L45) and passes it on as such into the generated `init.lua`, but [lazygit.nvim checks if the option is 1](https://github.com/kdheepak/lazygit.nvim/blob/main/lua/lazygit.lua#L96) to enable the feature.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.lazygit.settings = {
    use_custom_config_file_path = true;
    config_file_path = builtins.toString (pkgs.writeText "custom-lazygit-config.yml" ''
      # any options, e.g.
      gui:
        border: single
      notARepository: quit
    '');
  };
};
```

## Workaround

```diff
programs.nixvim = {
  plugins.lazygit.settings = {
-   use_custom_config_file_path = true;
+   use_custom_config_file_path.__raw = 1;
    config_file_path = builtins.toString (pkgs.writeText "custom-lazygit-config.yml" ''
      # any options, e.g.
      gui:
        border: single
      notARepository: quit
    '');
  };
};
```

**Comment by MattSturgeon** [comment]
As per the example, mkVimPlugin _should_ convert bool settings options to int. https://github.com/nix-community/nixvim/blob/49452662b7b4dd2467cbac19e0f9820d570d8976/lib/vim-plugin.nix#L57-L62

The example was added by @GaetanLepage in [`97fb6d6a`](https://github.com/nix-community/nixvim/commit/97fb6d6a29337883843d5edd6b87c4ed260642ec#diff-f6b6c5157e6a7c051a6200b617136341a34ae4d0050fd4a0c9542a2aa1411758R363-R368)

That said, looking at the implementation, I can't see any type conversion being done. It only seems to add the prefix to the option name: https://github.com/nix-community/nixvim/blob/49452662b7b4dd2467cbac19e0f9820d570d8976/lib/vim-plugin.nix#L107

This likely affects a ton of plugins, as many will assume the example is correct and bools are properly converted to int.

**Comment by MattSturgeon** [comment]
I'm dumb, of course vim options can be booleans. Therefore we can't assume nix booleans should be converted to ints.

Instead, the settings-example should be fixed and any affected options should have their type changed to `enum [0 1]`.

IDK if there's a good way to transition affected options without immediately breaking users' configs. I guess any affected users already had (silently) broken configs anyway, so this may not be important.

One way we could do this would be to create a custom type, equivalent to `enum [0 1 true false]` but have its "show" text be `either 0 or 1`.

That way we aren't documenting boolean support, but we could still check for boolean definitions and print an appropriate warning.

**Comment by traxys** [comment]
Yeah for configs that are already broken I don't think it's too bad to introduce a breaking change
