### ISSUE TITLE
[BUG] Some tools from upstream are not declared locally

### ISSUE THREAD

**Issue by ecarlson94** [nix-community/nixvim#1747]
| Field        | Description |
|--------------|-------------|
| Plugin       | `none-ls`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Currently, this is just a warning. It is not halting my progression. However, it does seem relatively new.

```bash
warning: <user> profile: [DEV] Nixvim (plugins.none-ls): Some tools from upstream are not declared locally in `builtinPackages`
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.none-ls.enable = true;
}
```

Then run, `nix flake check`.

**Comment by GaetanLepage** [comment]
Thanks for reporting.
This was taken care of in https://github.com/nix-community/nixvim/pull/1746.
