### ISSUE TITLE
[BUG] Stuck at `Generating remote plugin manifes` on aarch64-linux

### ISSUE THREAD

**Issue by Cryolitia** [nix-community/nixvim#1751]
| Field        | Description |
|--------------|-------------|
| Plugin       | `chadtree wilder`  | 
| Nixpkgs      | `github:nixos/nixpkgs/a71e967ef3694799d0c418c98332f7ff4cc5f6af` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When building on aarch64-linux, the buildPhase will stuck at `Generating remote plugin manifes`. I have waiting for 10 hours and it still keeps strucking.

Building on x86_64-linux seems good for me.

## Minimal, Reproducible Example (MRE)

```nix
  plugins = {
    chadtree.enable = true;
    wilder.enable = true;
  };
```

**Comment by GaetanLepage** [comment]
Have you tried re-running the build command or does it always behave the same ?

**Comment by Cryolitia** [comment]
Yes. I have run it on both a raspberry pi 5 and a aarch64-linux-binfmt-enabled x86_64 machine serveral times. All results in the same issue.
