### ISSUE TITLE
[BUG] rustaceanvim not honoring files.excludeDirs

### ISSUE THREAD

**Issue by Olle-Lukowski** [nix-community/nixvim#1847]
| Field        | Description |
|--------------|-------------|
| Plugin       | `rustaceanvim `  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I discovered this as I am trying to ignore the .direnv folder in my Rust project as rust-analyzer gets stuck on scanning for roots on it, with or without the code below.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins = {
      rustaceanvim = {
        enable = true;
  
        server.settings = {
          files = {
            excludeDirs = [ ".direnv" ];
          };
        };
      };
  };
}
```

**Comment by MattSturgeon** [comment]
Can you check the output of `nixvim-print-init`?

Any options under `settings` are passed directly to the plugin unmodified, so this is likely a plugin and/or config issue, rather than a nixvim issue.

**Comment by Olle-Lukowski** [comment]
Well, I just added this to my own config to make it work. and it seems that `nixvim` does not generate the `rust-analyzer` table:
```
settings = {
  server = {
    settings = ''{
    ['rust-analyzer'] = {
      assist = { emitMustUse = true, expressionFillDefault = "default" },
      check = { command = "clippy" },
      completion = { callable = { snippets = "add_parentheses" }, termSearch = { enable = true } },
      diagnostics = { styleLints = { enable = true } },
      files = { excludeDirs = { ".direnv", ".git" } },
      imports = { granularity = { enforce = true } },
      interpret = { tests = true },
    }}
    '';
  };
};
```

**Comment by traxys** [comment]
I think the correct way is:
```nix
programs.nixvim = {
  plugins = {
      rustaceanvim = {
        enable = true;
  
        server.settings.rust-analyzer = {
          files = {
            excludeDirs = [ ".direnv" ];
          };
        };
      };
  };
}
```
