### ISSUE TITLE
[BUG] Treesitter trying to create directory in nix store

### ISSUE THREAD

**Issue by RoastBeefer00** [nix-community/nixvim#1849]
| Field        | Description |
|--------------|-------------|
| Plugin       | `treesitter`  | 
| Nixpkgs      | `nixos-unstable` | 
| Home Manager | `24.05` | 

- [x ] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

### Error
I get the following error every time I launch neovim after the latest updates:

```
Error detected while processing /nix/store/5y36fg53rjbivbrxih547n5qjlsl46q4-init.lua:
Could not create parser dir ' /nix/store/ak1knrp12ckr8axic4g6ndfifgfmqzpl-vim-pack-dir/pack/m
yNeovimPackages/start/nvim-treesitter/parser ':  Vim:E739: Cannot create directory /nix/store
/ak1knrp12ckr8axic4g6ndfifgfmqzpl-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/pa
rser: read-only file system
Press ENTER or type command to continue
```

[Here is my config](https://github.com/RoastBeefer00/nixos-config/tree/main/nixvim)

**Comment by elohmeier** [comment]
Setting `plugins.treesitter.nixGrammars = false;` fixes this for me.

**Comment by elohmeier** [comment]
I've fixed this by switching to grammarPackages instead of the `plugins.treesitter.ensure_installed` setting.

Example:
```nix
{ pkgs, ... }:

{
  plugins.treesitter = {
    enable = true;
  
    grammarPackages = with pkgs.vimPlugins.nvim-treesitter.builtGrammars; [
      bash
      git_config
      git_rebase
      gitattributes
      gitcommit
      gitignore
      json
      jsonc
      lua
      make
      markdown
      meson
      ninja
      nix
      readline
      regex
      ssh-config
      toml
      vim
      vimdoc
      xml
      yaml
    ];
  };
}
```

**Comment by RoastBeefer00** [comment]
Thank you @elohmeier this resolved the issue for me as well.

**Comment by darkylein** [comment]
I run into the same bug. I don't think this issue should be closed. Maybe @khaneliman could have a look over it.

**Comment by ForsakenHarmony** [comment]
@RoastBeefer00 that's a workaround not a fix, should probably reopen this issue

**Comment by MattSturgeon** [comment]
I've reopened the issue. If the op is no longer interesting they are welcome to "unsubscribe"

**Comment by khaneliman** [comment]
Tried setting the  parser_install_dir = "$XDG_DATA_HOME/nvim/treesitter"; explicitly?
