### ISSUE TITLE
[BUG] Otter stopped working after 435ef28

### ISSUE THREAD

**Issue by PerchunPak** [nix-community/nixvim#1854]
| Field        | Description |
|--------------|-------------|
| Plugin       | `otter`  | 
| Nixpkgs      | `unstable, 655a58a7` | 
| Home Manager | `unstable, 3bfaacf4` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Some time ago I noticed that otter stopped working and today decided to investigate it, after bisecting I found out that 435ef28 is the first commit where otter stopped working

Otter is implemented here: https://github.com/nix-community/nixvim/blob/main/plugins/languages/otter.nix

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim.plugins = {
  otter.enable = true;
  cmp.settings.sources = [ { name = "otter"; } ];
}
```

Tbh I am not sure that example can reproduce the error, it would probably need treesitter and maybe lsp as well, so I just did `sudo nixos-rebuild --flake ... --override-input nixvim ~/dev/nixvim` when bisected.

**Comment by MattSturgeon** [comment]
Thanks for reporting! Are you sure that commit is the issue? I don't see how it could affect your plugin... Does otter interact with treesitter at all?

Any thoughts @khaneliman?

This PR on the other hand did change some behavior by removing the `addCmpSources` option: https://github.com/nix-community/nixvim/pull/1776, though based on your MRE you've noticed that already.

**Comment by khaneliman** [comment]
> Thanks for reporting! Are you sure that commit is the issue? I don't see how it could affect your plugin... Does otter interact with treesitter at all?
> 
> Any thoughts @khaneliman?
> 
> This PR on the other hand did change some behavior by removing the `addCmpSources` option: #1776, though based on your MRE you've noticed that already.

No idea, doesn't touch any related code.

**Comment by MattSturgeon** [comment]
Could you clarify what you mean by "stopped working"?

One thing the treesitter PR did change, is that `plugins.treesitter.settings.highlight.enable` is no longer true by default.

**Comment by khaneliman** [comment]
> Could you clarify what you mean by "stopped working"?
> 
> One thing the treesitter PR did change, is that `plugins.treesitter.settings.highlight.enable` is no longer true by default.

Looking at otter's github, it does look like treesitter is a dependency but it doesn't say what for. This would make sense if it's hooking into it's highlighting for something.

**Comment by PerchunPak** [comment]
Sorry for forgetting to clarify. "Doesn't work" means there is no syntax highlighting in markdown code blocks and I am pretty sure, there is no proper LSP inside those blocks.

Unfortunately, I am not at home right now, but `plugins.treesitter.settings.highlight.enable` should be the reason.

**Comment by PerchunPak** [comment]
`plugins.treesitter.settings.highlight.enable` fixed it for me, thanks!

**Comment by MattSturgeon** [comment]
Guessing otter would benefit from a plugin `description` that suggests configuring `cmp` and `treesitter`?

**Comment by traxys** [comment]
Yeah, maybe with some warnings
