### ISSUE TITLE
buildbot errors

### ISSUE THREAD

**Issue by zowoq** [nix-community/nixvim#1878]
https://github.com/nix-community/nixvim/blob/b9ed90003273f0a75151b32948e16b44891f403c/tests/default.nix#L46

The problem seems to be the linkfarm test that was added in https://github.com/nix-community/nixvim/pull/892, it is using a lot of memory.

> This should dramatically reduce the build time on buildbot.

@GaetanLepage Do you recall the details of this problem, we may be able to find another way of addressing it?

cc @Mic92

**Comment by Mic92** [comment]
The issue here is that one derivation depends on all derivations. So effectively everything gets evaluated twice

**Comment by GaetanLepage** [comment]
> @GaetanLepage Do you recall the details of this problem, we may be able to find another way of addressing it?

Yes, so I made that change for the following reason. Our test suite has one derivation per configuration we want to test.
Thus, as we have 2-3 test cases per plugin, and more than 100 plugins, this corresponded to several hundreds of test derivations per architecture.
So basically,  build-bot was getting flood and couldn't keep up with that many derivations (+ it was making the UI unusable as well).

**Comment by traxys** [comment]
The issue is that in the end our tests require a derivation each (as we launch neovim with the supplied configuration). Would launching each plugin (so ~100 derivations) independently be less though on buildbot?

**Comment by MattSturgeon** [comment]
> (Each of the derivations would be dependent on 2 to 4 other derivations on average)

So effectively a tree of link farm derivations?

In total we'd have more derivations, but maybe having a tree structure would be easier on buildbot?

As another approach, would it be easier on buildbot if we split up our `checks.*.tests` output into several `checks.*.test-*` outputs?

Currently `checks.*.tests` is the link farm derivation that has hundreds of dependencies.

Worth noting: while we have many wrapped nvim test derivations, they should all be wrapping _the same_ nvim package derivation, so that should only need to be built/downloaded once.

**Comment by GaetanLepage** [comment]
> So effectively a tree of link farm derivations?

Yes, what matters for build-bot is the number of top-level derivations. In this sense, it is tractable to have ~60 total top-level derivations (what we have now) rather than ~600+ that we would have without the linkFarm.

**Comment by zowoq** [comment]
I've disabled buildbot on this repo for now.

Even after the recent changes it's still using a lot of memory, can reproduce it by running the eval manually:

```
nix run nixpkgs#nix-eval-jobs -- --workers 1 --check-cache-status --force-recurse --flake 'github:nix-community/nixvim#checks'
```
