### ISSUE TITLE
[BUG] Alias @astrojs/language-server is still in node-packages.nix

### ISSUE THREAD

**Issue by biscotty666** [nix-community/nixvim#2010]
| Field        | Description |
|--------------|-------------|
| Plugin       | `<lsp?>`  | 
| Nixpkgs      | `<unstable>` | 
| Home Manager | `<unstable>` | 

- [ ] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

After updating my flake today, home-manager failed to build, giving the above error.

The specific update:
```
• Updated input 'nixvim':
    'github:nix-community/nixvim/c46bd820adabaf23acbccbbd226b1941566acb51' (2024-08-09)
  → 'github:nix-community/nixvim/4852f94f8ccae551514df0092a077014bafb95ca' (2024-08-09)
```

## Minimal, Reproducible Example (MRE)

Full trace attached

```nix
programs.nixvim = {
}
```
[fulltrace.txt](https://github.com/user-attachments/files/16571112/fulltrace.txt)

**Comment by MattSturgeon** [comment]
Upstream issue: https://github.com/NixOS/nixpkgs/issues/333677
Fixed in nixvim by: https://github.com/nix-community/nixvim/pull/2002

**Comment by biscotty666** [comment]
Thank you.
