### ISSUE TITLE
[BUG] lightline is generating a wrong key name for component_function

### ISSUE THREAD

**Issue by jaidTw** [nix-community/nixvim#2063]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lightline`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

The option [plugins.lightline.componentFunction](https://nix-community.github.io/nixvim/plugins/lightline/index.html#pluginslightlinecomponentfunction) has no effect.

I believe this is due to the generated lua code write this option to `vim.g.lightline.componentFunction`, which the key should really be `component_function` according to the plugin description, hence has no effect at all.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  extraConfigLua = ''
function myFunc()
  return "Hi"
end
'';
  plugins = {
      lightline = {
        enable = true;
        componentFunction = {
          myfunc = "v:lua.myFunc";
        };
        active = {
          right = [
            ["myfunc"]
          ];
      };
    };
  };
}
```

This should show Hi on the lightline

Generated `init.lua`:
```lua
-- Set up globals {{{
do
    local nixvim_globals = {
        lightline = {
            active = {
                right = {
                    { "myfunc" },
                },
            },
            -- This should be component_function
            componentFunction = { myfunc = "v:lua.myFunc" },
        },
    }

    for k, v in pairs(nixvim_globals) do
        vim.g[k] = v
    end
end
-- }}}
```

**Comment by khaneliman** [comment]
Thanks for posting this! It should be addressed soon as we do a refactor of it. I might tackle this next if it has a known bug.

**Comment by jaidTw** [comment]
Thanks for your quick fix!
