### ISSUE TITLE
[BUG] Conform plugin config using deprecated syntax for stop after first formatter

### ISSUE THREAD

**Issue by 347Online** [nix-community/nixvim#2064]
| Field        | Description |
|--------------|-------------|
| Plugin       | `conform-nvim` |
| Nixpkgs      | `unstable` |
| Home Manager | `unstable` |

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Conform has deprecated the nested list syntax for stopping after the first available formatter ([#491](https://github.com/stevearc/conform.nvim/pull/491)). New syntax for this uses a flat table, with an additional option `stop_after_first`. Using the previous syntax causes a warning to be shown the first time you the formatter in a given instance of neovim.

I find I end up closing and re-opening Neovim quite often, so I'm seeing this warning extremely frequently and it is very disruptive.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    enable = true;
    plugins.conform-nvim = {
        # See https://github.com/nix-community/nixvim/blob/1854d591cb0e5be6ad97f5091766cdf28e948265/plugins/lsp/conform-nvim.nix#L30
        # Use a sub-list to run only the first available formatter
        javascript = [ [ "prettierd" "prettier" ] ];
    };
}
```

**Comment by khaneliman** [comment]
Documentation looks like that option supports an attribute set of anything. https://nix-community.github.io/nixvim/plugins/conform-nvim/index.html#pluginsconform-nvimformattersbyft You should be able to do this yourself in its current form.
```nix
        javascript = {
          __unkeyed-1 = "prettierd";
          __unkeyed-2 = "prettier";
          timeout_ms = 2000;
          stop_after_first = true;
        };
```

**Comment by 347Online** [comment]
slick!

**Comment by khaneliman** [comment]
Thanks for bringing this up... while looking through documentation for the refactor, it looks like we were multiple versions behind on options and examples.

**Comment by 347Online** [comment]
My pleasure! Thanks for the lightning-fast response 😁
