### ISSUE TITLE
[PLUGIN REQUEST] Avante

### ISSUE THREAD

**Issue by edmundmiller** [nix-community/nixvim#2096]
| Field    | Description |
|----------|-------------|
| Plugin   | `Avante`  | 
| Homepage | `https://github.com/yetone/avante.nvim`     | 
| Nixpkgs  | `false` |

**Comment by elohmeier** [comment]
Some progress here: https://github.com/NixOS/nixpkgs/pull/339921

**Comment by GaetanLepage** [comment]
Indeed, it should land in unstable very soon.
Closing.

**Comment by elythh** [comment]
Isn't this issue about the Nixvim module rather than nixpkgs addition ?

**Comment by GaetanLepage** [comment]
> Isn't this issue about the Nixvim module rather than nixpkgs addition ?

Indeed I closed before I was thinking that this issue was posted on nixpkgs...

I have an opened PR to add it to nixvim: #2285
