### ISSUE TITLE
A flag to enable icon support in telescope

### ISSUE THREAD

**Issue by florentc** [nix-community/nixvim#2107]
The [`telescope.nvim`](https://github.com/nvim-telescope/telescope.nvim) plugin has support for icons through an optional dependeny: [`nvim-web-devicons`](https://github.com/nvim-tree/nvim-web-devicons).

In nixvim, there is no dedicated flag to enable this optional feature.

Depending on whether another plugin (e.g. `lualine`) that relies on `nvim-web-devicons` is enabled or not, the icon feature will be provided or not in telescope. If not, `pkgs.vimPlugins.nvim-web-devicons` may be added to `extraPlugins` manually.

I think it would be nice if there was a dedicated `plugin.telescope.enableIconSupport` flag to enable `nvim-web-devicons`.

**Comment by khaneliman** [comment]
This is something that I've thought of recently and wasn't sure if it was the best practice to keep adding options to every plugin that might use icons. Some plugins are just automatically adding it as a dependency, some offer it as an option like 

```nix
iconsEnabled = mkOption {
        type = types.bool;
        description = "Toggle icon support. Installs nvim-web-devicons.";
        default = true;
      };
```
I think for now, I can add it as a quick option, though. But, it would be nice to have an easier to maintain solution.

**Comment by MattSturgeon** [comment]
Nixvim doesn't have a well defined way to manage optional dependencies currently.

Most of the time (in newer code, anyway), we provide nullable `package` options, allowing users to a) set to null to forego installing and b) select a different version or overridden variant of the package to install instead.

Adding a `iconsPackage` option that defaults to `pkgs.vimPlugins.nvim-wev-devicons` but can be set to `null` if unwanted is probably the right approach here?
