### ISSUE TITLE
[Feature Request] `otter.activate()` automatically 

### ISSUE THREAD

**Issue by henrispriet** [nix-community/nixvim#2111]
| Field        | Description |
|--------------|-------------|
| Plugin       | `[otter.nvim](https://nix-community.github.io/nixvim/plugins/otter/index.html)`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I'm not sure whether this is really a bug.
When enabling otter via nixvim, I expected that when I open up any of my nixvim config files with lua snippets in them, I would now automatically get all the lsp features in those snippets. According to otter.nvim, one has to [activate otter](https://github.com/jmbuhr/otter.nvim/?tab=readme-ov-file#activate-otter) per document.

I'm just going to set up an autocommand for my own config now to call `require("otter").activate()` for every file opened, but maybe the `plugins.otter` module could do this automatically? Or perhaps as an option (`plugins.otter.auto_activate = true`)?

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.otter.enable = true;
  plugins.treesitter.enable = true;
  plugins.treesitter.settings.highlight.enable = true;
}
```

**Comment by khaneliman** [comment]
I have been meaning to use this plugin and forgot about it. But, I do see what you are talking about after adding it and trying it out. I wouldn't call it a bug, since it's the default behavior of the plugin and from the configuration used. But, now I am curious about what the proper way of auto loading it is. I'd assume we only want to load it with the lsp attach event handler...

**Comment by MattSturgeon** [comment]
> I'd assume we only want to load it with the lsp attach event handler...

In addition to the `on_attach` callback, there's also the `lsp_attach` autocmd event that we already use for registering lsp-plugin keybinds.
