### ISSUE TITLE
[BUG] Not possible to define custom extension for lualine

### ISSUE THREAD

**Issue by Wraul** [nix-community/nixvim#2130]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lualine`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

While migrating my configuration to NixVim I discovered a limitation that prevents me from completely achieving my desired configuration.

The upstream lualine plugin allows the user to define custom extensions by providing a object in the list of extensions. See [lualine documentation](https://github.com/nvim-lualine/lualine.nvim?tab=readme-ov-file#custom-extensions) for details.

Unless I'm missing something this isn't currently possible.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    plugins.lualine = {
      enable = true;
      extensions = [
        {
          sections = {
            lualine_a = [ "filename" ];
          };
          inactive_sections = {
            lualine_x = [ "location" ];
          };
          filetypes = [ "markdown" ];
        }
      ];
    };
}
```

**Comment by khaneliman** [comment]
I'm in the middle of migrating our lualine module to our new standards that will support this better in https://github.com/nix-community/nixvim/pull/2080.

**Comment by Wraul** [comment]
Thank you for expediting fixing this. It is very much appreciated :heart:.

Unfortunately the fix isn't 100% complete. This oversight could very much be due to my lackluster example though.
The regular sections has special handling for mapping "name" to the first element in the lua record. This is something that should happen in the extension sections as well.

So a more complete example would be like this

```nix
programs.nixvim = {
    plugins.lualine = {
      enable = true;
      extensions = [
        {
          sections = {
            lualine_a = [ {
              name = "branch";
              icon = "<U+F418>";
            }];
            lualine_y = [ "progress" ];
            lualine_z = [ "location" ];
          };
          inactive_sections = {
            lualine_x = [ "location" ];
          };
          filetypes = [ "fugitive" ];
        }
      ];
    };
}
```

And the extensions section should translate to the following lua

```lua
{
  extensions = {
    {
      filetypes = { "fugitive" },
      inactive_sections = { lualine_x = { "location" } },
      sections = {
        lualine_a = { { "branch", icon = "<U+F418>" } },
        lualine_y = { "progress" },
        lualine_z = { "location" },
    },
  },
},
```

But at the moment it appears to be translated to the following

```lua
{
  extensions = {
    {
      filetypes = { "fugitive" },
      inactive_sections = { lualine_x = { "location" } },
      sections = {
        lualine_a = { { icon = "<U+F418>", name = "branch" } },
        lualine_y = { "progress" },
        lualine_z = { "location" },
    },
  },
},
```

**Comment by MattSturgeon** [comment]
> The regular sections has special handling for mapping "name" to the first element in the lua record. This is something that should happen in the extension sections as well.

This is likely something we would remove when refactoring the plugin, as we try to avoid having any unpredictable transformations applied to freeform options.

Instead, you would have to use our "unkeyed" attrs hack:

```nix
{
  __unkeyed-1 = "a";
  __unkeyed-2 = "b";
  c = "c";
  d = "d";
}
```
=>
```lua
{
  "a",
  "b",
  c = "c",
  d = "d"
}
```

**Comment by Wraul** [comment]
@MattSturgeon I see, makes sense I guess.

Thank you so much for the hint! With that I was able to produce my desired configuration.
