### ISSUE TITLE
[PLUGIN REQUEST] grug-far

### ISSUE THREAD

**Issue by tknawara** [nix-community/nixvim#2133]
| Field    | Description |
|----------|-------------|
| Plugin   | `grug-far`  | 
| Homepage | `https://github.com/MagicDuck/grug-far.nvim`     | 
| Nixpkgs  | `https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/vim/plugins/generated.nix#L4684` | 

## Extra Information

it is a nice plugin for doing global find/replace utilizing ripgrep, I'm not sure if you want to have ripgrep installed as part of enabling the plugin though. I put nixpkgs as false for now, but ripgrep is available in nixpkgs

**Comment by 0x006E** [comment]
@tknawara Currently available in nixpkgs.  [vimPlugins.grug-far-nvim](https://search.nixos.org/packages?channel=24.11&show=vimPlugins.grug-far-nvim&from=0&size=50&sort=relevance&type=packages&query=grug-far). It would if I could use this instead of nvim-spectre
