### ISSUE TITLE
allowUnfree issue with allowUnfree = true

### ISSUE THREAD

**Issue by nagy135** [nix-community/nixvim#2147]
Hello, i have trouble upgrading my flake using nix flake update, it started saying that one plugin requires "allowUnfree" (copilot-vim) and it doesnt seem to register that that one is already there. I am using nix-darwin and home-manager that loads nixvim module.
And i cant get throught this error
```
       error: Package ‘vimplugin-copilot.vim-2024-07-10’ in /nix/store/9qq0zf30wi74pz66rr05zmxq0nv17q1p-source/pkgs/applications/editors/vim/plugins/generated.nix:2687 has an unfree license (‘unfree’), refusing to evaluate.

       a) To temporarily allow unfree packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNFREE=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnfree = true; }
       in configuration.nix to override this.

       Alternatively you can configure a predicate to allow specific packages:
         { nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
             "copilot.vim"
           ];
         }

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnfree = true; }
       to ~/.config/nixpkgs/config.nix.
```

Its saying really clearly what the issue is but the point is i already have `nixpkgs.config.allowUnfree = true;`. Also prefixing rebuild with env doesnt seem to fix it either. Can you give me some suggestion what to do? I am unable to upgrade :(

My entire config is here:
https://github.com/nagy135/nix-darwin/blob/master/flake.nix

**Comment by JeremieRodon** [comment]
I was able to workaround this bug by setting
```nix
nixpkgs.config.allowUnfreePredicate = _: true;
```
in my `home.nix`.
I was following the advice from this thread and it ended-up working for me:
[https://discourse.nixos.org/t/unfree-packages-on-flake-based-home-manager/30231](https://discourse.nixos.org/t/unfree-packages-on-flake-based-home-manager/30231)

**Comment by MattSturgeon** [comment]
> It's saying really clearly what the issue is but the point is I already have `nixpkgs.config.allowUnfree = true;`.

This sounds like you may have multiple instances of nixpkgs, some with allowUnfree and some without.

I.e. by default nix-darwin and home-manager will each create their own instance of nixpkgs.

Nixvim currently uses the "host"'s instance, but we'll likely change that in the future.

Home-manager can be configured to re-use the host's pkgs, by setting:

```nix
home-manager.useGlobalPkgs = true;
```

**Comment by JeremieRodon** [comment]
> Home-manager can be configured to re-use the host's pkgs, by setting:
> 
> ```nix
> home-manager.useGlobalPkgs = true;
> ```
I can confirm it also works for me and feels a lot less like a dirty hack. Thank you good sir!

**Comment by viniciuspalma** [comment]
```nix
      darwinConfigurations."${hostname}" = nix-darwin.lib.darwinSystem {
        inherit system specialArgs;
        modules = [
          ./modules/nix-core.nix
          ./modules/apps.nix
          ./modules/system.nix
          ./modules/host-users.nix
          home-manager.darwinModules.home-manager
          {
            home-manager = { 
              useGlobalPkgs = true;
              useUserPackages = true;
              extraSpecialArgs = specialArgs;
              users.${username} = { config, lib, pkgs, ... }: {
                imports = [
                  ./home
                  nixvimModule
                ];
              };
            };  
          }
        ];
      };

```

This isn't working I already have home-manager.useGlobalPkgs set to true and still receiving this issue

**Comment by MattSturgeon** [comment]
> Nixvim currently uses the "host"'s instance, but we'll likely change that in the future.

We did change this somewhat recently.

It is documented under [Recent Breaking Changes](https://nix-community.github.io/nixvim/#recent-breaking-changes):

> By default, Nixvim now constructs its own instance of nixpkgs, using the revision from our flake.lock.
> This change was largely motivated by: [How do I solve "`<name>` cannot be found in `pkgs`"](https://nix-community.github.io/nixvim/user-guide/faq.html#how-do-i-solve-name-cannot-be-found-in-pkgs)
>
> The old behaviour can be restored by enabling `nixpkgs.useGlobalPackages`.


While you _can_ use [`nixpkgs.useGlobalPackages`](https://nix-community.github.io/nixvim/platforms/hm.html#nixpkgsuseglobalpackages) which is effectively nixvim's equivalent to [`home-manager.useGlobalPkgs`](https://nix-community.github.io/home-manager/nixos-options.xhtml#nixos-opt-home-manager.useGlobalPkgs), I don't recommend this.

I've been meaning to update & improve the relevant docs, but usually the best practice is to a) allow nixvim to use its own locked nixpkgs revision (i.e. don't set `nixvim.inputs.nixpkgs.follows`) and b) allow nixvim to construct its own nixpkgs instance (i.e. don't enable `nixpkgs.useGlobalPackages`). The reason to do this is that nixvim is tested against the nixpkgs revision pinned in our lockfile, if you use a different revision you may run into unexpected issues.

If you have overlays or config that you want to apply to the nixpkgs instance used by nixvim, it can be specified in nixvim's [`nixpkgs.*` options](https://nix-community.github.io/nixvim/NeovimOptions/nixpkgs/index.html); if you're using home-manager that'd be `programs.nixvim.nixpkgs.*`.

If you understand the issues, and you really want to ensure you have a single common pkgs instance, you can also just use the [`nixpkgs.useGlobalPackages`](https://nix-community.github.io/nixvim/platforms/hm.html#nixpkgsuseglobalpackages) option.

**Comment by viniciuspalma** [comment]
If I understood you correctly @MattSturgeon, I need to not to set the `follows` attribute and let nixvim flake taken it's own nixpkgs, I did this and still not working 👎🏽 

```nix
    nixvim = {
      url = "github:nix-community/nixvim";
      # inputs.nixpkgs.follows = "nixpkgs";
    };

```

**Comment by viniciuspalma** [comment]
Seems that 

```nix
  programs.nixvim = {
    enable = true;

    nixpkgs = {
      config = {
        allowUnfree = true;
      };
    };
  }
```

Did the job, so a combination of removing the follows attribute from the flake input definition and adding the config explicitly on the nixvim config, made possible to install Copilot. I still not sure if this is the best approach, but it works for now, will be waiting for any feedback. But thank you for the support really appreciated it

**Comment by SamiSuleiman** [comment]
> Seems that
> 
>   programs.nixvim = {
>     enable = true;
> 
>     nixpkgs = {
>       config = {
>         allowUnfree = true;
>       };
>     };
>   }
> Did the job, so a combination of removing the follows attribute from the flake input definition and adding the config explicitly on the nixvim config, made possible to install Copilot. I still not sure if this is the best approach, but it works for now, will be waiting for any feedback. But thank you for the support really appreciated it

this worked without removing the "follows"

**Comment by relief-melone** [comment]
If you alredy have configured your pkgs (e.g. I configure it in my flake.nix)

```nix
pkgs = import nixpkgs  {
  config.allowUnfree  = true;
  # possibly more configuration
};
```

and you don't want to repeat yourself then this has also worked for me in the config for home manager

```nix
{ pkgs, ...}:
{
  programs.nixvim.nixpkgs.pkgs = pkgs;
}
```
