### ISSUE TITLE
[BUG] 'undodir' option does not recognize '~' and '$HOME'

### ISSUE THREAD

**Issue by bileamScheuvens** [nix-community/nixvim#2148]
| Field        | Description |
|--------------|-------------|
| Plugin       | `n/a`  | 
| Nixpkgs      | `unstable` | 

- [ X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
Setting the undodir option creates the directory locally, even if it begins with '\~' or '$HOME'. 
It interprets it literally and creates the structure .../'\~'/undodir/.
Easy to work around with lua or nix ```builtins.getEnv "HOME"```, but IMO unintuitive behavior.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  config.opts.undodir = "~/undodir";
}
```

**Comment by GaetanLepage** [comment]
I think that to get those paths properly expanded, you indeed need to call some lua code.
Can you try something like:
```nix
config.opts.undodir.__raw = "vim.fs.normalize('~/undodir')";
```

**Comment by MattSturgeon** [comment]
> Easy to work around with lua or nix `builtins.getEnv "HOME"`, but IMO unintuitive behavior.

If the alternative behaviour is to automatically transform option definitions when detecting `~` or `$HOME` in the string, this is even less intuitive IMO.

When I configure a nixvim option, I expect the `init.lua` file to have a lua-equivialent of whatever nix value I defined; without any arbitrary transformations being done without me knowing.
