### ISSUE TITLE
[PLUGIN REQUEST] Add somesass_ls LSP server

### ISSUE THREAD

**Issue by Yasso9** [nix-community/nixvim#2163]
Hi, thanks a lot for this amazing project !

Would it be possible to add somesass_ls, a LSP server for SCSS and SASS (alternative to CSS) ?

Here is the server configurations part on the LSP documentation : https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#somesass_ls

**Comment by khaneliman** [comment]
I couldn't find it in nixpkgs upstream. We need to get that added upstream before we can add a module for it.
