### ISSUE TITLE
[BUG] Alias eslint is still in node-packages.nix

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#2168]
I just updated my flake lock, and found I can no longer build nixvim.

Using standalone and even without any `follows`, I get:

```
error: Alias eslint is still in node-packages.nix
```

I suspect this was caused by #2160, specifically [this line](https://github.com/nix-community/nixvim/pull/2160/files#diff-d701989168ac134a24e9192c153e76d80ef5d40f16431647914fe2711da98bddR104).

What I can't figure out is why CI is happy here, yet my config fails to build...

**Comment by MattSturgeon** [comment]
https://github.com/MattSturgeon/nixvim/commit/e05a9e45b37a7f5bee61eda8ea4b296273afb2ab was working around the issue, but #2160 made it so that such workarounds are difficult to implement, and therefore removed the workaround.

https://github.com/NixOS/nixpkgs/pull/339641 will fix the issue upstream.

Rolling back nixvim can be used as a tempory workaround until we figure out how to deal with having dependencies on broken upstream packages...

```
nix flake lock --override-input nixvim github:nix-community/nixvim/2ef974182ef62a6a6992118f0beb54dce812ae9b
```

**Comment by ZainKergaye** [comment]
Thanks for keeping everyone updated, your workaround worked for me. Thanks!

**Comment by MattSturgeon** [comment]
The `eslint` alias fix has made it to nixos-unstable, however there seems to be a new upstream issue with _building_ `eslint`: https://github.com/NixOS/nixpkgs/issues/339301
