### ISSUE TITLE
[BUG] "Alias eslint is still in node-packages.nix" when installing nixvim as a home-manager module

### ISSUE THREAD

**Issue by ZogStriP** [nix-community/nixvim#2169]
| Field        | Description |
|--------------|-------------|
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I'm trying to switch from "regular" `neovim` to `nixvim` in https://github.com/ZogStriP/config/commit/4cce204146fefaf6c8579be1a4889d9c1ffa6b7c but I'm getting the following error when running `sudo nixos-rebuild switch --flake .`

```plain
error: Alias eslint is still in node-packages.nix
```

When I run the `nixos-rebuild switch` with `--show-trace` option, it points to an error in

https://github.com/NixOS/nixpkgs/blob/98d5d99cf6517b6ae13fb1f697d23b76223787ca/pkgs/development/node-packages/aliases.nix#L24-L28

Not sure what to do with that information or if I'm doing something wrong here 🤷‍♂️

Here's the full [stack trace](https://gist.github.com/ZogStriP/8e8671cb5d20414940a69681c38965c5) if that's helpful.

Any help would be greatly appreciated. Please do let me know if you need more information from my end as I'm not sure what to share.

**Comment by MattSturgeon** [comment]
I also ran into this (#2168). On nixvim's side this was triggered by #2160 however it is likely an upstream nixpkgs bug we've ran into.

You can workaround the issue by rolling nixvim back a few revisions:

```
nix flake lock --override-input nixvim github:nix-community/nixvim/2ef974182ef62a6a6992118f0beb54dce812ae9b
```

**Comment by ZogStriP** [comment]
Thanks a lot @MattSturgeon 👍 

My search-fu failed me this time 😢 _Sorry for the noise._

I also asked on https://discourse.nixos.org/t/alias-eslint-is-still-in-node-packages-nix-when-installing-nixvim-as-a-home-manager-module/51651 and someone linked to https://github.com/NixOS/nixpkgs/pull/339641 as a fix.

In the meantime, will try your workaround.

**Comment by ZogStriP** [comment]
> In the meantime, will try your workaround.

The workaround [worked](https://github.com/ZogStriP/config/commit/d1fddf0d8ea22295791a07600f8fce41dccbecbc) 👏 

Closing this as a duplicate of #2168.
