### ISSUE TITLE
[LSP REQUEST] basedpyright

### ISSUE THREAD

**Issue by Fr4nk1inCs** [nix-community/nixvim#2180]
| Field    | Description |
|----------|-------------|
| Plugin   | `basedpyright` in lspconfig https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#basedpyright | 
| Homepage | https://github.com/DetachHead/basedpyright     | 
| Nixpkgs  | [[nixpkgs.basedpyright]](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ba/basedpyright/package.nix) | 

## Extra Information

Should work like `pyright` LSP.

Basedpyright is a fork of pyright with various type checking improvements, improved vscode support and pylance features built into the language server.

**Comment by purepani** [comment]
i wonder if it's possible to just drop based pyright right into the package property of pyright.
