### ISSUE TITLE
[BUG] treesitter-just-grammar doesn't highlight anything

### ISSUE THREAD

**Issue by DoctorDalek1963** [nix-community/nixvim#2189]
| Field        | Description  |
|--------------|--------------|
| Plugin       | `treesitter` |
| Nixpkgs      | `unstable`   |

- [X] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When using Nixvim with treesitter, it highlights most filetypes completely fine, but `justfile`s don't get highlighted at all. If I run `:lua =require('nvim-treesitter.parsers').get_parser_configs()` in nvim, `just` is on the list, and is maintained by Hubro (but they seem to have no commits to nixvim, [tree-sitter-just](https://github.com/IndianBoy42/tree-sitter-just), or nixpkgs). And if I run `:checkhealth nvim-treesitter`, `just` has all 5 ticks.

## Minimal, Reproducible Example (MRE)

Create a file called `justfile` with the following contents:
```just
_default:
	@just --list

build profile:
	cargo build --profile {{profile}}
```

And build Nixvim with this config:

```nix
programs.nixvim = {
	plugins.treesitter.enable = true;
}
```

Now open the `justfile` with Nixvim and see that it's not highlighted at all. It should be highlighted like you see on GitHub.

**Comment by MattSturgeon** [comment]
Have you tried enabling treesitter's highlighting?

```diff
 programs.nixvim = {
 	plugins.treesitter.enable = true;
+	plugins.treesitter.settings.highlight.enable = true;
 }
```

**Comment by DoctorDalek1963** [comment]
Oh. Oops! That fixed my problem, thank you!
