### ISSUE TITLE
[BUG] Lualine options don't behave as like actual lualine configuration

### ISSUE THREAD

**Issue by Mikilio** [nix-community/nixvim#2191]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lualine`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins = {
    lualine = {
      enable = true;
      componentSeparators = "|"; #not accepted but is valid in lualine
      
      sections = {
        lualine_a = [
          { name = "mode"; separator.left = ""; padding.left = 2; } #not accepted but lua line totally accepts left_padding option
        ];
      };
   };
}
```

The above configuration describes some pain points with the module. It does not impair functionality, but is nice to have fixed. Separator works, however.

**Comment by MattSturgeon** [comment]
I think #2080 fixes this?

**Comment by khaneliman** [comment]
> I think #2080 fixes this? cc @khaneliman

Hmm.. I think that's related to the mkSeparatorsOption which right now wouldn't. I will need to update its definition to support it, I think.

**Comment by MattSturgeon** [comment]
> Hmm.. I think that's related to the mkSeparatorsOption which right now wouldn't. 

Ah, so even though `mkSeparatorsOption` uses a freeform submodule, the sub-options in question have type restrictions blocking this kinda config?

**Comment by khaneliman** [comment]
I made sure a single string is accepted for the separators, now in the refactor. 

> ```nix
>         lualine_a = [
>           { name = "mode"; separator.left = ""; padding.left = 2; } #not accepted but lua line totally accepts left_padding option
>         ];
> ```

This should work in the current configuration, already https://github.com/nix-community/nixvim/blob/c4135d720a5a57b7ddbd7ee918544c26b2c6f732/plugins/statuslines/lualine.nix#L59-L72.

**Comment by MattSturgeon** [comment]
> This should work in the current configuration, already or does it complain that right is missing?

With that option type, if `padding` is an attrset then both `left` and `right` are required by the module system.

If not set, we'll get "option used but not defined" when we try to render the value to lua using `toLuaObject`.

**Comment by khaneliman** [comment]
> > This should work in the current configuration, already or does it complain that right is missing?
> 
> With that option type, if `padding` is an attrset then both `left` and `right` are required by the module system.
> 
> If either are not set, we'll get "option used but not defined" when we try to render the value to lua using `toLuaObject`.
> 
> This is because they do not have default values.

Probably just do 

```nix
                      options = {
                        left = defaultNullOpts.mkInt null "Left padding.";
                        right = defaultNullOpts.mkInt null "Right padding.";
                      };

```

**Comment by khaneliman** [comment]
Looking at their documentation, it was a supported config in one of their tests, as well. https://github.com/nvim-lualine/lualine.nvim/blob/b431d228b7bbcdaea818bdc3e25b8cdbe861f056/examples/evil_lualine.lua#L120
