### ISSUE TITLE
none-ls: source packages missing 

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#2197]
It seems some of the none-ls source plugins are not being found in `pkgs`:

```
evaluation warning: python3.pkgs.cfn-lint cannot be found in pkgs!
evaluation warning: phpPackages.php-codesnifferpkgs cannot be found in pkgs!
evaluation warning: qt6.qtdeclarativepkgs cannot be found in pkgs!
evaluation warning: luaPackages.tl cannot be found in pkgs!
evaluation warning: rubyPackages.erb-formatterpkgs cannot be found in pkgs!
evaluation warning: phpPackages.php-codesnifferpkgs cannot be found in pkgs!
evaluation warning: phpPackages.php-cs-fixerpkgs cannot be found in pkgs!
evaluation warning: prisma cannot be found in pkgs!
evaluation warning: qt6.qtdeclarativepkgs cannot be found in pkgs!
```

https://github.com/nix-community/nixvim/blob/e1a5e39eb9d863f2ba8ec7d00eaa7f4ea29f688c/plugins/none-ls/packages.nix#L180

I think we need to add a check for `hasAtteByPath` in our `generated` test to avoid this regression again.

**Comment by khaneliman** [comment]
Prisma one doesn't make sense.. that's in nixos-unstable. Unless our lockfile is just behind that change, still?

**Comment by MattSturgeon** [comment]
After #2198 we're still left with:

```
evaluation warning: python3.pkgs.cfn-lint cannot be found in pkgs!
evaluation warning: luaPackages.tl cannot be found in pkgs!
evaluation warning: prisma cannot be found in pkgs!
```

**Comment by khaneliman** [comment]
So the first 2 I can't explain, yet. The third is just because our current nixpkgs revision is from before it was moved from nodePackages to top-level.

**Comment by MattSturgeon** [comment]
This one isn't using a list-type path:

https://github.com/nix-community/nixvim/blob/e1a5e39eb9d863f2ba8ec7d00eaa7f4ea29f688c/plugins/none-ls/packages.nix#L127

**Comment by khaneliman** [comment]
> This one isn't using a list-type path:
> 
> https://github.com/nix-community/nixvim/blob/e1a5e39eb9d863f2ba8ec7d00eaa7f4ea29f688c/plugins/none-ls/packages.nix#L127
> 
> Same:
> 
> https://github.com/nix-community/nixvim/blob/e1a5e39eb9d863f2ba8ec7d00eaa7f4ea29f688c/plugins%2Fnone-ls%2Fpackages.nix#L214

Doh... i feel dumb for missing that

**Comment by khaneliman** [comment]
I'll just add a TODO to remind me to clean it up after the flake.lock update. Since it'll get removed I'll leave it in that spot.
