### ISSUE TITLE
[BUG] Hardtime: 'enabled' option no longer works

### ISSUE THREAD

**Issue by hauskens** [nix-community/nixvim#2203]
| Field        | Description |
|--------------|-------------|
| Plugin       | `Hardtime`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
The commit https://github.com/nix-community/nixvim/commit/2de406d9722fd2c69641e8347641c4a655586956 seems to break the `plugins.hardtime.enabled` option. 

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.hardtime.enabled = true;
}
```
Workaround is to either using `plugins.hardtime.enable` or `nix flake lock --override-input nixvim github:nix-community/nixvim/810eacf5163b16b666ca70b6617c6a85ce412e0a`

**Comment by khaneliman** [comment]
Yeah, before the option to enable the plugin was shared with the enabled option that gets passed to the plugin config. If you’re just trying to enable the plugin, it’s enable if you’re trying to auto start the functionality set plugins.hardtime.settings.enabled

**Comment by khaneliman** [comment]
I think we missed a mkRemovedOption to give instructions

**Comment by MattSturgeon** [comment]
> Yeah, before the option to enable the plugin was shared with the enabled option

Did we have an `enable` _and_ and `enabled` before or just one shared options?

I missed this subtlety when reviewing :eyes: 

We probably need a `mkRenamedOptionModule (basePluginPath ++ [ "enabled" ]) (basePluginPath ++ [ "enable" ])` then.

**Comment by MattSturgeon** [comment]
Ah, we had both. I missed that.

https://github.com/nix-community/nixvim/blob/7409e80bd2dbbc5d653b27170d2fb33082150df3/plugins/utils/hardtime.nix#L15

and

https://github.com/nix-community/nixvim/blob/7409e80bd2dbbc5d653b27170d2fb33082150df3/plugins/utils/hardtime.nix#L48-L50

I think we can just add `"enabled"` to the `optionsRenamedToSettings` list then.

**Comment by khaneliman** [comment]
Yeah, my memory of the review was that it inherited the `enable` for `enabled` but that doesn't appear to be the case.
