### ISSUE TITLE
docs: use consistent admonitions syntax in options and user-guides

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#2217]
- [x] #2213
- [x] #2218
- [ ] #2221

#2213 added support for rendering github-flavoured "markdown alerts":

```md
> [!TIP]
> This is a tip
```

Using the mdbook-alerts preprocessor, we now renders this as:

```html
<div class="mdbook-alerts mdbook-alerts-tip">
  <p class="mdbook-alerts-title">
    <span class="mdbook-alerts-icon"></span>
    tip
  </p>
  <p>This is a tip</p>
</div>
```

> [!TIP]
> This is a tip

---

However, we render our option descriptions using [`nixos-render-docs`](https://github.com/NixOS/nixpkgs/blob/1376d89f1394fd5111a7306a3e72c8f9359e36d8/pkgs/tools/nix/nixos-render-docs/default.nix#L21), via the [`optionsCommonMark` function](https://github.com/NixOS/nixpkgs/blob/1376d89f1394fd5111a7306a3e72c8f9359e36d8/nixos/lib/make-options-doc/default.nix#L182-L190).
https://github.com/nix-community/nixvim/blob/e864f2c9e0cda66b0f419b2c3e36374c177d3712/docs%2Fmdbook%2Fdefault.nix#L13-L18

This takes an `options.json` file parses its markdown to an AST and spits out commonmark, asciidoc, or manpages (as requested).

Because it uses an abstract syntax tree, recognized-but-invalid symbols (such as `[foo]` where there's no corresponding `[foo]: URL`) end up being escaped (`\[foo\]`) in the resulting commonmark output.

It's also probably not a good idea to use syntax not supported by nixos-render-docs in option descriptions, since it will render poorly in the manpage docs.

---

As documented [here](https://github.com/NixOS/nixpkgs/blob/master/doc/README.md#admonitions), nixpkgs have adopted an alternative syntax for admonitions:

```md
::: {.warning}
This is a warning
:::
```

This is based on pandoc’s [fenced `div`s syntax](https://github.com/jgm/commonmark-hs/blob/master/commonmark-extensions/test/fenced_divs.md) which is _intended_ to be used to add HTML classes or IDs to the rendered `div`.

`nixos-render-docs options commonmark` will render the above as `**Warning:** This is a warning`, which mdbook then renders as:

```html
<p><strong>Warning:</strong> This is a warning</p>
```
**Warning:** This is a warning

[Implemented here](https://github.com/NixOS/nixpkgs/blob/8ae535d44c1b8002cf53c3456811306b6834cd6f/pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/commonmark.py#L46-L52).

**Comment by MattSturgeon** [comment]
### Rendering

I'm wondering if we need to use a patched `nixos-render-docs`? We could patch the [commonmark render code](https://github.com/NixOS/nixpkgs/blob/8ae535d44c1b8002cf53c3456811306b6834cd6f/pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/commonmark.py#L46-L52) to something like:

```python
def _admonition_open(self, kind: str) -> str:
    pbreak = self._maybe_parbreak()
    self._enter_block("> ")
    return f"{pbreak}> [!{kind}]\n{pbreak}> "
def _admonition_close(self) -> str:
    self._leave_block()
    return ""
```

### Parsing

We would probably also want to patch the parsing code to accept the GFM syntax? Or alternatively write a preprocessor to convert nixpkgs-style admonitions to GFM-style alerts.

If we don't do one of these, then we'd have to use GFM syntax in user-guides and plugin-descriptions, while using nixpkgs syntax in option descriptions...

**Comment by traxys** [comment]
Yeah I don't think it's too bad to patch out some programs to improve our documentation

**Comment by MattSturgeon** [comment]
#2218 implements the rendering side, which is the biggest blocker to actually _using_ alerts in option descriptions.

---

`nixos-render-docs` uses MarkdownIt to parse option descriptions, so we'll need to dig into that library a little and maybe write a plugin for it.

There's already a handful of related MarkdownIt plugins out there, this one is the most relevant: https://github.com/ByPikod/markdown-it-github-alert (MIT license)

We could look into how they do things, but we can't use the full implementation since we want to tokenise GFM alerts to the tokens `nixos-render-docs` already uses for its admonitions; e.g. [`AdmonitionKind`](https://github.com/NixOS/nixpkgs/blob/8ae535d44c1b8002cf53c3456811306b6834cd6f/pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/md.py#L46).

**Comment by MattSturgeon** [comment]
If consistency is all we're aiming for, perhaps it'd be simpler to implement nixpkg's admonitions syntax in mdbook, or as a pre-build step in our derivation _before_ calling mdbook.

That way we could use a consistent syntax in both places, even if it isn't the syntax I'd personally prefer. :thinking: 

If adding GFM-alert parsing to nixos-render-docs is simple, I'd prefer that though.
