### ISSUE TITLE
Option has wrong name

### ISSUE THREAD

**Issue by Mikilio** [nix-community/nixvim#2244]
https://github.com/nix-community/nixvim/blob/2d5949f65ca6060552ca5841716119c6d7d4bb54/plugins/by-name/markdown-preview/default.nix#L89

The actual option has no underscore. This options can not work this way

**Comment by khaneliman** [comment]
Thanks for catching that, since this is a freeform type you are free to provide the correct option name. But, I will create a pr to fix that.
