### ISSUE TITLE
alpha: allow for custom Lua code for sections.val

### ISSUE THREAD

**Issue by Mikilio** [nix-community/nixvim#2273]
https://github.com/nix-community/nixvim/blob/9307b201a3dc57d5b71ded4f897ea9d096544877/plugins/by-name/alpha/default.nix#L31

It makes only sense to allow for raw lua code to provide strings here, as it is a pain to define nix functions for it.

**Comment by khaneliman** [comment]
This whole plugin module needs to be rewritten but, if you are in a need for that rawlua support immediately, I can PR a fix for it.

**Comment by Mikilio** [comment]
It's not important since the entire plugin is just eye candy, but I appreciate the timely response. I actually think it's incredible.
