### ISSUE TITLE
[BUG] coq_nvim: cannot import name 'Cancellation' from 'std2.asyncio' 

### ISSUE THREAD

**Issue by msanft** [nix-community/nixvim#2282]
| Field        | Description |
|--------------|-------------|
| Plugin       | `coq-nvim`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When `coq-nvim` is enabled, nixvim runs into the following:

```
cannot import name 'Cancellation' from 'std2.asyncio' (/nix/store/3bcpp9gka30xwqlmqxcvk7m1xqq2aj8i-python3-3.12.5-env/lib/python3.12/site-packages/std2/asyncio/__init__.py)

Please update dependencies using :COQdeps
-
-
Dependencies will be installed privately inside `/home/msanft/.cache/coq_nvim/vars`
`rm -rf x1l4hv1r6c3mw2fah1g1p6xzzaqj1a9b-vimplugin-coq_nvim-2024-09-01` will cleanly remove everything
```

Presumably related to #400, #694

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
  coq-nvim.enable = true;
}
```

**Comment by msanft** [comment]
Hmm, I'm on `nixpkgs-unstable`, which should have this already, or am I mistaken?

**Comment by GaetanLepage** [comment]
> Hmm, I'm on `nixpkgs-unstable`, which should have this already, or am I mistaken?

There is a delay between `master` and `nixos-unstable`.
This PR has not made its way there yet. You can track the progress here: https://nixpk.gs/pr-tracker.html?pr=342643

**Comment by GaetanLepage** [comment]
Please, go and run `nix flake update`. It should be fixed.
