### ISSUE TITLE
[BUG] option `markview.settings.mode` should be `markview.settings.modes`

### ISSUE THREAD

**Issue by henrispriet** [nix-community/nixvim#2295]
| Field        | Description |
|--------------|-------------|
| Plugin       | `markview`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

See: https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-hybrid-mode
The second example ("insert-mode") does not work: insert mode does not give preview nor hybrid preview. I believe this is because the option `modes` was misspelled as `mode`.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.markview = {
    enable = true;

    settings = {
      mode = ["n" "i" "no" "c"];
      hybrid_modes = ["i"];
    };
  };
}
```

**Comment by khaneliman** [comment]
Thanks for reporting, it's a freeform field so feel free to pass the correct option. I'll fix our documentation.
