### ISSUE TITLE
Set `shorthandOnlyDefinesConfig = false;` in hm-config

### ISSUE THREAD

**Issue by DrRuhe** [nix-community/nixvim#2305]
## Description
The home manager module defines the nixvim module with `shorthandOnlyDefinesConfig = true;`. This means when trying to import a config module, one gets an error unless they make the nixvim config module into a function
https://github.com/nix-community/nixvim/blob/main/wrappers/hm.nix#L24

## Minimal, Reproducible Example (MRE)

```nix
# as a home-manager module
programs.nixvim = {
  imports = [
    ./nixvim-config.nix 
  ]
}
```
Causes the error `error: The option `home-manager.users.username.programs.nixvim.imports' does not exist.`

To fix it, one has to [declare the home manager to not be "shorthand"](https://nlewo.github.io/nixos-manual-sphinx/development/option-types.xml.html#:~:text=With%20this%20option%20enabled%2C%20defining%20a%20non%2Dconfig%20section%20requires%20using%20a%20function%3A%20the%2Dsubmodule%20%3D%20%7B%20...%20%7D%3A%20%7B%20options%20%3D%20%7B%20...%20%7D%3B%20%7D.), which gets rid of the error:

```nix
# as a home-manager module
programs.nixvim = {...}:{
  imports = [
    ./nixvim-config.nix 
  ]
}
```

# The Fix
Set `shorthandOnlyDefinesConfig = false;`. I dont see nixvim using a config option, so this should not break anything. 

## My Usecase
I want to expose nixvim as a package of my config flake as well as be part of the home manager config. Therefore I have one single config that defines the nixvim options which is then imported in my home-manager config and exposed as a package via `inputs'.nixvim.legacyPackages.makeNixvim`

**Comment by MattSturgeon** [comment]
Wouldn't this prevent someone defining nixvim options as follows:

```nix
programs.nixvim = {
  foo = "bar";
  bar = "baz";
};
```

And they'd instead need to do:

```nix
programs.nixvim = {
  config.foo = "bar";
  config.bar = "baz";
};
```

Or have I misinterpreted the purpose of `shorthandOnlyDefinesConfig`?

---

Also, I plan to replace the `submoduleWith` with `(evalNixvim {}).type`[^1], are you aware of how that'd fit in with this?

[^1]: [`evalNixvim`](https://github.com/nix-community/nixvim/blob/901346e38b81c236305e29934dd02c1f64bd8621/lib/modules.nix#L18-L42) is a thin-wrapper for `lib.evalModules`

**Comment by MattSturgeon** [comment]
Ok, re-reading [the docs](https://nixos.org/manual/nixos/unstable/#sec-option-types-submodule):

> *`shorthandOnlyDefinesConfig`* Whether definitions of this type should default to the `config` section of a module (see [Example: Structure of NixOS Modules](#ex-module-syntax)) if it is an attribute set. Enabling this only has a benefit when the submodule defines an option named `config` or `options`. In such a case it would allow the option to be set with `the-submodule.config = "value"` instead of requiring `the-submodule.config.config = "value"`. This is because only when modules *don't* set the `config` or `options` keys, all keys are interpreted as option definitions in the `config` section. Enabling this option implicitly puts all attributes in the `config` section.
>
> With this option enabled, defining a non-`config` section requires using a function: `the-submodule = { ... }: { options = { ... }; }`.

You're right, this option only has an effect when the submodule has a `config` or `options` sub-option. Historically, until #1324 we used to have an `options` option, so that is likely the original reason why we set `shorthandOnlyDefinesConfig`.

It won't be set when using [`(lib.evalModules {}).type`](https://github.com/NixOS/nixpkgs/blob/b4cde4d7f1fc84f6ff41ad165dab793dedaedfa0/lib/modules.nix#L327-L329), so I'll likely bundle the fix for this into the PR switching away from `submoduleWith`.

**Comment by DrRuhe** [comment]
Alright, thanks 👍
