### ISSUE TITLE
[BUG] plugins.transparent.enabled doesn't call Lua setup() without settings

### ISSUE THREAD

**Issue by cobbweb** [nix-community/nixvim#2310]
| Field        | Description |
|--------------|-------------|
| Plugin       | `transparent`  | 
| Nixpkgs      | `nixos-24.05` | 
| Home Manager | `release-24.05` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I added `plugins.transparent.enabled = true;` to my config, but the plugin doesn't work. It's meant to provide some Vim commands (`:TransparentToggle`, etc) but they're not registered either.

I manually added a Lua `setup({})` call, which fixes this issue:

```nix
    extraConfigLua = ''
      require('transparent').setup({})
    '';
```
I would have expected nixvim to automatically call `setup({})`, as it seems to with other plugins.

EDIT: I've realised I can get the plugin to setup by specifying some `plugins.transparent.settings...` too.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.transparent.enable = true;
  
   # Uncomment this line to make plugin work
   # plugins.transparent.settings = { };
   
   # Alternative solution:
   # extraConfigLua = ''
   #    require('transparent').setup({})
   # '';
}
```

**Comment by GaetanLepage** [comment]
This is weird because on my end, simply having `plugins.transparent.enable = true;` does call setup.
You can inspect your config using the `nixvim-print-init` command (shipped with nixvim).

**Comment by cobbweb** [comment]
Sorry for the delay, I've been away on holidays! I've just done some debugging using `nixvim-print-init` and you're correct that `plugins.transparent.enable = true;` is calling `setup({})`. I'm not what was happing, but it seems I can no longer replicate the issue :shrug:
