### ISSUE TITLE
[BUG] Enabling mini.icons with web-devicon mocking does not silence "automatically enabled" warning.

### ISSUE THREAD

**Issue by lunik1** [nix-community/nixvim#2330]
| Field        | Description |
|--------------|-------------|
| Plugin       | `mini`/`telescope`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I have started getting the following warning from my config:

```
trace: warning: Nixvim: `plugins.web-devicons` was enabled automatically because the following plugins are enabled.
This behaviour is deprecated. Please explicitly define `plugins.web-devicons.enable` or alternatively enable `plugins.mini.modules.icons` with `plugins.mini.mockDevIcons`.
plugins.telescope
```

but setting up mini as described does not seem to silence this, it only checks for `plugins.web-devicons`.

https://github.com/nix-community/nixvim/blob/ae2b9bd445ebe5d5342172c66ecbf60028070d32/plugins/deprecation.nix#L72

## Minimal, Reproducible Example (MRE)

```nix
{
  programs.nixvim = {
    plugins = {
      mini = {
        modules.icons = { };
        mockDevIcons = true;
      };

      telescope.enable = true;
    };
  };
}

```

**Comment by khaneliman** [comment]
This is intended, you haven't actually enabled the mini plugin. Seems we need to update the warning.
```nix
{
  programs.nixvim = {
    plugins = {
      mini = {
enable = true;
        modules.icons = { };
        mockDevIcons = true;
      };

      telescope.enable = true;
    };
  };
}
```

**Comment by lunik1** [comment]
Yep that did it, thanks.
