### ISSUE TITLE
[BUG] jupytext not found when running with jupytext-nvim

### ISSUE THREAD

**Issue by jalil-salame** [nix-community/nixvim#2367]
| Field        | Description |
|--------------|-------------|
| Plugin       | `jupytext`  | 
| Nixpkgs      | `24.05 (some packages come from unstable)`     | 
| Home Manager | `24.05`     | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

When installing the `jupytext` plugin and trying to open a `*.ipynb` file, this fails with `jupytext ... : 127` (command not found)

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.jupytext.enable = true;
}
```

## Other things I've tried

I have tried:
- setting `programs.nixvim.extraPython3Packages = p: [p.jupytext];` (same error)
- entering a devshell with `python3.jupytext` available (works properly)

**Comment by bkp5190** [comment]
Looks like you may need this:

https://search.nixos.org/packages?channel=24.05&show=python312Packages.jupytext&from=0&size=50&sort=relevance&type=packages&query=jupytext

~~~
home.packages = with pkgs; [
      python312Packages.jupytext
];
~~~

**Comment by jalil-salame** [comment]
No need for homeManager, you can fix it inside `nixvim`: ` extraPackages = [ (pkgs.python3.withPackages (p: [ p.jupytext ])) ];`.

Still, the plugin should do this automatically.

**Comment by bkp5190** [comment]
Merged a change for this dependency similar to other packages, can you retest this @jalil-salame ?

**Comment by jalil-salame** [comment]
Thanks for the help! Sadly the fix doesn't work:

```
zsh:1: command not found: jupytext
Error detected while processing BufReadCmd Autocommands for "*.ipynb":
jupytext '/home/jalil/Dev/jupyter-test/test.ipynb' --to=md:markdown --output='/home/jalil/Dev/jupyter-test/test.md' : 127
Error executing lua callback: Vim:E484: Can't open file /home/jalil/Dev/jupyter-test/test.md
stack traceback:
	[C]: in function 'readfile'
	...ckages/start/vimplugin-plugin-pack/lua/jupytext/init.lua:90: in function 'read_from_ipynb'
	...ckages/start/vimplugin-plugin-pack/lua/jupytext/init.lua:176: in function <...ckages/start/vimplugin-plugin-pack/lua/jupytext/init.lua:175>
```

Modifying `python3Dependecy` does not seem to add `jupytext` to the path.

You can see my configuration here: https://github.com/jalil-salame/configuration.nix

```console
$ nix build .#nvim
$ result/bin/nvim test.ipynb
```

Using this patch to disable my workaround:

```patch
diff --git a/nvim/dev-plugins.nix b/nvim/dev-plugins.nix
index b29f66b8d9..12e02fe811 100644
--- a/nvim/dev-plugins.nix
+++ b/nvim/dev-plugins.nix
@@ -127,7 +127,7 @@
       }
       # Jupyter notebooks
       {
-        extraPackages = [ (pkgs.python3.withPackages (p: [ p.jupytext ])) ];
+        # extraPackages = [ (pkgs.python3.withPackages (p: [ p.jupytext ])) ];
         plugins = {
           image.enable = enableExceptInTests;
           jupytext = {
```

My configuration is using commit be455f7f2714ce3479ae5bb662a03bd450f45793 which does contain the fix.

I am not familiar with nixvim's code, but my guess is that `python3Dependencies` do not add their binaries to nvim's path in the wrapper, because I cannot run `jupytext` from nvim's shell:

```console
$ result/bin/nvim --headless '+:!jupytext --version' '+:q'
:!jupytext --help
zsh:1: command not found: jupytext

shell returned 127
```

Using the version with my workaround:

```console
$ result/bin/nvim --headless '+:!jupytext --version' '+:q'
:!jupytext --version
1.16.4
```

**Comment by jalil-salame** [comment]
I'm thinking a test like this https://github.com/nix-community/nixvim/blob/5c6dd20aeb7fa868836cfb20ac2ec546cc3c977a/tests/test-sources/modules/performance/byte-compile-lua.nix#L227 should be added that checks if `jupytext` is in path.

**Comment by jalil-salame** [comment]
Looks like this is a jupytext issue (it doesn't look at the `g:python_host_prog` variable): https://github.com/GCBallesteros/jupytext.nvim/issue/24

**Comment by jalil-salame** [comment]
Huh, something seems to have fixed it because now I can do `:!python3 -m jupytext --version` and `:!jupytext --version` and both work (as does the `jupytext` plugin). Thank you so much for the help!
