### ISSUE TITLE
[Request] Treesitter Lua queries for Nix files

### ISSUE THREAD

**Issue by blackxored** [nix-community/nixvim#2396]
Given the amount of code people write in Lua, I think it would be great to include treesitter queries that automatically highlight lua code in `extraConfigLua` and friends, just started with nixvim today and is already hard to read the Lua code without syntax highlighting.

**Comment by khaneliman** [comment]
This is available already through our `plugins.treesitter.nixvimInjections`.

**Comment by MattSturgeon** [comment]
In addition to the [above](https://github.com/nix-community/nixvim/issues/2396#issuecomment-2401177310), there's also [hmts.nvim](https://github.com/calops/hmts.nvim?tab=readme-ov-file) which can be enabled via `plugins.hmts.enable`. This adds ts queries for several home-manager options and can be used alongside `plugins.treesitter.nixvimInjections`.
