### ISSUE TITLE
[BUG] <BUG> Trouble's auto_open throws error and does not auto open

### ISSUE THREAD

**Issue by whoisthis0192837465** [nix-community/nixvim#2398]
| Field        | Description |
|--------------|-------------|
| Plugin       | `Trouble`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

## Description

I tried to enable auto open in trouble, but then an error was thrown at every neovim startup

You specified `auto_open = true` in your global config.
This is probably not what you want.
Add it to the mode you want to auto open instead.
```lua
opts = {
  modes = {
    diagnostics = { auto_open = true },
  }
}
```
Disabling global `auto_open`.

## Minimal, Reproducible Example (MRE)

```nix
{ ... }: {
  programs.nixvim = {
    enable = true;
    plugins = {
      trouble = {
        enable = true;
        settings = {
          auto_close = true;
          auto_open = true;
        };
      };
    };
  };
}
```

**Comment by khaneliman** [comment]
Ah, I do see the plugin throws that message when it detects that... https://github.com/folke/trouble.nvim/blob/254145ffd528b98eb20be894338e2d5c93fa02c2/lua/trouble/config/init.lua#L223-L234 We will need to update the settings to redirect... I wonder if that was the previous behavior and we just never updated with new trouble version.

**Comment by khaneliman** [comment]
Yeah, looks like in 2.X they had everything global level. Thanks for reporting, will update when I get a chance.
