### ISSUE TITLE
[BUG] Haskell Language Server needs GHC

### ISSUE THREAD

**Issue by HeitorAugustoLN** [nix-community/nixvim#2413]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lsp`  | 
| Nixpkgs      | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Just like `rust-analyzer` depends on `cargo` and `rustc`. `haskell-language-server` needs to be installed so it can work.
A solution could be installing it with `haskell-language-server`, or just like `rust-analyzer`, it could be an option (which I think should be better)

![image](https://github.com/user-attachments/assets/3ebec231-6512-4782-85dd-c999d9d0bb5c)

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  lsp.enable = true;
  lsp.servers.hls = {
    enable = true;
    filetypes = [ "cabal" "haskell" "lhaskell" ];
  };
}
```

**Comment by GaetanLepage** [comment]
Thanks for reporting this. I opened #2416 that adopts the same strategy as for `rust_analyzer`.
