### ISSUE TITLE
`lsp.servers.ocamllsp` is broken

### ISSUE THREAD

**Issue by computerscience-person** [nix-community/nixvim#2415]
| Field        | Description |
|--------------|-------------|
| Plugin       | `ocamllsp`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Error message:

```
error: The option `programs.nixvim.plugins.lsp.servers.ocamllsp.package' was accessed but has no value defined. Try setting the option.
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
plugins.lsp.servers.ocamllsp.enable = true;
}
```

**Comment by computerscience-person** [comment]
Oops, `ocamllsp` was silently changed. IG my bad for not reading release notes?

**Comment by MattSturgeon** [comment]
See https://github.com/nix-community/nixvim/issues/2412
