### ISSUE TITLE
[BUG] FTPlugin for markdown (tab size 2)

### ISSUE THREAD

**Issue by anotherhadi** [nix-community/nixvim#2418]
| Field        | Description |
|--------------|-------------|
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [ x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

For my markdowns files I want to set tabs size to 2 spaces.
I tried to set it using ftplugins but it looks like it has no effect on my configuration. (The file is created in the ftplugin directory)

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    extraFiles = {
      "ftplugin/markdown.lua".text = ''
        vim.opt.tabstop = 2
        vim.opt.shiftwidth = 2
        vim.opt.expandtab = true 
      '';
    };
}
```

**Comment by stasjok** [comment]
This is not specific to NixVim. First of all, for buffer-local options, you should use `vim.bo` or `vim.opt_local` (or it'll be remembered and used as default values for all new buffers). Secondly, to extend the default ftplugin, use the "after" directory. For more information, see `:h ftplugin`. Try this:
```nix
programs.nixvim = {
    extraFiles = {
      "after/ftplugin/markdown.lua".text = ''
        vim.bo.tabstop = 2
        vim.bo.shiftwidth = 2
        vim.bo.expandtab = true 
      '';
    };
}
```

**Comment by anotherhadi** [comment]
> This is not specific to NixVim. First of all, for buffer-local options, you should use `vim.bo` or `vim.opt_local` (or it'll be remembered and used as default values for all new buffers). Secondly, to extend the default ftplugin, use the "after" directory. For more information, see `:h ftplugin`. Try this:
> 
> ```nix
> programs.nixvim = {
>     extraFiles = {
>       "after/ftplugin/markdown.lua".text = ''
>         vim.bo.tabstop = 2
>         vim.bo.shiftwidth = 2
>         vim.bo.expandtab = true 
>       '';
>     };
> }
> ```

Now working, awesome thanks!
