### ISSUE TITLE
[PLUGIN REQUEST] nabla.nvim

### ISSUE THREAD

**Issue by Mcrtin** [nix-community/nixvim#2423]
| Field    | Description |
|----------|-------------|
| Plugin   | `nabla.nvim`  |
| Homepage | `[<URL>](https://github.com/jbyuki/nabla.nvim/)`     | 
| Nixpkgs  | `https://search.nixos.org/packages?query=nabla` | 

## Extra Information

Have the default keybind `<leader>p` be enabled by default maybe and make it able to change.
There also should be an option for virt_lines.

**Comment by GaetanLepage** [comment]
I have made the PR.
We don't set keymaps automatically as we wish to stay as neutral as possible.

You would just have to add:
```nix
plugins.nabla.enable = true;
keymaps = [
  {
    key = "<leader>p";
    action.__raw = "require('nabla').popup";
  }
];
```
