### ISSUE TITLE
[LSP] specify a default package for `kulala-ls`

### ISSUE THREAD

**Issue by SymphonySimper** [nix-community/nixvim#2427]
| Field    | Description |
|----------|-------------|
| Plugin   | `kulala-ls`  | 
| Homepage | `https://github.com/mistweaverco/kulala-ls`     | 
| Nixpkgs  | `false` | 

## Extra Information
- [nvim-lspconfig for kulala-ls](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#kulala_ls)
- There is an open package request in `nixpkgs` ([#347263](https://github.com/NixOS/nixpkgs/issues/347263))

**Comment by khaneliman** [comment]
Needs to be packaged upstream, first.

**Comment by Eveeifyeve** [comment]
> Needs to be packaged upstream, first.

It doesn't necessarily have to be you just have to set `package = null;`

**Comment by Eveeifyeve** [comment]
Also I would wait for https://github.com/nix-community/nixvim/pull/2393.

**Comment by MattSturgeon** [comment]
Since we generate everything under `plugins.lsp.servers` automatically (from `nvim-lspconfig` data) I'm not sure if this is still a valid issue?

**Comment by SymphonySimper** [comment]
> Since we generate everything under `plugins.lsp.servers` automatically (from `nvim-lspconfig` data) I'm not sure if this is still a valid issue?

I feel like the issue should be open till there is a default package.

**Comment by Eveeifyeve** [comment]
> > Since we generate everything under `plugins.lsp.servers` automatically (from `nvim-lspconfig` data) I'm not sure if this is still a valid issue?
> 
> I feel like the issue should remain open until there is a default package.

I mean a new issue should be created at nixpkgs to request for the package. This is not a nixvim issue but a nixpkgs issue.

**Comment by SymphonySimper** [comment]
> > > Since we generate everything under `plugins.lsp.servers` automatically (from `nvim-lspconfig` data) I'm not sure if this is still a valid issue?
> > 
> > 
> > I feel like the issue should remain open until there is a default package.
> 
> I mean a new issue should be created at nixpkgs to request for the package. As this is not a nixvim issue but a nixpkgs issue.

But enabling `kulala_ls` results in a build failure as it does not have default package. So I feel like this is still related to `nixvim`.

**Comment by Eveeifyeve** [comment]
> > > > Since we generate everything under `plugins.lsp.servers` automatically (from `nvim-lspconfig` data) I'm not sure if this is still a valid issue?
> > > 
> > > 
> > > I feel like the issue should remain open until there is a default package.
> > 
> > 
> > I mean a new issue should be created at nixpkgs to request for the package. As this is not a nixvim issue but a nixpkgs issue.
> 
> But enabling `kulala_ls` results in a build failure as it does not have default package. So I feel like this is still related to `nixvim`.

Not really, easy fix is set kulala package to null and it will fix the error. It's just that nixpkgs hasn't packaged kulala_ls at all until they package the kulala_ls to nixpkgs you will have to set package to null.

**Comment by Eveeifyeve** [comment]
I will look to add this to the documentation of lsp plugin as it's not really a nixvim issue, yes nixvim expects the package but it's not available in nixpkgs until it's available the only fix is to set the package to null.

**Comment by traxys** [comment]
I'll note that there are a large number of such servers

**Comment by SymphonySimper** [comment]
> I will look to add this to the documentation of lsp plugin as it's not really a nixvim issue, yes nixvim expects the package but it's not available in nixpkgs until it's available the only fix is to set the package to null.

Yep, I know settings null will resolve the build failure. But then it throw a executable not found error.
```Spawning language server with cmd: `{ "kulala-ls", "--stdio" }` failed. The language server is either not installed, missing from PATH, or not executable.```

Then to resolve this, users have to install the executable using language specific package manager (in this case `npm`). I understand having support for LSP configuration even if there is no package is available is better.

So, instead can we create a issue tracker to track for all missing LSP servers in upstream? If this is out of scope of the project, I totally understand it. And the issue can be closed if that's the case.

**Comment by Eveeifyeve** [comment]
> > I will look to add this to the documentation of lsp plugin as it's not really a nixvim issue, yes nixvim expects the package but it's not available in nixpkgs until it's available the only fix is to set the package to null.
> 
> Yep, I know settings null will resolve the build failure. But then it throw a executable not found error. `` Spawning language server with cmd: `{ "kulala-ls", "--stdio" }` failed. The language server is either not installed, missing from PATH, or not executable. ``
> 
> Then to resolve this, users have to install the executable using language specific package manager (in this case `npm`). I understand having support for LSP configuration even if there is no package is available is better.
> 
> So, instead can we create a issue tracker to track all missing LSP servers in upstream? If this is out of scope of the project, I totally understand it. And the issue can be closed if that's the case.

I guess that could be a good idea but it's not nixvim problem it's again nixpkgs thing.

**Comment by Eveeifyeve** [comment]
But yeah until it's upstream on unstable nixpkgs, it's a nixpkgs issue.

**Comment by SymphonySimper** [comment]
Yep, I will close the issue. And open a issue tracker within a day or two.

**Comment by MattSturgeon** [comment]
Related issue: https://github.com/nix-community/nixvim/issues/2412
