### ISSUE TITLE
[PLUGIN REQUEST] NotebookNavigator.nvim 

### ISSUE THREAD

**Issue by ryan-ressmeyer** [nix-community/nixvim#2449]
| Field    | Description |
|----------|-------------|
| Plugin   | NotebookNavigator.nvim  |
| Homepage | https://github.com/GCBallesteros/NotebookNavigator.nvim  |
| Nixpkgs  | `false` | 

## Extra Information

Notebook navigator allows VSCode-like cell execution from .py (or other) files without the need for a complete notebook environment. This functionality greatly increases my productivity and I'd love to see it as a part of nixvim!

**Comment by GaetanLepage** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/350718 to add it upstream.
