### ISSUE TITLE
[BUG] pylsp causes extreme lag when switching python buffers in large projects

### ISSUE THREAD

**Issue by charludo** [nix-community/nixvim#2451]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lsp`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

In large python projects, simply having `programs.nixvim.plugins.lsp.servers.pylsp.enable = true;` in the nix config leads to extreme lag when switching to or from buffers in which `.py` files are open.

For a project with ~75k  LoC, I am getting a >10s timeout in which nvim is completely frozen every time I
- switch from a py buffer to another buffer
- switch from some buffer to a by buffer
- exit insert mode

I am not really certain if this is a nixvim, neovim, lsp, or pylsp issue. However, I could not find existing issues for the other projects, and since they are quite a bit larger,... 😅 

## Minimal, Reproducible Example (MRE)

- set `programs.nixvim.plugins.lsp.servers.pylsp.enable = true;`
- open a python file from a large project in a buffer
- open a second py file from that project in a second buffer

**Comment by traxys** [comment]
It's possible that nixvim configures pylsp in a sub-par nonstandard way, but I think it's more likely an issue with either pylsp or neovim.
In order to diagnose this you could try to use `nixvim-print-init` to generate a minimal init.lua to try and put nixvim out of the picture.

**Comment by charludo** [comment]
> `nixvim-print-init`

Nice, did not know about this!

Using the generated config, I did still get *some* lag, but only a fraction of a second.

**Comment by charludo** [comment]
Turns out it was not pylsp after all, it was pylint (via the `lint` plugin). I must have fucked up commenting out just the LSP config, accidentally fixing my problem 🤦🏼‍♀️ 

Anyways, removing `programs.nixvim.plugins.lint.linterByFt.python = [ "pylint" ];` from the config and adding 
```nix
pylint.enabled = true;
pylint.package = pkgs.pylint;
```
fixed my issue.

There's still something funky going on (from the timing it almost appear like the entire project is re-linted every time a buffer is focused?), but the is a perfect workaround for me, so I'll mark as closed :)
