### ISSUE TITLE
[PLUGIN REQUEST] flutter-tools.nvim

### ISSUE THREAD

**Issue by Daru-san** [nix-community/nixvim#2470]
| Field    | Description |
|----------|-------------|
| Plugin   | `flutter-tools.nvim`  | 
| Homepage | `https://github.com/nvim-flutter/flutter-tools.nvim`     | 
| Nixpkgs  | `https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/vim/plugins/generated.nix#L4072` | 

## Extra Information

Flutter-tools is an extensive plugin with many flutter-specific features that enhance flutter development in neovim.

### Features

- Telescope support 
- In-editor `flutter run`
- Debugging
- Widget guides
- Nvim-dap support
- Statusline decoration with app version
- Closing tags
- Hot reloading

**Comment by GaetanLepage** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/352744

**Comment by GGORG0** [comment]
Hi, are there any updates on flutter-tools support?
