### ISSUE TITLE
[PLUGIN REQUEST] <FastAction.nvim>

### ISSUE THREAD

**Issue by Shringe** [nix-community/nixvim#2471]
| Field    | Description |
|----------|-------------|
| Plugin   | `Improved LSP Code Actions prompt`  | 
| Homepage | `https://github.com/Chaitanyabsprip/fastaction.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information
The plugin provides a nice Code Actions menu, simiar to nvim-cmp, with keys automatically assinged to actions, similar to `f` in the Vimium browser plugin.

**Comment by GaetanLepage** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/352744
