### ISSUE TITLE
[BUG] Home-manager not working on nixos-24.05

### ISSUE THREAD

**Issue by mfiumara** [nix-community/nixvim#2473]
| Field        | Description |
|--------------|-------------|
| Plugin       | `<any>`  | 
| Nixpkgs      | `<24.05>` | 
| Home Manager | `<stable>` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Hi, I am new to nixOS but I cannot seem to get this working. I have added nixvim pinned to 24.05 to my configuration and then whenever I try to set load any plugin it cannot be loaded, for example lualine:
```
Error detected while processing /home/mattiaf/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/mattiaf/.config/nvim/init.lua:6: module 'lualine' not found:
        no field package.preload['lualine']
        no file '/nix/store/rwf92hm6drz4rgng9r2hsviqsvpwdjb7-luajit-2.1.1693350652-env/share/lua/5.1/lualine.lua'
        no file '/nix/store/rwf92hm6drz4rgng9r2hsviqsvpwdjb7-luajit-2.1.1693350652-env/share/lua/5.1/lualine/init.lua'
        no file '/nix/store/rwf92hm6drz4rgng9r2hsviqsvpwdjb7-luajit-2.1.1693350652-env/lib/lua/5.1/lualine.so'
```

Also colorschemes do not load when set in my configuration.
## Minimal, Reproducible Example (MRE)
My `/etc/nixos/configuration.nix`:
```nix
{ config, pkgs, ... }:

let
  nixvim = import (builtins.fetchGit {
    url = "https://github.com/nix-community/nixvim";
    ref = "nixos-24.05";
  });
in
{
  imports =
    [ # Include the results of the hardware scan.
      /etc/nixos/hardware-configuration.nix
      <home-manager/nixos>
    ];
  # Define home-manager settings inside configuration as module
  home-manager.users.mattiaf = { pkgs, ... }: {
    imports = [ nixvim.homeManagerModules.nixvim ];
    programs = {
     nixvim = {
       enable = true;
       plugins = {
         lualine.enable = true;
	 nvim-tree.enable = true;
       };
     };
    };
 
    home.stateVersion = "24.05";
  };
```

**Comment by dddictionary** [comment]
Bump! I'm currently facing this issue right now. For some reason, the colorschemes were just not loading properly. I would add `colorschemes.catppuccin.enable = true` from the docs but the lua files for it would not be found. I got rid of the option for colorschemes and instead have this:

  ```nix
  { config, pkgs, lib, ... }:
let inherit (config.nixvim) helpers;
in {
  programs.nixvim = {
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;

    opts = {
      number = true;
      relativenumber = true;
      shiftwidth = 2;
    };

    luaLoader.enable = true;
    plugins.lualine.enable = true;

    # colorschemes.catppuccin.enable = true;
  };
}
```
This gives me the following error:
```
Error detected while processing /home/abrar/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/abrar/.config/nvim/init.lua:16: module 'lualine' not found:
        no field package.preload['lualine']
cache_loader: module lualine not found
cache_loader_lib: module lualine not found
        no file '/nix/store/ykymiyddxidkckg5jyr4lmk61l90lbg2-luajit-2.1.1693350652-env/share/lua/5.1/lualine.lua'
        no file '/nix/store/ykymiyddxidkckg5jyr4lmk61l90lbg2-luajit-2.1.1693350652-env/share/lua/5.1/lualine/init.lua'
        no file '/nix/store/ykymiyddxidkckg5jyr4lmk61l90lbg2-luajit-2.1.1693350652-env/lib/lua/5.1/lualine.so'
stack traceback:
        [C]: in function 'require'
        /home/abrar/.config/nvim/init.lua:16: in main chunk
```

I get a similar error like this when I uncomment the `colorschemes.catppuccin.enable` line.

Anyone have any ideas?

**Comment by mateusz2173** [comment]
I'm facing same issue when I try to enable any colorscheme or plugin, I get "module <plugin/colorscheme> not found" error

**Comment by GaetanLepage** [comment]
`nixos-24.11` has just been released. Can you try switching to it maybe ?

**Comment by morphe157** [comment]
It did not help,

Here is my config:

<details>
<summary>flake.nix</summary>

```nix
{
  description = "Your new nix config";

  inputs = {
    # Nixpkgs
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.11";

    home-manager = {
	url = "github:nix-community/home-manager/release-24.11";
        inputs.nixpkgs.follows = "nixpkgs";
    };

    nixvim = {
      url = "github:nix-community/nixvim/nixos-24.11";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    home-manager,
    nixvim,
    ...
  } @ inputs: let
    inherit (self) outputs;
  in {
    # Standalone home-manager configuration entrypoint
    # Available through 'home-manager --flake .#your-username@your-hostname'
    homeConfigurations = {
      # FIXME replace with your username@hostname
      "morphe" = home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.x86_64-linux; # Home-manager requires 'pkgs' instance
        extraSpecialArgs = {inherit inputs outputs;};
        # > Our main home-manager configuration file <
        modules = [
	  ./home.nix
	  nixvim.homeManagerModules.nixvim
	];
      };
    };
  };
}

```

</details>

<details>
<summary>home.nix</summary>

```nix
{config, pkgs, inputs, home-manager, ...}:
let 
  username = "morphe";
in
{
#  imports = [
#      nixvim.homeManagerModules.nixvim
#  ];
  home = {
    inherit username;
    stateVersion = "24.11";
    homeDirectory = "/home/${username}";
      packages = with pkgs; [
	bat
	btop
	neofetch
	jq
	tmux
	alacritty
      ];
  };

  programs.home-manager.enable = true;
  programs.nixvim = {
     enable = true;
     luaLoader.enable = true;
     plugins.oil.enable = true;
  };
}
```
</details>

**Comment by traxys** [comment]
Alternatively, are you sure you are using the correct neovim? i.e what is the result of `which neovim`

**Comment by morphe157** [comment]
init.lua:
```lua
-- Nixvim's internal module table
-- Can be used to share code throughout init.lua
local _M = {}

vim.loader.enable()
require("oil").setup({})
```

`which nvim` looks fine

```
λ which nvim
/home/morphe/.nix-profile/bin/nvim
```

**Comment by morphe157** [comment]
OK so I manager to make it work, not sure how exactly;

What I did:
1. `pacman -Syu`
2. Delete `flake.lock`
3. `nix-collect-garbage -d`
4. `git add . && git commit`
5. Run again

And it started working

**Comment by dddictionary** [comment]
I solved the issue by making sure that I had not downloaded any other version of neovim on my system. I had installed neovim in my `configuration.nix` as well as I had kept the `programs.neovim.enable` option for home-manager set to true. I believe this kept overwriting the nixvim settings. Just make sure you install neovim only once, and also enable it only once.

**Comment by GaetanLepage** [comment]
> I solved the issue by making sure that I had not downloaded any other version of neovim on my system. I had installed neovim in my `configuration.nix` as well as I had kept the `programs.neovim.enable` option for home-manager set to true. I believe this kept overwriting the nixvim settings. Just make sure you install neovim only once, and also enable it only once.

Indeed, this impurity is the culprit.
Thanks for having reported your solution !

**Comment by SeraphimRP** [comment]
> I solved the issue by making sure that I had not downloaded any other version of neovim on my system. I had installed neovim in my `configuration.nix` as well as I had kept the `programs.neovim.enable` option for home-manager set to true. I believe this kept overwriting the nixvim settings. Just make sure you install neovim only once, and also enable it only once.

Just to add onto this for any future visits, make sure you check `nix-env` (and rollbacks of it) for any installations of neovim.
