### ISSUE TITLE
[PLUGIN REQUEST] muren.nvim

### ISSUE THREAD

**Issue by altacountbabi** [nix-community/nixvim#2482]
| Field    | Description |
|----------|-------------|
| Plugin   | `muren.nvim`  | 
| Homepage | `https://github.com/AckslD/muren.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information
A plugin for multiple replacements

**Comment by GaetanLepage** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/353828.
