### ISSUE TITLE
[PLUGIN REQUEST] Haskell Lsp

### ISSUE THREAD

**Issue by VoreckLukas** [nix-community/nixvim#2483]
| Field    | Description |
|----------|-------------|
| Plugin   | Not directly a vim plugin but  a lsp for the haskell language to be included   | 
| Homepage | https://github.com/haskell/haskell-language-server     | 
| Nixpkgs  | [haskell-language-server](https://search.nixos.org/packages?channel=unstable&show=haskell-language-server&from=0&size=50&sort=relevance&type=packages&query=haskell+lsp) | 

## Extra Information

Should be mostly the same as any other lsps

**Comment by VoreckLukas** [comment]
Just realized its there just not under the name i expected

**Comment by MattSturgeon** [comment]
Glad you found a solution!

For anyone else stumbling on this issue, see [`plugins.lsp.servers.hls`](https://nix-community.github.io/nixvim/plugins/lsp/servers/hls/index.html) and the [nvim-lspconfig `hls` docs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#hls).
