### ISSUE TITLE
[BUG] globalOpts.signcolumn = "no" does not work

### ISSUE THREAD

**Issue by jasper-clarke** [nix-community/nixvim#2487]
| Field        | Description |
|--------------|-------------|
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Setting `globalOpts.signcolumn` to `"no"` is not working and when entering neovim and running `:set signcolumn` it shows `auto`.

Running `:set signcolumn=no` once neovim is open, removes the signcolumn.

My configuration: https://github.com/jasper-clarke/neovim/blob/nixvim/config/options.nix#L5

**Comment by khaneliman** [comment]
Just curious if you tried with no plugins to see if there's something setting it up differently through an autoCmd or something.

**Comment by jasper-clarke** [comment]
Thanks for your reply @khaneliman 
I removed my plugins.nix and the issue is still persistent.
I also checked my own autoCmd's and nothing is triggering signcolumn.

**Comment by khaneliman** [comment]
Alright, taking a look.

**Comment by khaneliman** [comment]
>vim.opt
The most convenient way for setting global and local options, e.g., in init.lua,
is through vim.opt and friends:
[vim.opt](https://neovim.io/doc/user/lua.html#vim.opt): behaves like [:set](https://neovim.io/doc/user/options.html#%3Aset)
[vim.opt_global](https://neovim.io/doc/user/lua.html#vim.opt_global): behaves like [:setglobal](https://neovim.io/doc/user/options.html#%3Asetglobal)
[vim.opt_local](https://neovim.io/doc/user/lua.html#vim.opt_local): behaves like [:setlocal](https://neovim.io/doc/user/options.html#%3Asetlocal)

Have you tried using opts ? 
https://github.com/nix-community/nixvim/blob/aabbd60633947baba11db44df84f402edc241440/modules/opts.nix#L9-L14

**Comment by jasper-clarke** [comment]
@khaneliman 
Using `opts.signcolumn = "no";` works.
Thanks very much for the help.
