### ISSUE TITLE
[BUG] base16 colorscheme not working despite successful build

### ISSUE THREAD

**Issue by xqtc161** [nix-community/nixvim#2489]
| Field        | Description |
|--------------|-------------|
| Plugin       | `colorschemes.base16`  | 
| Nixpkgs      | `nixos-unstable` | 
| Home Manager | follows nixpkgs | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
I have enabled the apathy colorscheme with the base16 colorscheme plugin. My nixvim configuration builds without errors, however when i start neovim I get following error:
```
Error detected while processing /home/xqtc/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/xqtc/.config/nvim/init.lua:66: module 'base16-colorscheme' not found:
        no field package.preload['base16-colorscheme']
        no file '/nix/store/5d2mg8la2b9haxk007nknv54l5qb97xf-luajit-2.1.1713773202-env/share/lua/5.1/base16-colorscheme.lua'
        no file '/nix/store/5d2mg8la2b9haxk007nknv54l5qb97xf-luajit-2.1.1713773202-env/share/lua/5.1/base16-colorscheme/init.lua'
        no file '/nix/store/5d2mg8la2b9haxk007nknv54l5qb97xf-luajit-2.1.1713773202-env/lib/lua/5.1/base16-colorscheme.so'
stack traceback:
        [C]: in function 'require'
        /home/xqtc/.config/nvim/init.lua:66: in main chunk
```
I have checked the luajit env path listed in the thrown error in the nix-store and there is indeed nothing related to the base16 plugin.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
  colorschemes.base16 = {
    enable = true;
    colorscheme = "apathy";
    settings.telescope_borders = true;
  };
}
```

My full system configuration can be found [here](https://git.gay/xqtc/nixos-config)

**Comment by xqtc161** [comment]
This seems to go deeper. Might not even be nixvim-related. Closing this.

**Comment by qussaif10** [comment]
I'm having the same issue, how did you figure out what the issue was?
