### ISSUE TITLE
[BUG] angular-language-server not available in x86_64

### ISSUE THREAD

**Issue by DinkyTrady** [nix-community/nixvim#2525]
| Field        | Description |
|--------------|-------------|
| Plugin       | `angularls`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
it does not even care if i set the lsp to disable or set `lsp.angularls.enable = false` its still give the same error
```
… while evaluating the default value of option `plugins.lsp.servers.angularls.cmd`
(stack trace truncated; use '--show-trace' to show the full, detailed trace)
error: angular-language-server cannot be found in pkgs
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
  plugins = {
    lsp.enable = false;
  };
}
```

**Comment by khaneliman** [comment]
How are you providing pkgs to nixvim? Sounds like a mismatch between nixvim version and the pkgs provided.

**Comment by DinkyTrady** [comment]
typo nixpkgs url in flake.nix, now its fixed closed the issue
