### ISSUE TITLE
[PLUGIN REQUEST] gitlab.vim

### ISSUE THREAD

**Issue by bkp5190** [nix-community/nixvim#2565]
| Field    | Description |
|----------|-------------|
| Plugin   | `gitlab.vim`  | 
| Homepage | `https://docs.gitlab.com/ee/editor_extensions/neovim/`     | 
| Nixpkgs  | `false` | 

## Extra Information
gitlab.vim is an extension which makes it easier to configure gitlab pipelines through neovim. It can be configured with code suggestions through the GitLab language server.

**Comment by GaetanLepage** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/358768.

**Comment by bkp5190** [comment]
Thanks @GaetanLepage !
