### ISSUE TITLE
[PLUGIN REQUEST] codecompanion.nvim

### ISSUE THREAD

**Issue by jasper-clarke** [nix-community/nixvim#2569]
| Field    | Description |
|----------|-------------|
| Plugin   | `codecompanion.nvim`  | 
| Homepage | [olimorris/codecompanion.nvim](https://github.com/olimorris/codecompanion.nvim)     | 
| Nixpkgs  | `false` | 

## Extra Information

At minimum this plugin should contains options to enable each of the providers.

**Comment by GaetanLepage** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/358913
