### ISSUE TITLE
[PLUGIN REQUEST] wezterm.nvim

### ISSUE THREAD

**Issue by samos667** [nix-community/nixvim#2596]
| Field    | Description |
|----------|-------------|
| Plugin   | `wezterm.nvim`  | 
| Homepage | [github.com/willothy/wezterm.nvim](https://github.com/willothy/wezterm.nvim)     | 
| Nixpkgs  | `I use github:wez/wezterm?dir=nix input because otherwise wezterm is broken on wayland.` | 

## Extra Information

Allow to interact with wezterm within nvim, provide [various features](https://github.com/willothy/wezterm.nvim/blob/main/doc/wezterm.nvim.txt) nice to have for wezterm users.
[I have tested](https://github.com/samos667/nivis/commit/a3da8881a6132d58b7875d8c34cc177375695459) with pkgs.vimUtils and all seems to work nicely.

By the way I think wezterm should be a possible choice for molten.nvim image provider https://github.com/nix-community/nixvim/blob/80e49e7fd3fa720b93d18e6d859d9b9e7aad4a62/plugins/by-name/molten/default.nix#L78

**Comment by GaetanLepage** [comment]
Would you be interested in giving it a shot ?
We would obviously help you with make it work !

**Comment by samos667** [comment]
Of course I'd love to, I will try it and open a PR !

**Comment by GaetanLepage** [comment]
> Of course I'd love to, I will try it and open a PR !

Great ! Also, feel free to join the [development matrix room](https://matrix.to/#/#nixvim-dev:matrix.org) if you wish :)
