### ISSUE TITLE
[PLUGIN REQUEST] typos-lsp

### ISSUE THREAD

**Issue by ddogfoodd** [nix-community/nixvim#2622]
| Field    | Description |
|----------|-------------|
| Plugin   | `typos-lsp`
| Homepage | `https://github.com/tekumara/typos-lsp`
| Nixpkgs  | `https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/ty/typos-lsp/package.nix`

## Extra Information

Source Code Spellchecker

**Comment by khaneliman** [comment]
This is already available under `plugins.lsp.servers.typos_lsp`  https://nix-community.github.io/nixvim/plugins/lsp/servers/typos_lsp/index.html?highlight=typos#pluginslspserverstypos_lspenable
