### ISSUE TITLE
[BUG] Nixvim doesn't enable catpuccin theme by default with Home manager catppuccin module enabled

### ISSUE THREAD

**Issue by taranarmo** [nix-community/nixvim#2726]
| Field        | Description |
|--------------|-------------|
| Plugin       | `colorschemes.catpuccin`  | 
| Nixpkgs      | `24.11` | 
| Home Manager | `24.11` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

Running nix home manager with `catppuccin.enable = true;` I have catppuccin enabled everywhere except for nixvim (installed via home manager module but probably not limited to this installation method) where I have to explicitly enable the corresponding plugin.
The issue faced on nix-darwin installation and checked on NixOS 24.11

https://nix.catppuccin.com/search/rolling/?option_scope=1&option=catppuccin.enable

## Minimal, Reproducible Example (MRE)

```nix
# home.nix
imports = [
  catppuccin.homeManagerModules.catppuccin
  nixvim.homeManagerModules.nixvim
];

catppuccin.enable = true; # this should enable catppuccin globally in Home manager

programs.nixvim = {
  enable = true;
}
```

**Comment by MattSturgeon** [comment]
Since neither the nixvim or catppuccin modules are part of home-manager, it's not too surprising that they don't know about each other.

I think the most sensible solution would be for the catppuccin module to check if nixvim is present, and if so enable _our_ catppuccin option.

**Comment by khaneliman** [comment]
Yeah, this isn't a bug in nixvim but more of a feature request for catppuccin.

**Comment by taranarmo** [comment]
Okay then, let's consider it closed. I'll file a request to the catppuccin or create a PR if I can handle it.
