### ISSUE TITLE
How to set cmp keyboard shortcuts correctly

### ISSUE THREAD

**Issue by Acisama** [nix-community/nixvim#2762]
I am in the process of migrating my nvim config to nixvim and I love it so far.

But for cmp, the keymaps just don't seem to trigger for some reason.
I want it to start with nothing, tab and shift-tab to navigate between the suggestions and ctrl+space to select a suggestion.

My cmp.nix: 
```
{
  enable = true;
  settings = {
    preselect = "cmp.PreselectMode.None";

    sources = [
      { name = "nvim_lsp"; }
      { name = "path"; }
      { name = "buffer"; }
      { name = "luasnip"; }
    ];

    window = {
      completion.border = "rounded";
      documentation = {
        border = "rounded";
      };
    };

    mappings = {
      "<Tab>" = "cmp.mapping.select_next_item()";
      "<S-Tab>" = "cmp.mapping.select_prev_item()";
      "<C-space>" = "cmp.mapping.confirm({ select = false })";
      "<esc>" = "cmp.mapping.abort()";
    };
  };
}
```

**Comment by traxys** [comment]
You need to use raw values to insert lua, for example `"<Tab>".__raw = "cmp.mapping.<...>"`. See the [documentation](https://nix-community.github.io/nixvim/user-guide/helpers.html) for some more details
