### ISSUE TITLE
[PLUGIN REQUEST] vim-sleuth

### ISSUE THREAD

**Issue by Eviepayne** [nix-community/nixvim#2767]
| Field    | Description |
|----------|-------------|
| Plugin   | `vim-sleuth`  |
| Homepage | `https://github.com/tpope/vim-sleuth`     | 
| Nixpkgs  | `https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/editors/vim/plugins/generated.nix#L17304` |

**Comment by khaneliman** [comment]
Already available as `sleuth` https://nix-community.github.io/nixvim/plugins/sleuth/index.html?highlight=sleuth#sleuth
