### ISSUE TITLE
Question about the dependencies of coq-nvim

### ISSUE THREAD

**Issue by GaetanLepage** [nix-community/nixvim#289]
The [coq-nvim](https://github.com/ms-jpq/coq_nvim) plugin [has been packaged upstream](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=coq_nvim).
However, there, it does not have the [python dependencies as the version packaged in nixvim](https://github.com/pta2002/nixvim/commit/f8b70a30eac4728e35cd15e8d46bb81d6d11c662).

Do we need those python dependencies ? More precisely, which one of the following options is the best ?

1. Those plugins are not mandatory dependencies, it is why they are not part of the upstream `vimPlugins.coq_nvim` package.
We can then remove `coq_nvim` from the packages that we manually package and rely on the upstream package.
2. Those dependencies are necessary and it would make sense to upstream them.
3. In between: it does not really make sense to upstream them, but it is useful to get them for nixvim users.

If option 3, why precisely ?

cc @pta2002 as you packaged this plugin first.

**Comment by GaetanLepage** [comment]
I made a PR upstream: https://github.com/NixOS/nixpkgs/pull/223056

**Comment by pta2002** [comment]
Sorry I could swear I'd replied to this. Thanks for making the PR upstream, it was indeed necessary as otherwise coq would try to download the dependencies by itself and it'd fail as it tried to write to the nix store.

**Comment by GaetanLepage** [comment]
The upstream PR has finally been merged !
https://github.com/NixOS/nixpkgs/pull/223056
Once the updates makes it to `nixos-unstable`, coq_nvim user should have a good experience.

Hence, I am closing this issue.
