### ISSUE TITLE
Can't change leader when using plugin config

### ISSUE THREAD

**Issue by ForsakenHarmony** [nix-community/nixvim#328]
**Plugin affected**: third party
**Nixpkgs channel**: 22.11
**Home-manager version**: 

## Description
trying to change the leader via `globals.mapleader` doesn't work because `extraPlugins.[].config` gets inlined before it

## Config
```nix
programs.nixvim = {
  globals.mapleader = " ";
  
  extraPlugins = with pkgs.vimPlugins; [
    {
      plugin = ctrlp;
      config = ''
        nmap <leader>p :CtrlP<cr>
      '';
    }     
};
```

this will get `\` as the leader instead of ` ` because of the way the plugin config is inlined first
https://github.com/pta2002/nixvim/blob/main/modules/output.nix#L149

**Comment by pta2002** [comment]
This is a matter of putting the globals on the pre-initialization lua code. I can take care of this.

**Comment by pta2002** [comment]
Am now confused! It's already on the pre-initialization code. Can you show the generated `init.lua` with your config @ForsakenHarmony? (Last time I picked up nixvim, `config` on `extraPlugins` was not supported, but it might have been added while I stepped off)

**Comment by pta2002** [comment]
In the meantime, you can try changing your config to this:

```nix
{
  globals.mapleader = " ";
  
  extraPlugins = with pkgs.vimPlugins; [ ctrlp ];
  extraConfigLua = ''
    nmap <leader>p :CtrlP<cr>
  '';
}
```

**Comment by pta2002** [comment]
Yeah I'd say we can remove that. Maybe in the future add proper support for it, but it'd need to differentiate lua and vimscript.

**Comment by ForsakenHarmony** [comment]
@pta2002 it is used for me the generated `init.lua` file looks like this:

```lua
vim.cmd([[
nmap <leader>p :CtrlP<cr>
]])
-- Set up globals {{{
do
  local nixvim_globals = {["localleader"] = ",",["mapleader"] = " "}

  for k,v in pairs(nixvim_globals) do
    vim.g[k] = v
  end
end
```

**Comment by ForsakenHarmony** [comment]
I think it's this
https://github.com/pta2002/nixvim/blob/838f616f0a2bcdd1baaab8f54a6c5d41b270c483/modules/output.nix#L150

maybe that just needs to be moved down

**Comment by traxys** [comment]
You could use a configuration as follows: 

```nix
{
    globals.mapleader = ' ';
    
   /* Ctrl-P configuration */
   maps.normal = {
       "<leader>p" = ":CtrlP<cr>";
   };
}
```

or even

```nix
{
    globals.mapleader = ' ';

   imports = [
     /* Ctrl-P Configuration */
     {
         maps.normal = {
           "<leader>p" = ":CtrlP<cr>";
          };
     }
   ]
}
```

To implement this in a similar way with our current implementation of nixvim. We haven't really thought on how to have different nix expressions for differents plugins, I think we need to look into that but doing it cleanly will not be easy. It's a bit similar to what is talked https://github.com/pta2002/nixvim/issues/49#issuecomment-1280544771 here, but with entire plugin configurations instead of filetypes

**Comment by GaetanLepage** [comment]
From my understanding, this issue is now solved.
Do not hesitate to re-open if you have further concern.
