### ISSUE TITLE
error: attribute 'vscode-langservers-extracted' missing

### ISSUE THREAD

**Issue by deeengan** [nix-community/nixvim#438]
**Nixpkgs channel**: 23.05
**Home-manager version**: 23.05

## Description

Hi,

I recently updated my flake.

After updating, I attempted to rebuild. However, I cannot. If I comment out  nixvim.homeManagerModules.nixvim and take out my neovim config, then my flake does, indeed, rebuild. 

``
error:
       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:776:24:

          775|     let f = attrPath:
          776|       zipAttrsWith (n: values:
             |                        ^
          777|         let here = attrPath ++ [n]; in

       … while calling 'g'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:248:72:

          247|           # For definitions that have an associated option
          248|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          249|

       … while evaluating the option `system.build.toplevel':

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:774:28:

          773|         # Process mkMerge and mkIf properties.
          774|         defs' = concatMap (m:
             |                            ^
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/nixos/modules/system/activation/top-level.nix':

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:775:137:

          774|         defs' = concatMap (m:
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          776|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:846:25:

          845|   */
          846|   dischargeProperties = def:
             |                         ^
          847|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/nixos/modules/system/activation/top-level.nix:131:12:

          130|   # Replace runtime dependencies
          131|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
          132|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while calling 'foldr'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while calling 'fold''

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … while calling 'g'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:248:72:

          247|           # For definitions that have an associated option
          248|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          249|

       … while evaluating the option `assertions':

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:774:28:

          773|         # Process mkMerge and mkIf properties.
          774|         defs' = concatMap (m:
             |                            ^
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/yg4829d6gqd2ipc1vjnr2nxh3aapmmqw-source/nixos/common.nix':

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:775:137:

          774|         defs' = concatMap (m:
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          776|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:846:25:

          845|   */
          846|   dischargeProperties = def:
             |                         ^
          847|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:852:11:

          851|         if def.condition then
          852|           dischargeProperties def.content
             |           ^
          853|         else

       … while calling 'dischargeProperties'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:846:25:

          845|   */
          846|   dischargeProperties = def:
             |                         ^
          847|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/yg4829d6gqd2ipc1vjnr2nxh3aapmmqw-source/nixos/common.nix:103:18:

          102|
          103|     assertions = flatten (flip mapAttrsToList cfg.users (user: config:
             |                  ^
          104|       flip map config.assertions (assertion: {

       … while calling 'flatten'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:138:13:

          137|   */
          138|   flatten = x:
             |             ^
          139|     if isList x

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:140:21:

          139|     if isList x
          140|     then concatMap (y: flatten y) x
             |                     ^
          141|     else [x];

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:140:24:

          139|     if isList x
          140|     then concatMap (y: flatten y) x
             |                        ^
          141|     else [x];

       … while calling 'flatten'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/lists.nix:138:13:

          137|   */
          138|   flatten = x:
             |             ^
          139|     if isList x

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:10:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          540|

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:16:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          540|

       … while calling anonymous lambda

         at /nix/store/yg4829d6gqd2ipc1vjnr2nxh3aapmmqw-source/nixos/common.nix:103:64:

          102|
          103|     assertions = flatten (flip mapAttrsToList cfg.users (user: config:
             |                                                                ^
          104|       flip map config.assertions (assertion: {

       … from call site

         at /nix/store/yg4829d6gqd2ipc1vjnr2nxh3aapmmqw-source/nixos/common.nix:104:7:

          103|     assertions = flatten (flip mapAttrsToList cfg.users (user: config:
          104|       flip map config.assertions (assertion: {
             |       ^
          105|         inherit (assertion) assertion;

       … while calling 'flip'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/trivial.nix:138:16:

          137|   */
          138|   flip = f: a: b: f b a;
             |                ^
          139|

       … while calling 'g'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:248:72:

          247|           # For definitions that have an associated option
          248|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          249|

       … while evaluating the option `home-manager.users.deeengan.assertions':

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:774:28:

          773|         # Process mkMerge and mkIf properties.
          774|         defs' = concatMap (m:
             |                            ^
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/flake.nix':

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:775:137:

          774|         defs' = concatMap (m:
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          776|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:846:25:

          845|   */
          846|   dischargeProperties = def:
             |                         ^
          847|     if def._type or "" == "merge" then

       … while calling 'g'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:248:72:

          247|           # For definitions that have an associated option
          248|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          249|

       … while evaluating the option `home-manager.users.deeengan.programs.nixvim':

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:796:59:

          795|       if isDefined then
          796|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          797|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while calling 'merge'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/types.nix:751:22:

          750|         check = x: isAttrs x || isFunction x || path.check x;
          751|         merge = loc: defs:
             |                      ^
          752|           (base.extendModules {

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:10:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          540|

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:16:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          540|

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:678:46:

          677|         else
          678|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          679|             map (def: def // {

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:664:22:

          663|         # Propagate all unmatched definitions from nested option sets
          664|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          665|         # Plus the definitions for the current prefix that don't have a matching option

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:10:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          540|

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:16:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          540|

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:678:46:

          677|         else
          678|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          679|             map (def: def // {

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:664:22:

          663|         # Propagate all unmatched definitions from nested option sets
          664|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          665|         # Plus the definitions for the current prefix that don't have a matching option

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:10:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          540|

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:16:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          540|

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:678:46:

          677|         else
          678|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          679|             map (def: def // {

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:664:22:

          663|         # Propagate all unmatched definitions from nested option sets
          664|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          665|         # Plus the definitions for the current prefix that don't have a matching option

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:10:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          540|

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/attrsets.nix:539:16:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          540|

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:678:46:

          677|         else
          678|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          679|             map (def: def // {

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:664:22:

          663|         # Propagate all unmatched definitions from nested option sets
          664|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          665|         # Plus the definitions for the current prefix that don't have a matching option

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:618:39:

          617|
          618|       resultsByName = mapAttrs (name: decls:
             |                                       ^
          619|         # We're descending into attribute ‘name’.

       … while calling anonymous lambda

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:624:33:

          623|           defns' = defnsByName'.${name} or [];
          624|           optionDecls = filter (m: isOption m.options) decls;
             |                                 ^
          625|         in

       … from call site

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/modules.nix:624:36:

          623|           defns' = defnsByName'.${name} or [];
          624|           optionDecls = filter (m: isOption m.options) decls;
             |                                    ^
          625|         in

       … while calling 'isType'

         at /nix/store/7chim95y65lpps6j547gyy06wm5r2lbj-source/lib/types.nix:70:18:

           69| rec {
           70|   isType = type: x: (x._type or "") == type;
             |                  ^
           71|

       error: attribute 'vscode-langservers-extracted' missing

       at /nix/store/9gci9x3krb2aryz7nlr0a6pvzga9sz4y-source/plugins/lsp/language-servers/default.nix:40:17:

           39|       description = "Enable cssls, for CSS";
           40|       package = pkgs.vscode-langservers-extracted;
             |                 ^
           41|       cmd = cfg: ["${cfg.package}/bin/vscode-css-language-server" "--stdio"];

``
## Config

                            home-manager.nixosModules.home-manager
                              {
                                home-manager.useGlobalPkgs = true;
                                home-manager.useUserPackages = true;
                                home-manager.users.user = { imports = [ nixvim.homeManagerModules.nixvim ./home.nix ]; };

        }

**Comment by GaetanLepage** [comment]
Hello,
What channel of `nixpkgs` are you running ?
There has been an update recently where `pkgs.nodePackages.vscode-langservers-extracted` has been renamed to `vscode-langservers-extracted`.
We updated `nixvim` to reflect that change.
If you are running an unstable channel, you should not have any problem.

However, if you are on `nixos-23.05`, then you need to stay on the `nixos-23.05` banch of nixvim.

**Comment by GaetanLepage** [comment]
> I do get an error below.

Indeed, the `auto-save` plugin has been packaged after the 'branch-off'.
Hence, either you stay on 23.05 and limit yourself to the packages available on this branch, or you switch to the nixvim `main` branch and, in this case, you have to change your flake `nixpkgs` input from `nixos-23.05` to `nixos-unstable`.

There is not really another alternative...
