### ISSUE TITLE
plugins​.nvim-cmp​.sources does not accept list of lists as advertised

### ISSUE THREAD

**Issue by NickHu** [nix-community/nixvim#494]
**Plugin affected**: nvim-cmp
**Nixpkgs channel**: unstable

## Description
To quote the documentation:

> The sources to use​. Can either be a list of sourceConfigs which will be made directly to a Lua object​. **Or it can be a list of lists, which will use the cmp built-in helper function cmp​.config​.sources​.**

But if you put in a list of lists, it doesn't build.
Error:
```
error:
       … while evaluating a branch condition

         at /nix/store/1blbi96nzwjqx90i7i9ahrx82ys6gzal-source/wrappers/standalone.nix:21:5:

           20|   in
           21|     if failedAssertions != []
             |     ^
           22|     then throw "\nFailed assertions:\n${builtins.concatStringsSep "\n" (map (x: "- ${x}") failedAssertions)}"

       … while calling the 'map' builtin

         at /nix/store/1blbi96nzwjqx90i7i9ahrx82ys6gzal-source/wrappers/standalone.nix:19:24:

           18|   handleAssertions = config: let
           19|     failedAssertions = map (x: x.message) (lib.filter (x: !x.assertion) config.assertions);
             |                        ^
           20|   in

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: A definition for option `plugins.nvim-cmp.sources."[definition 1-entry 1]"' is not of type `submodule'. Definition values:
       - In `<unknown-file>':
           [
             {
               name = "nvim_lsp";
             }
           ]

```

 Indeed the code doesn't seem to check for this case at all:
https://github.com/nix-community/nixvim/blob/4c25722d73694245e767839b462026ab2296542b/plugins/completion/nvim-cmp/default.nix#L587-L606

## Config
```nix
{ pkgs, ... }:
{
  config = {
    plugins = {
      nvim-cmp = {
        enable = true;
        sources = [
          [
            { name = "nvim_lsp"; }
          ]
        ];
      };
    };
  };
}
```

**Comment by GaetanLepage** [comment]
You are right, our option would let the user provide a list of list but then the implementation was only flattening everything.
In https://github.com/nix-community/nixvim/pull/525, I cleaned the `nvim-cmp` code and now, only a list of sources can be provided.

**Comment by GaetanLepage** [comment]
I will mark this issue as closed since this anomaly is no more.
@NickHu did you have a specific need for the "list of lists" method of providing sources to`nvim-cmp` ?

**Comment by NickHu** [comment]
Yes, it's necessary because it's the only way to define completion groups in cmp

**Comment by GaetanLepage** [comment]
Oh all right. I will then have a look at fixing it properly.
