### ISSUE TITLE
Module not found from init.lua

### ISSUE THREAD

**Issue by alesauce** [nix-community/nixvim#502]
**Plugin affected**: What plugin does this bug relate to (if applicable): `catpuccin` (although this is just because it's the first line in the file)
**Nixpkgs channel**: unstable
**Home-manager version**: N/A - Darwin Module

## Description
After building my nix-darwin setup on a [secondary computer](https://github.com/alesauce/nix-home/blob/main/flake.nix#L55), attempting to use Neovim results in the following error:
```
Error detected while processing /Users/alesauce/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/alesauce/.config/nvim/init.lua:21: module 'catppuccin' not found:
        no field package.preload['catppuccin']
        no file '/nix/store/4fjb4rg5gjk3zs0hpkvavq0qphvybjd0-luajit-2.1.0-2022-10-04-env/share/lua/5.1/catppuccin.lua'
        no file '/nix/store/4fjb4rg5gjk3zs0hpkvavq0qphvybjd0-luajit-2.1.0-2022-10-04-env/share/lua/5.1/catppuccin/init.lua'
        no file '/nix/store/4fjb4rg5gjk3zs0hpkvavq0qphvybjd0-luajit-2.1.0-2022-10-04-env/lib/lua/5.1/catppuccin.so'
stack traceback:
        [C]: in function 'require'
        /Users/alesauce/.config/nvim/init.lua:21: in main chunk
```

This computer previously had a Neovim configuration through my own Lua files managed via home-manager before I migrated to nix-darwin. My [other computer](https://github.com/alesauce/nix-home/blob/main/flake.nix#L38) has not encountered the same error.

Troubleshooting steps I've tried:
1. `nix store gc`
2. Rebuilding the nix-darwin flake, several times
3. Restarting computer
4. Deleting other system files for Neovim
5. Reviewing issues to see if anyone has encountered this before
6. Deleting `~/.local/share/nvim` and `~/.local/state/nvim`

## Config
My default flake in codeblock below. [Directory with all of my nixvim config files](https://github.com/alesauce/nix-home/tree/main/home-manager/neovim)

```nix
{ pkgs, ... }:

{
  imports = [
    ./base-opts.nix
    ./base-plugins.nix
    ./colorscheme.nix
    ./lsp.nix
    ./telescope.nix
    ./treesitter.nix
  ];

  programs.nixvim = {
    enable = true;
    viAlias = true;
    vimAlias = true;

    globals.mapleader = "<Space>";
    # TODO: Figure out how the append function works for a table and how I can set a table with specific characters added
    extraConfigLua = ''
      vim.opt.listchars:append "eol:↴"
    '';
  };

    # TODO: move this over to completions module
    # Completions
    # completeopt = "menuone,noselect";

    # TODO: move these over to completions module
    # Completions (cmp)
    # nvim-cmp.enable = true;
    # cmp-buffer.enable = true;
    # cmp-cmdline.enable = true;
    # cmp_luasnip.enable = true;
    # cmp-path.enable = true;
    # cmp-nvim-lsp.enable = true;
    # cmp-nvim-lua.enable = true;
    # luasnip.enable = true;

    # TODO: create treesitter module
    # treesitter.enable = true;
}
```

**Comment by alesauce** [comment]
The issue was on my end! Since my computer had a previous `home-manager` installation, it had an entry in $PATH for the `.nix-profile` that was previously created by the home-manager. Deleting that entry from my path resolved the issue.

Thank you for this wonderful tool!

**Comment by GaetanLepage** [comment]
Oh ok !
Glad that you have sorted it out :)

**Comment by nbfritch** [comment]
I had this problem because I had previously uninstalled neovim with `nix-env -iA neovim`.
I was able to resolve by running `nix-env --uninstall neovim`
