### ISSUE TITLE
neovim not loading generated config file

### ISSUE THREAD

**Issue by robsmith11** [nix-community/nixvim#508]
I'm new to NixOS, so perhaps I'm doing something obviously wrong, but I tried to follow the instructions for using nixvim as a module for the 23.05 channel without a home manager or flakes

nixvim.nix:
```
{ pkgs, lib, ... }:
let
  nixvim = import (builtins.fetchGit {
    url = "https://github.com/nix-community/nixvim";
    ref = "nixos-23.05";
  });
in
{
  imports = [
    # For NixOS
    nixvim.nixosModules.nixvim
  ];

  programs.nixvim = {
    enable = true;
    colorschemes.gruvbox.enable = true;
    plugins.lsp.enable = true;
    plugins.lsp.servers.pyright.enable = true;
  };
}
```

After rebuilding, it's clear that neovim is not using the generated config file, but if I run `nvim -u /etc/nvim/sysinit.lua`, everything works as expected.

I don't have anything nvim related in my home directory, so I'm not sure why it's not working without explicitly passing the config file.

**Comment by GaetanLepage** [comment]
Should be fixed by #515.
We will be backporting this change to the `nixos-23.05` branch.
I am closing the issue now. Feel free to re-open if needed :)
