### ISSUE TITLE
How to specify an overlay for nixpkgs

### ISSUE THREAD

**Issue by gaelreyrol** [nix-community/nixvim#528]
Hi!

I am using multiple overlays over the standard `pkgs` attribute to access `unstable` & `master` channels:
```nix
nixpkgs.overlays = [
  (final: prev: {
    unstable = builtins.import inputs.unstable {
      inherit (final) config;
      inherit system;
    };
  })
  (final: prev: {
    master = builtins.import inputs.master {
      inherit (final) config;
      inherit system;
    };
  })
]
```
As I am using the `master` branch of `nixvim`, it expects `pkgs` to be the `unstable` channel. Mine targets `nixos-23.05`, I would like to know if there was a way to pass to `nixvim.nixosModules.nixvim` a specific `pkgs` attribute. For example:
```nix
modules = [
  nixvim.nixosModules.nixvim
  {
    nixvim.pkgs = pkgs.unstable;
  }
];
```
Thanks for your time!

**Comment by gaelreyrol** [comment]
Oops I realized there was a discussion page, sorry for the noise...

**Comment by elohmeier** [comment]
https://github.com/nix-community/nixvim/discussions/529
