### ISSUE TITLE
FlakeHub Support?

### ISSUE THREAD

**Issue by siph** [nix-community/nixvim#538]
It looks like Determinate Systems launched a new project [FlakeHub](https://determinate.systems/posts/introducing-flakehub). It seems like it could eventually alleviate a lot of the confusion around which branch to use in conjunction with `nixpkgs`. I just wanted to start a discussion to see what other people thought.

**Comment by traxys** [comment]
It depends a bit on how nixvim is used, we tought in the past of pinning a known good nixpkgs version, but it's not really in the spirit of either nixos modules or home-manager modules to require that, so I'm not sure even with FlakeHub we could alleviate those issues. Tough we could maybe help in the for the standalone case

**Comment by siph** [comment]
It could also be beneficial for the discoverability of `nixvim`, depending on how adoption goes.

**Comment by pta2002** [comment]
I don't have any real problem with _publishing_ nixvim over there, but it seems more oriented towards libraries - things like `flake-utils`. Nixvim does not really have versions, it's just a rolling release kind of thing, so I'm not really sure how we'd fit into the FlakeHub model.

**Comment by GaetanLepage** [comment]
I agree with your observation @pta2002.
Nothing against being referenced there, but not sure about other benefits.
I have not yet fully grasp the span of Flakehub.

**Comment by GaetanLepage** [comment]
This flake has be published on flakehub: https://flakehub.com/flake/nix-community/nixvim
