### ISSUE TITLE
`treesitter-rainbow` breaks `:TSModuleInfo`

### ISSUE THREAD

**Issue by siph** [nix-community/nixvim#546]
**Plugin affected**: `treesitter-rainbow`
**Nixpkgs channel**: `nixos-unstable`

## Description
Enabling `plugins.treesitter-rainbow` breaks `:TSModuleInfo`.
```
E5108: Error executing lua ...ed-0.9.1/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 338 for
 language cpp
stack traceback:
        [C]: in function '_ts_parse_query'
        ...ed-0.9.1/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
        ...imPackages/start/nvim-ts-rainbow2/lua/ts-rainbow/lib.lua:70: in function 'get_query'
        ...ackages/start/nvim-ts-rainbow2/lua/ts-rainbow/module.lua:30: in function 'is_supported'
        ...es/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:387: in function 'is_enabled'
        ...kages/start/nvim-treesitter/lua/nvim-treesitter/info.lua:91: in function 'append_module_table'
        ...kages/start/nvim-treesitter/lua/nvim-treesitter/info.lua:125: in function 'print_info_modules'
        ...kages/start/nvim-treesitter/lua/nvim-treesitter/info.lua:159: in function 'run'
        [string ":lua"]:1: in main chunk

```

## Config
Standalone:
```nix
{
  plugins = {
    treesitter.enable = true;
    treesitter-rainbow.enable = true;
  };
}

```

**Comment by GaetanLepage** [comment]
Hello !

Thank you for reporting this issue. I am also able to reproduce it.
It does not seem to be a nixvim problem but rather an upstream/plugin one.
The underlying `treesitter-rainbow` plugin that we are using is [nvim-ts-rainbow2](https://gitlab.com/HiPhish/nvim-ts-rainbow2) which has been deprecated.
Indeed, from their README:
> This plugin is implemented as a module for
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), but nvim-treesitter has deprecated the module feature.

So I guess that we will deprecate this plugin in nixvim and add the suggested [rainbow-delimiters.nvim](https://gitlab.com/HiPhish/rainbow-delimiters.nvim) separately.

**Comment by GaetanLepage** [comment]
After switching to `rainbow-delimiters` it should work again :)
Feel free to re-open if it is not the case.
