### ISSUE TITLE
`treesitter-playground` is deprecated.

### ISSUE THREAD

**Issue by siph** [nix-community/nixvim#565]
https://github.com/nvim-treesitter/playground

From readme:  

This plugin is **deprecated** since the functionality is included in Neovim: Use

- `:Inspect` to show the highlight groups under the cursor
- `:InspectTree` to show the parsed syntax tree ("TSPlayground")
- `:PreviewQuery` to open the Query Editor (Nvim 0.10+)

**Comment by GaetanLepage** [comment]
Thank you for noticing !
The plugin has been marked as deprecated :)
