### ISSUE TITLE
Error when launching as "vim". Works fine if launched as "nvim"

### ISSUE THREAD

**Issue by haizaar** [nix-community/nixvim#567]
Most likely the problem is somewhere on my end but I'll give it a shot.
I'm using nixvim as a home-manage module.

After enabling it, when I start neovim as `vim` it throws lua error; otherwise, when start it as `nvim` it works just fine.

Here is the error:
```
Error detected while processing /home/foo/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_editor.lua:0: /home/foo/.config/nvim/init.lua..nvim_exec2() called at /home/foo/.config/
nvim/init.lua:0: Vim(colorscheme):E185: Cannot find color scheme 'gruvbox'
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/foo/.config/nvim/init.lua:17: in main chunk
```

Here is my (generated) `init.lua`:
```lua
vim.cmd([[
  


]])
-- Set up globals {{{
do
  local nixvim_globals = {["gruvbox_bold"] = 0}

  for k,v in pairs(nixvim_globals) do
    vim.g[k] = v
  end
end
-- }}}

vim.loader.disable()
vim.cmd([[
  colorscheme gruvbox

]])
```

And here is my relevant nix HM config snippet:

```nix
{ config, pkgs, ... }:

let
  nixvim = import (builtins.fetchGit {
    url = "https://github.com/nix-community/nixvim";   
    # If you are not running an unstable channel of nixpkgs, select the corresponding branch of nixvim.
    ref = "nixos-23.05";
  });
in
{
        
  imports = [
    <home-manager/nixos>
  ];
        
  home-manager.useUserPackages = true;
  home-manager.useGlobalPkgs = true;
        
  home-manager.users.foo = { config, pkgs, ... }: {
        
    imports = [
      nixvim.homeManagerModules.nixvim
    ];
        
    programs.nixvim = {
      enable = true;

      plugins."markdown-preview".enable = true;
      colorschemes.gruvbox.enable = true;
    };
}
```

My neovim is installed globally through the system module:
```nix
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    vimAlias = true;
    viAlias = true;  
  };
```

I'm on NixOS 23.05 with respective home manager channel and nixvim branch.

Is there something obvious that I'm missing?

**Comment by traxys** [comment]
You must not install neovim globally when using nixvim, nixvim takes care of the installation. I think what is happening is that nixvim does not create the `vimAlias` and as such `vim` points to the globally installed neovim, and `nvim` to the `nixvim` installation (that don't have the same plugins)

**Comment by traxys** [comment]
You should be able to use `vimAlias` and `viAlias` in `programs.nixvim`. Not sure about `defaultEditor`, I set manually the `EDITOR` environnement variable

**Comment by haizaar** [comment]
Yeap, using `vi(m)Alias` did the trick! Now both it works fine regardless of how it's invoked. Thank you for the quick reply!

Here is the minimal config for others that come here:
```nix
    programs.nixvim = {
      enable = true;
      vimAlias = true;
      viAlias = true; 
    
      plugins.markdown-preview.enable = true;  
      colorschemes.gruvbox.enable = true;
    };
```

P.S. I do want (n)vim available globally to be used by `root`, etc.

**Comment by siph** [comment]
If you want `nvim` for root I think you need to use the `Nixos` modules instead of `home-manager`, which is only for user level.

**Comment by haizaar** [comment]
I have a couple of users on my machine (on top of root), so I don't want to force one config for everybody. Hence having a system nvim with default (empty) config and leaving per-user configs to respective HMs is what I'm working on - so far works OK.
Are you saying there is a caveat in this setup?

**Comment by traxys** [comment]
I don't think so
