### ISSUE TITLE
plugins.lsp.nixd: implicit dependency on nixpkgs-fmt for formatting

### ISSUE THREAD

**Issue by jhvst** [nix-community/nixvim#573]
**Plugin affected**: `plugins.lsp.nixd`
**Nixpkgs channel**: unstable
**Home-manager version**: unstable

## Description
When LSP formatting is enabled, and so is `nixd`, formatting does not work unless `nixpkgs-fmt` is added as extraPackage. Looking at the [nixd source code](https://github.com/search?q=repo%3Anix-community%2Fnixd%20nixpkgs-fmt&type=code) it has an implicit dependency on `nixpkgs-fmt`.

`nixpkgs-fmt` should be added as an additional package to install if `nixd` is enabled, and formatting is set as default or as `nixpkgs-fmt`.

## Config
N/A

**Comment by GaetanLepage** [comment]
After having taken a look, it seems that `nixpkgs-fmt` is not really a _dependency_ of `nixd`.
`nixd` can run `nixpkgs-fmt`.
As such, it does not really make sense to systematically add it as a dependency.
If the user needs it, he should indeed add it to `extraPackages`.

**Comment by jhvst** [comment]
Fair enough. Could you comment on LSPs that do the same? Like bash-ls integrates with `shellcheck`, it is not a required dependency, but one could assume that if the user wants to enable bash-ls, they most likely also want `shellcheck` to be enabled as well. I wonder what is your stance in these cases?

**Comment by GaetanLepage** [comment]
After a second thought, I have proposed #577 which will automatically add the dependency if you enable formatting in the `nixd` settings (see PR for more details).
I think that this is a nice middle-ground.
