### ISSUE TITLE
Crash build on adding home-manager module

### ISSUE THREAD

**Issue by Sironheart** [nix-community/nixvim#574]
**Plugin affected**: -
**Nixpkgs channel**: 23.11
**Home-manager version**: 23.11

## Description
On running `darwin-rebuild switch --flake .` the following error output is produced.
![image](https://github.com/nix-community/nixvim/assets/13799656/c1b81ece-adbd-4222-b371-0c6c4a2bbfa6)
I might be doing something wrong (please tell me if so), but as soon as I remove the comment from my [flake.nix (line 124)](https://github.com/Sironheart/nix-config/blob/main/flake.nix#L124) I get the error in the screenshot. 

Would be great if I can switch to nixvim :) 

## Config
[Link to file in repo](https://github.com/Sironheart/nix-config/blob/main/home/programs/nixvim/default.nix)

**Comment by GaetanLepage** [comment]
Hello !
Indeed, you should import the `nixvim.homeManagerModules.nixvim` in the home-manager configuration, not in the NixOS one.
Currently, you are importing it in NixOS [at this line](https://github.com/Sironheart/nix-config/blob/66faaf80f3051cdfb05af6ce9c2b549de02ebe44/flake.nix#L124).
What you should do is something like this: https://github.com/GaetanLepage/dotfiles/blob/90614775dbbab4fe6c8a8f127b79c0eb24896d5d/flake.nix#L76-L79.
You may add it to `home-manager.users.USERNAME.imports`.

I hope this was clear :)

**Comment by Sironheart** [comment]
Thank you very much, this was indeed the problem! That helps a lot and I learned yet another thing :)
This can be handled as done :D

**Comment by pagusupu** [comment]
Sorry to open this back up but I was stuck on the exact same thing, but after adding ``nixvim.homeManagerModules.nixvim`` to  ``home-manager.users.USERNAME.imports`` I get 


![image](https://github.com/nix-community/nixvim/assets/114620038/04ae3b67-113e-4453-8cbb-908fa24d4395)


I'm probably just missing something obvious but I couldn't quite figure it out, thought I'd appreciate any help :) 
Links to my [flake](https://github.com/pagusupu/nixos/blob/main/flake.nix), [home-manager](https://github.com/pagusupu/nixos/blob/main/hosts/home/user.nix#L25C16-L25C16) and full [config](https://github.com/pagusupu/nixos)
> home-manager (user.nix) is imported to default.nix then flake.nix

**Comment by GaetanLepage** [comment]
Indeed, in this `user.nix` file, the variable `nixvim` is undefined.
You should replace `nixvim.homeManagerModules.nixvim` with `inputs.nixvim.homeManagerModules.nixvim`.
(`inputs` has been properly put in the arguments at the top of the file.
