### ISSUE TITLE
desc attribute in action.key for todo-comments

### ISSUE THREAD

**Issue by b-m-f** [nix-community/nixvim#598]
Would it be possible to supply an attribute set like `{ key = "key; desc = "Show all TODOs in telescope overlayer"` in the  [todo-comments keymap](https://github.com/nix-community/nixvim/blob/ada99e57635b9ec60fab30d361927820fa0f890d/plugins/utils/todo-comments.nix#L196)?

Or matybe add a new parameter `desc` to make the keymapping compatible with **which-key**?

I'm not sure if such a cross-plugin features are something that should be introduced or considered in **nixvim** or if this is something that should go into the custom keymap of every user.

**Comment by traxys** [comment]
I think this is already implemented in the keymaps options, but not shown in the documentation

**Comment by b-m-f** [comment]
Does it maybe need yo be inherited at https://github.com/nix-community/nixvim/blob/ada99e57635b9ec60fab30d361927820fa0f890d/plugins/utils/todo-comments.nix#L277?

@traxys do you have an example that I could try?

**Comment by traxys** [comment]
Yes for the keymaps defined in plugins there may be problems if we don't define them permissive enough, you can't do it with todo-comments as is.

Though that's a bug we need to fix.

**Comment by traxys** [comment]
With the linked PR it should be possible to pass options, and they should appear in the documentation!
