### ISSUE TITLE
Random Breakage with overlay of nixvim

### ISSUE THREAD

**Issue by lecoqjacob** [nix-community/nixvim#606]
**Plugin affected**: What plugin does this bug relate to (if applicable)
**Nixpkgs channel**: unstable
**Home-manager version**: N/A

## Description
Adding an overlay with nixvim causes an error saying `attribute 'i686-linux' missing`
![Screenshot_2023-09-26-23-00-12_](https://github.com/nix-community/nixvim/assets/9278174/6439075e-9753-4a95-9d9d-8ea6e07d63d7)

## Config
Your nixvim config

**Comment by GaetanLepage** [comment]
Can you please share the code that leads to this bug ?
I have personally never tried adding an overlay.

**Comment by GaetanLepage** [comment]
@lecoqjacob sorry to bother you again, but I would like to replicate this bug so that I can fix it.
Could you provide me with a configuration snippet that triggers this behavior please ?

**Comment by lecoqjacob** [comment]
> @lecoqjacob sorry to bother you again, but I would like to replicate this bug so that I can fix it.
> 
> Could you provide me with a configuration snippet that triggers this behavior please ?

Sorry for never getting back to you. I believe this was happening from a really outdated dep deep in the dependency list. I was using snowfall-lib, but when I forked and updated the deps, it stopped throwing errors. I don't think it's an issue in your end, but I will definitely report back if I do find that it is still occuring.

**Comment by GaetanLepage** [comment]
Ok perfect ! Thanks for your response :)
Closing then
