### ISSUE TITLE
[Feature Request] Complete programming language support

### ISSUE THREAD

**Issue by zoedsoupe** [nix-community/nixvim#635]
Hello! Nice project here! I always build my neovim config with nix and then with flakes and it awesome to see the cimmunity building a “complete” flake with many possibilities for who would like to just set neovim up declaratively.

I would like to start my contributions to this project adding plugins and color schemes but I also would like to know if there’s any plan to implement programming languages support in a declarative way, like an abstraction around `plugins` opts.

I would work like that:
```nix
{
  programs.nixvim = {
    languages.elixir {
      enable = true;
      lsp = {
        enable = true;
        name = “nexts”; # or elixir-ls
        package = next-ls;
      };
      # other configs
    };
    languages.rust.enable = true; # use default options
  };
}
```

WDYT about this possible feature? I would like to tackle this if there’s chance to evolve in discussion 😊

**Comment by zoedsoupe** [comment]
Ok, if that feature is against the flake philosofy, no problem with that! But I think that is different from being a neovim distribution. My point is: on neovim distributions there are configs pre-defined with a style pre-defined too, for example for buffer line/tree view and other UI plugins.
Adding support to a language is different as this project aims to give total control to the user to set up the config. So keymaps would be defined by the user. THis possible feature aims only to be a wrapper into plugins,as if I need to support elixir language one would do:
```
{
  programs.nixvim = {
    plugins = {
      elixir-ls.enable = true;
      elixir-tools.enable = true;
      treesitter = {
        enable = true;
        ensureInstalled = [“elixir”];
      };
    };
  };
}
```

Abstraction doesn’t mean miss config control, but I understand that may be outside from the project scope. Thanks for the response!

**Comment by zoedsoupe** [comment]
That’s a really good point of view! Indeed this feature would demand a kinda complex implementation as it should handle different options for some packages. So for elixir for example, there’s the `elixir-ls` and the `next-ls` LSPs clients. So the desired API to declare this would be:
```nix
{
  programs.nixvim = {
    languages.elixir = {
      enable = true; # basic setup as tressiter grammar for example
      elixir-tools.enable = true; # specific plugin to handle other configs, as LSP
      linting.null-ls.enable = true; # enables Credo for static analysis, for example
      lsp = {
        enable = true;
        client = {
          name = “next-ls”; # can defaults to one or be a required option
          package = next-ls-derivation;
        };
      };
    };
  };
}
```

and for javascript (i don’t know much about the ecosystem too):
```nix
{
  programs.nixvim = {
    languages.javascript = {
      enable = true; # basic setup as tressiter grammar for example
      linting = {
        prettier.enable = true;
        # other linting options
      };
      lsp = {
        enable = true;
        client = {
          name = “javascript-typescript-langserver”;
          package = pkgs.javascript-lsp; # example name
        };
      };
    };
  };
}
```

Yeah, I agree it seems an extensible and complex feature but could be a valuable one! So if is decided to not go on, I’ll close this issue 😊

**Comment by traxys** [comment]
With this discussion I'm pretty convinced it's not the role of `nixvim` itself, but more of an opinionated wrapper around of nixvim for it to have a nice added value.
From experience it's definitively though enough to follow the plugin options, it would be even harder to follow the ecosystem changes.

Though if a project builds upon nixvim to provide a more "batteries-included" approach we would include it gladly in the README!
