### ISSUE TITLE
Plugin Request - persistence.nvim

### ISSUE THREAD

**Issue by pupbrained** [nix-community/nixvim#643]
**Plugin**: persistence.nvim
**Plugin repository**: [folke/persistence.nvim](https://github.com/folke/persistence.nvim)
**Is the plugin on nixpkgs**: Yes

## Extra information
N/A

**Comment by pupbrained** [comment]
[persistence.nvim 2.0.0](https://github.com/folke/persistence.nvim/releases/tag/v2.0.0) was just released which has a breaking change - nixpkgs seems to still be out of date compared to the plugin itself.

**Comment by traxys** [comment]
It does not seem like the breaking change affect the configuration, and nixvim only handle those kinds of breaking changes
