### ISSUE TITLE
mkdnflow.nvim is broken on nvim v0.9.4

### ISSUE THREAD

**Issue by willswats** [nix-community/nixvim#652]
**Plugin affected**: mkdnflow.nvim
**Nixpkgs channel**: unstable
**Home-manager version**: (if applicable)

## Description
mkdnflow.nvim is broken on nvim v0.9.4 due to [API changes](https://github.com/neovim/neovim/pull/25523). It needs to be updated to this [commit](https://github.com/jakewvincent/mkdnflow.nvim/commit/f7e513a521f5926df034cf40ddd54b43ba73a013).

## Config
N/A

**Comment by GaetanLepage** [comment]
Yes, I know about that. Plugins have not been updated upstream for a while.
I have a [PR](https://github.com/NixOS/nixpkgs/pull/261262) opened for that. I hope that it will get merged soon.

We cannot really do anything at the nixvim level.

**Comment by teto** [comment]
I am not saying you should do it but nixvim could expose a vim plugin overlay.

**Comment by willswats** [comment]
Closing as it's fixed, thanks!
