### ISSUE TITLE
update example.nix "leader"

### ISSUE THREAD

**Issue by evccyr** [nix-community/nixvim#659]
The leader attribute from the example doesn't exist:
https://github.com/nix-community/nixvim/blob/3c4ac5ba0db665ea895f4c4babaf06d98130e9f6/example.nix#L28

Perhaps this is the only possible way to set the leader key using nixvim:
https://github.com/nix-community/nixvim#globals

**Comment by GaetanLepage** [comment]
Nice catch !
Fixed in #662 
Thanks :)
