### ISSUE TITLE
`nvim-cmp` and `cmp-nvim-lsp` with `rust-analyzer`should ensure that `rustc` is available. 

### ISSUE THREAD

**Issue by jdbosser** [nix-community/nixvim#674]
**Plugin affected**: nvim-cmp, cmp-nvim-lsp, lsp, rust-analyzer
**Nixpkgs channel**: unstable
**Home-manager version**: NA

## Description
When trying to get completions to work from rust-analyzer, cmp-nvim-lsp and nvim-cmp, it is unable to fetch completions if `rustc` is not installed. 

If one looks at the `:LspLog`, you see that
```
[ERROR][2023-10-27 17:32:53] .../vim/lsp/rpc.lua:734	"rpc"	"/nix/store/yflcwnhmws4ain0kzf1m22xivqqz35rr-rust-analyzer-2023-10-16/bin/rust-analyzer"	"stderr"	
'[ERROR project_model::workspace] failed fetching data layout for 
ManifestPath { file: AbsPathBuf("/home/jibe/neovim/config/rust-test/Cargo.toml") } 
workspace e=RUSTC_BOOTSTRAP="1" "rustc" "-Z" "unstable-options" "--print" "target-spec-json" failed\n'
```

Due to this, the completion I got was:

![image](https://github.com/nix-community/nixvim/assets/3251406/5bf7a27a-cd92-480b-aded-56d44b614a9e)

when adding `rustc` to path (`nix-shell -p rustc`) I instead get the following result

![image](https://github.com/nix-community/nixvim/assets/3251406/e119cff1-ae97-45f5-aa32-0ba8fdb9d7e7)

Interestingly, I get warning and help messages from the lsp in my buffer, hence I think the lsp is correctly installed and configured. It seems that cmp needs rustc for the completion. I also noted that cargo indexing didn't start until rustc was available. 
I found an issue on github with a similar error message: 

## Config
I have removed stuff for an isolated configuration. You may test this very minimal configuration by running 
```
nix run github:jdbosser/nvim/nix-minimal
```

### `default.nix` 
``` 
{
  # Import all your configuration modules here
  imports = [
    ./lsp.nix
    ./cmp.nix
  ];
}
```
### `lsp.nix` 
```
{
	plugins.lsp = {
		enable = true; 
		servers = {
			rust-analyzer.enable = true; 
		};

	};
}
```
### `cmp.nix`
```
{pkgs, ...}:
{
	extraPlugins = with pkgs.vimPlugins; [luasnip];
	plugins = {

		nvim-cmp.enable = true; 
		
		cmp-nvim-lsp.enable = true; 
		cmp_luasnip.enable = true; 
		
		nvim-cmp.snippet.expand = "luasnip";
		nvim-cmp.mappingPresets = ["insert"];
		
		nvim-cmp.sources = [
			{name = "nvim_lsp";}
			{name = "luasnip"; }
			{name = "buffer"; }
		];
	};
}
```
## Steps to reproduce

To reproduce the error, ensure that `rustc` is not available in your path. Create a new crate with
```
mkdir lsp-rust-test
cd lsp-rust-test
cargo init
```
then try to edit `main.rs`, i.e, `nix run github:jdbosser/nvim/nix-minimal -- src/main.rs` and look for some completion. 

Then, add `rustc` to your path, i.e., `nix-shell -p rustc`, and rerun `nix run github:jdbosser/nvim/nix-minimal -- src/main.rs` and look for the completions. 

## Suggested solution
I think we should modify the option [installLanguageServer](https://nix-community.github.io/nixvim/plugins/lsp/servers/rust-analyzer/index.html#pluginslspserversrust-analyzerinstalllanguageserver) to ensure that it includes `rustc` as a runtime dependency.

**Comment by GaetanLepage** [comment]
Wow, thank you for this very detailed bug report.
So basically, you have cargo on your path, but not rustc right ?

**Comment by GaetanLepage** [comment]
On my side, `rust-analyze` complains if `cargo` is not on the path.

**Comment by traxys** [comment]
At least for me personally I would _not_ want to have rustc/cargo installed automatically as I always use https://github.com/oxalica/rust-overlay to manage the rust overlay. So I would want something that can toggle this behaviour.

I'm not really sure what is the best solution, maybe adding an specific option to install rustc/cargo that can be `null` (would warn that rustc/cargo must be installed), `false` would not install them, but not warn, and `true` would add them both?
