### ISSUE TITLE
Molten-nvim as Magma Alternative

### ISSUE THREAD

**Issue by mcamp-ata** [nix-community/nixvim#682]
**Plugin**: molten-nvim
**Plugin repository**: [URL to the repository of the plugin](https://github.com/benlubas/molten-nvim)
**Is the plugin on nixpkgs**:  No 

## Extra information
The Magma plugin has some bugs in it and the project might be be maintained. There is currently a fork of Magma called Molten that seems a little more active an provides similar features.

**Comment by GaetanLepage** [comment]
Thanks for reporting this.
Not sure how we should deal with that:

- If magma becomes clearly unmaintained and if it appears clear that molten is the new goto fork, then we will rename + refactor the current `magma` module to target `molten`.
- We can also introduce another nixvim plugin for molten and leave both simultaneously.

Anyway, the first step is to package molten.
I opened a PR upstream: https://github.com/NixOS/nixpkgs/pull/265423
