### ISSUE TITLE
Attribute 'fantomas' missing - not being used

### ISSUE THREAD

**Issue by bee1850** [nix-community/nixvim#697]
**Plugin affected**: none-ls
**Nixpkgs channel**: unstable
**Home-manager version**: 23.11-pre
## Description
Hi everyone,
i recently migrated my vim configuration to use nixvim but rebuilding errors out with the following output:

```
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/xjviahzwa7x51vl51kc3c1k1n                                                                                                                                    1jmhpd5-source/pkgs/stdenv/generic/make-derivation.nix:300:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-g                                                                                                                                    eneration'

         at /nix/store/xjviahzwa7x51vl51kc3c1k1n1jmhpd5-source/pkgs/build-suppor                                                                                                                                    t/trivial-builders/default.nix:87:14:

           86|       enableParallelBuilding = true;
           87|       inherit buildCommand name;
             |              ^
           88|       passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'fantomas' missing

       at /nix/store/nsbcpbwxhm8ihfkgcrp0as86ayksmk4n-source/plugins/none-ls/ser                                                                                                                                    vers.nix:95:19:

           94|       fantomas = {
           95|         package = pkgs.fantomas;
             |                   ^
           96|       };


```
Weirdly i dont think i am using the none-ls plugin anywhere in my configuration.

## Config

```nix
programs.nixvim = {
    enable = true;
    colorscheme.nord.enable = true;
    options = {
      number = true;
      relativenumber = true;
      spell = true;
      spellang = [ "de" "en" ];
      enableMan = true;
      extraConfigVim = "let skip_defaults_vim=1\nset viminfo=\"\"";
    };
    plugins.lsp = {
      enable = true;
      servers = {
        clangd.enable = true;
        bashls.enable = true;
        eslint.enable = true;
        nil_ls.enable = true;
        terraformls.enable = true;
      };
    };
  };
```

**Comment by bee1850** [comment]
fantomas can be found in unstable, but not in stable 23.05
https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=fantomas

**Comment by traxys** [comment]
Are you using the correct nixvim branch with your installation? If you are using a stable nixpkgs then you need to use the stable branch as mentionned here: https://github.com/nix-community/nixvim#installation

**Comment by traxys** [comment]
Sorry, do you mean 23.11 instead of 21.11?

**Comment by bee1850** [comment]
> Are you using the correct nixvim branch with your installation? If you are using a stable nixpkgs then you need to use the stable branch as mentionned here: https://github.com/nix-community/nixvim#installation

Thanks for your reply, i am using the unstable channel as of right now.

**Comment by bee1850** [comment]
This is my current full configuration: https://github.com/bee1850/my-homemanager-configuration

**Comment by bee1850** [comment]
@traxys I hope its okay to ping you, as I'm not used to issues and don't know if you got my replies :) If its bothering you, i'll stop of course.

**Comment by traxys** [comment]
I think you just need to update your lockfile.
Your nixpkgs version is from ~october 10, fantomas was added ~october 19. Generally nixvim is only compatible with a recent nixpkgs version (often less than a week old as we frequently upstream plugins!)

**Comment by bee1850** [comment]
I think that did the job! Much appreciated, I've never used the flake update command, because it never was an issue, I will do this more often now, Thank you very much!
