### ISSUE TITLE
error: attribute 'molten-nvim' missing

### ISSUE THREAD

**Issue by poach3r** [nix-community/nixvim#706]
**Plugin affected**: N/A
**Nixpkgs channel**: Unstable
**Home-manager version**: 23.11-pre

## Description
Attempting to home-manager switch fails with the following output despite me not making any changes to my Neovim configuration.
```                                                                                                  
error: attribute 'molten-nvim' missing

       at /nix/store/i0f5213pc4pdvjhr6jdacfxkxdygdg9q-source/plugins/utils/molten.nix:11:15:

           10|     description = "molten-nvim";
           11|     package = pkgs.vimPlugins.molten-nvim;
             |               ^
           12|     globalPrefix = "molten_";
(use '--show-trace' to show detailed location information)
```

## Config
[Your nixvim config](https://github.com/poach3r/nixos-config/blob/main/home-manager/modules/neovim.nix)

**Comment by poach3r** [comment]
Note: This happens even when I delete everything in my config except for the components necessary for NixVim.
Stripped config
```
{ pkgs, lib, ... }:
let
  nixvim = import (builtins.fetchGit {
    url = "https://github.com/nix-community/nixvim.git";
  });
in
{
  imports = [
    nixvim.homeManagerModules.nixvim
  ];

  programs.nixvim = {
    enable = true;
  };
}
```

home-manager switch output:
```
error: attribute 'molten-nvim' missing

       at /nix/store/i0f5213pc4pdvjhr6jdacfxkxdygdg9q-source/plugins/utils/molten.nix:11:15:

           10|     description = "molten-nvim";
           11|     package = pkgs.vimPlugins.molten-nvim;
             |               ^
           12|     globalPrefix = "molten_";
(use '--show-trace' to show detailed location information)
```

**Comment by GaetanLepage** [comment]
The `molten-nvim` package has been added in the latest jump of `nixos-unstable`.
Try to update your flake inputs and make sure you are following `nixos-unstable` for `nixpkgs`.

**Comment by traxys** [comment]
I saw in your configuration that you have nixpkgs & home-manager as flake inputs, but you directly download nixvim with fetchGit. I'd recommend adding nixvim to the flake inputs too, so that you can update them in lockstep. With your setup your are often going to have problems, as nixvim will update but nixpkgs won't, and this is not a supported nixvim configuration, we require a very recent nixpkgs (we only test with a week old nixpkgs)

**Comment by poach3r** [comment]
These changes worked, thanks!
