### ISSUE TITLE
`rust-tools` negates `lsp-format`

### ISSUE THREAD

**Issue by trueNAHO** [nix-community/nixvim#715]
The [`plugins.rust-tools`](https://nix-community.github.io/nixvim/plugins/rust-tools/index.html) module prevents the [`plugins.lsp-format`](https://nix-community.github.io/nixvim/plugins/lsp-format/index.html) module from working because `require('rust-tools').setup({})` is invoked after the iterative `require('lspconfig')[server.name].setup(options)` operations.

For reference, here is [my NixVim generated `LSP` section](https://github.com/trueNAHO/dotfiles/blob/f599e724facc65040743211fafb7390ecb4dceea/modules/programs/nixvim/default.nix) that negates the `lsp-format` functionality:

```
-- LSP {{{
do
  

  local __lspServers = {{["name"] = "rust_analyzer"},{["name"] = "nil_ls"}}
  local __lspOnAttach = function(client, bufnr)
    require("lsp-format").on_attach(client)

  end
  local __lspCapabilities = function()
    capabilities = vim.lsp.protocol.make_client_capabilities()

    capabilities = require('cmp_nvim_lsp').default_capabilities()


    return capabilities
  end

  local __setup = {
            on_attach = __lspOnAttach,
            capabilities = __lspCapabilities()
          }

  for i,server in ipairs(__lspServers) do
    if type(server) == "string" then
      require('lspconfig')[server].setup(__setup)
    else
      local options = server.extraOptions

      if options == nil then
        options = __setup
      else
        options = vim.tbl_extend("keep", options, __setup)
      end

      require('lspconfig')[server.name].setup(options)
    end
  end

  require('rust-tools').setup({})
  
end
-- }}}
```

The following manually adjusted version works (moved `require('rust-tools').setup({})` to the top): 

```
-- LSP {{{
do
  

  require('rust-tools').setup({})

  local __lspServers = {{["name"] = "rust_analyzer"},{["name"] = "nil_ls"}}
  local __lspOnAttach = function(client, bufnr)
    require("lsp-format").on_attach(client)

  end
  local __lspCapabilities = function()
    capabilities = vim.lsp.protocol.make_client_capabilities()

    capabilities = require('cmp_nvim_lsp').default_capabilities()


    return capabilities
  end

  local __setup = {
            on_attach = __lspOnAttach,
            capabilities = __lspCapabilities()
          }

  for i,server in ipairs(__lspServers) do
    if type(server) == "string" then
      require('lspconfig')[server].setup(__setup)
    else
      local options = server.extraOptions

      if options == nil then
        options = __setup
      else
        options = vim.tbl_extend("keep", options, __setup)
      end

      require('lspconfig')[server.name].setup(options)
    end
  end
  
end
-- }}}
```

Note: During debugging I explicitly enabled the `plugins.lsp.servers.rust-analyzer.enable = true;` setting because otherwise the Lua generated `__lspServers` variable does not contain `{["name"] = "rust_analyzer"}`.

Related: https://github.com/lukas-reineke/lsp-format.nvim/issues/56

**Comment by traxys** [comment]
Could you try looking if #737 fixes the issue? I think this should be the correct reason why this fails after reading https://github.com/lukas-reineke/lsp-format.nvim/issues/56

**Comment by trueNAHO** [comment]
> Could you try looking if #737 fixes the issue?

Yes, this works! Thanks for looking into this.
