### ISSUE TITLE
`context_commentstring` `nvim-treesitter` Module Deprecated

### ISSUE THREAD

**Issue by AmeerTaweel** [nix-community/nixvim#748]
**Plugin Affected**: `ts-context-commentstring`
**Nixpkgs Channel**: [`nixos-unstable`](https://github.com/NixOS/nixpkgs/tree/5a09cb4b393d58f9ed0d9ca1555016a8543c2ac8)
**Home-manager Version**: [`latest`](https://github.com/nix-community/home-manager/tree/a462e7315deaa8194b0821f726709bb7e51a850c)

## Description

When I open NeoVim, I get the following message:

```log
context_commentstring nvim-treesitter module is deprecated, use use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading instead.              
This feature will be removed in ts_context_commentstring version in the future
```

## Config

Relevant part of my config:

```nix
programs.nixvim.plugins.ts-context-commentstring.enable = true;
```

I can include all of my config but it's long and I don't think it's relevant.

**Comment by GaetanLepage** [comment]
Thank you for your report.
I am not able to reproduce the bug with this minimal config:
```nix
plugins = {
  treesitter.enable = true;
  ts-context-commentstring.enable = true;
};
```

Can you update your flake inputs to the latest version and check again please ?

**Comment by AmeerTaweel** [comment]
Sorry I forgot to say that in my report.
Thank you for the fix!
