### ISSUE TITLE
Any way to extend LSP and tree-sitter?

### ISSUE THREAD

**Issue by LennyLizowzskiy** [nix-community/nixvim#759]
I'm looking for https://github.com/fwcd/kotlin-language-server and https://github.com/fwcd/tree-sitter-kotlin support in nixvim. I looked through your code but I couldn't understand how exactly can I setup them myself - got pretty much confused.

**Comment by siph** [comment]
I'm using kotlin in my config and I have something like this:
```nix
{
    plugins = {
      lsp = {
        enable = true;
        servers.kotlin-language-server.enable = true;
      };
      # All grammars are enabled by default
      treesitter.enable = true;
    };
  };
}
```
