### ISSUE TITLE
plugins/debugprint-nvim: init

### ISSUE THREAD

**Issue by trueNAHO** [nix-community/nixvim#763]
How to enable the https://github.com/andrewferrier/debugprint.nvim plugin which is not yet packaged in [Nixpkgs](https://github.com/NixOS/nixpkgs/tree/76f642f87ff9b752ec652efc75234cf2fdc446aa)?

Ideally, I would package the plugin in Nixpkgs, and then in Nixvim. However, I am struggling to try it out it in [my Nixvim configuration](https://github.com/trueNAHO/dotfiles/blob/b5787aee623eeb6a6e7ba1bfbe79dcd00c4bb701/modules/programs/nixvim/default.nix) with:

```nix
{pkgs, ...}: {
  programs.nixvim = {
    extraConfigLua = ''
      require("debugprint").setup()
    '';

    extraPlugins = let
      debugprint-nvim = pkgs.vimUtils.buildVimPluginFrom2Nix {
        meta.homepage = "https://github.com/andrewferrier/debugprint.nvim/";
        pname = "debugprint-nvim";

        src = pkgs.fetchFromGitHub {
          owner = "andrewferrier";
          repo = "debugprint.nvim";
          rev = "8a6d66bd6162e9c49804e9286a7d4ceba60355d5";
          sha256 = "1h2wh86qph38mgfyahy8ha6zpvn2kvs4h2znipxq9z4ybnwcxmf4";
        };

        version = "2022-11-29";
      };
    in [debugprint-nvim];
  };
}
```

Upon starting `neovim`, I receive the error that `debugprint` is not available in the [Lua module path](http://www.lua.org/manual/5.4/manual.html#pdf-package.path):

```
Error detected while processing /home/USER/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/USER/.config/nvim/init.lua:237: module 'debugprint' not found:
        no field package.preload['debugprint']
        no file '/nix/store/fil9z2hnrak3b37fj4n0ki2n0n3fwrni-luajit-2.1.1693350652-env/share/lua/5.1/debugprint.lua'
        no file '/nix/store/fil9z2hnrak3b37fj4n0ki2n0n3fwrni-luajit-2.1.1693350652-env/share/lua/5.1/debugprint/init.lua'
        no file '/nix/store/fil9z2hnrak3b37fj4n0ki2n0n3fwrni-luajit-2.1.1693350652-env/lib/lua/5.1/debugprint.so'
stack traceback:
        [C]: in function 'require'
        /home/USER/.config/nvim/init.lua:237: in main chunk
```

For reference, I loosely followed the Nixvim instructions:

- https://github.com/nix-community/nixvim/blob/fda9e1e9a478c8dbe14cc7e2d8ff1db82619e515/README.md?plain=1#L244-L255
- https://github.com/nix-community/nixvim/blob/fda9e1e9a478c8dbe14cc7e2d8ff1db82619e515/README.md?plain=1#L275-L285

And already looked at how to package plugins in Nixpkgs:

- https://github.com/NixOS/nixpkgs/blob/76f642f87ff9b752ec652efc75234cf2fdc446aa/doc/languages-frameworks/vim.section.md?plain=1#L129-L167

**Comment by traxys** [comment]
That's strange, I'd expect what you have done to work.
Could you try to look at the plugin directory?
If you do `cat $(which nvim)` it should be a shell script with on the last line something along the lines of `set rtp^=/nix/store/fpbvzwgi9pgrm5mbjlxilydzw1z6yhgf-vim-pack-dir`. If you then do `ls <store-path>/pack/myNeovimPackages/start` there should be all your plugins, is there a directory for debugprint?

**Comment by trueNAHO** [comment]
> If you do `cat $(which nvim)` it should be a shell script with on the last line something along the lines of `set rtp^=/nix/store/fpbvzwgi9pgrm5mbjlxilydzw1z6yhgf-vim-pack-dir`. 

Yes.

> If you then do `ls <store-path>/pack/myNeovimPackages/start` there should be all your plugins, is there a directory for debugprint?

Yes, the `debugprint` directory contains the following files:

- `/nix/store/lxsq9cgak74z05gf1bij57dn27bqp4z2-vimplugin-debugprint-nvim-2022-11-29/plugin/vim-printer.vim`
- `/nix/store/lxsq9cgak74z05gf1bij57dn27bqp4z2-vimplugin-debugprint-nvim-2022-11-29/README.md`

The `vim-printer.vim` file contains the following:

```vim
" ============================================================================
" File:        vim-printer.vim
" Author:      Abin Simon
" Description: Easily print out variables in any language
" License:     MIT
" ============================================================================

if exists('g:loaded_vim_printer') || &compatible
  finish
endif
let g:loaded_vim_printer = 1

let s:vim_printer_items_full = { 
            \ 'python': 'print("{$}:", {$})', 
            \ 'javascript': 'console.log("{$}:", {$})',
            \ 'javascriptreact': 'console.log("{$}:", {$})',
            \ 'javascript.jsx': 'console.log("{$}:", {$})',
            \ 'typescript': 'console.log("{$}:", {$})',
            \ 'typescript.tsx': 'console.log("{$}:", {$})',
            \ 'go': 'fmt.Println("{$}:", {$})',
            \ 'vim': 'echo "{$}: ".{$}',
            \ 'rust': 'println!("{$}: {:?}", {$});',
            \ 'sh': 'echo "{$}: ${$}"',
            \ 'bash': 'echo "{$}: ${$}"',
            \ 'zsh': 'echo "{$}: ${$}"',
            \ 'java': 'System.out.println("{$}: " + {$});',
            \ 'lua': 'print("{$}: " .. {$})',
            \ 'cpp': 'std::cout << "{$}: " << {$} << endl;',
            \ 'f77': 'write(6,*)"{$}: ", {$}',
            \ 'f90': 'write(6,*)"{$}: ", {$}' 
            \ }

let g:vim_printer_items = get(g:, 'vim_printer_items', {})
for pi in keys(g:vim_printer_items)
  let s:vim_printer_items_full[pi] = g:vim_printer_items[pi]
endfor

let s:print_below_keybinding = get(g:, 'vim_printer_print_below_keybinding', '<leader>p')
let s:print_above_keybinding = get(g:, 'vim_printer_print_above_keybinding', '<leader>P')


" i am not sure if this is the right way to do it
function s:GetVisualSelection()
    let [lnum1, col1] = getpos("'<")[1:2]
    let [lnum2, col2] = getpos("'>")[1:2]
    let lines = getline(lnum1, lnum2) 

    let lines[-1] = lines[-1][: col2 - (&selection == 'inclusive' ? 1 : 2)]
    let lines[0] = lines[0][col1 - 1:]

    let selectedText = join(lines, "\n")
    return selectedText
endfunction

function! AddPrintLine(visual, above)

    let filetype = &filetype
    if has_key(s:vim_printer_items_full, filetype)
      if a:visual == 1
          let exp = s:GetVisualSelection()
      else
          let exp = expand('<cword>')
      endif

      let ns = substitute(s:vim_printer_items_full[filetype], '{$}', exp, 'g')
      if a:above == 1
          execute ':normal! O' . ns
      else
          execute ':normal! o' . ns
      endif
    else
      echo 'No vim-printer definition available for '. filetype
    endif
endfunction


execute 'nnoremap <silent>'. s:print_below_keybinding . ' :call AddPrintLine(0, 0)<CR>'
execute 'nnoremap <silent>'. s:print_above_keybinding . ' :call AddPrintLine(0, 1)<CR>'
execute 'vnoremap <silent>'. s:print_below_keybinding . ' :call AddPrintLine(1, 0)<CR>'
execute 'vnoremap <silent>'. s:print_above_keybinding . ' :call AddPrintLine(1, 1)<CR>'
```

**Comment by traxys** [comment]
This seems pretty odd, as this does not look like the source of debugprint.nvim...

**Comment by traxys** [comment]
It looks like this plugin: https://github.com/meain/vim-printer

**Comment by trueNAHO** [comment]
> This seems pretty odd, as this does not look like the source of debugprint.nvim...

The `pkgs.vimUtils.buildVimPluginFrom2Nix` function does not seem to be the
culprit as the `pkgs.fetchFromGitHub` function already contains the
`/nix/store/lxsq9cgak74z05gf1bij57dn27bqp4z2-vimplugin-debugprint-nvim-2022-11-29/plugin/vim-printer.vim`
file:

```nix
pkgs.fetchFromGitHub {
  owner = "andrewferrier";
  repo = "debugprint.nvim";
  rev = "8a6d66bd6162e9c49804e9286a7d4ceba60355d5";
  sha256 = "1h2wh86qph38mgfyahy8ha6zpvn2kvs4h2znipxq9z4ybnwcxmf4";
};
```
###

**Comment by trueNAHO** [comment]
The incorrect SHA256 field is the reson `pkgs.fetchFromGitHub` fetches the wrong repository.

**Comment by trueNAHO** [comment]
Now, the `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29` directory contains the correct files:

- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/.github/workflows/panvimdoc.yaml`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/.github/workflows/release-please.yml`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/.github/workflows/tests.yaml`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/.gitignore`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/.stylua.toml`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/CHANGELOG.md`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/Makefile`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/README.md`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/demo/script.lua`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/doc/debugprint.nvim.txt`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/doc/tags`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/lua/debugprint/filetypes.lua`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/lua/debugprint/init.lua`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/lua/debugprint/utils.lua`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/tests/debugprint.lua`
- `/nix/store/nckab5gnnnhgy6rsbm6y37b23bza88rl-vimplugin-debugprint-nvim-2022-11-29/tests/minimal.vim`
