### ISSUE TITLE
lsp.tsserver conflicts with none-ls.sources.prettier

### ISSUE THREAD

**Issue by Theaninova** [nix-community/nixvim#766]
**Plugin affected**: `none-ls`, `lsp`
**Nixpkgs channel**: unstable
**Home-manager version**: 23.11-pre

## Description
Using Prettier with `none-ls` while also enabling the `tsserver` LSP will override prettier and use the built-in formatter instead.

## Config
```nix
lsp = {
  enable = true;
  servers.tsserver.enable = true;
};
none-lsp = {
  enable = true;
  formatting.prettier.enable = true;
};
```

## Workaround

```nix
lsp = {
  enable = true;
  servers.tsserver = {
    enable = true;
    onAttach.function = "client.server_capabilities.documentFormattingProvider = false";
  };
};
none-lsp = {
  enable = true;
  formatting.prettier.enable = true;
};

**Comment by GaetanLepage** [comment]
Hey ! Thank you for reporting this.
You have indeed identified the correct fix.
This is what you are supposed to do as per mentioned in the [none-ls wiki](https://github.com/nvimtools/none-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts#neovim-08).

Whether we should do this automatically in nixvim is a good question:

- **Pro:** It makes no sense do enable `prettier` through `none-ls` while still wanting to use the LSP provided formatting. This would remove this responsibility from the user.
- **Cons:** Stacking this kind of "automatic behaviors" in our code base might not be very sustainable. Also, users don't expect us to do "things in the background".

Honestly, applying this patch automatically does not bother me. What do you think @traxys ?

**Comment by Theaninova** [comment]
Using this repo has been the best experience configuring neovim for me because a lot of sane defaults are already applied and most things *just work* with `enable = true;`. To me as a user it felt like good mixture of just a wrapper and some small patches/enhancements on top to make the config behave more like you'd expect.

I feel like the best way would be something like a `disableTsServerFormatter` that defaults to `true`. That way it's pretty clear that something is being done and making it very obvious how to get rid of it, while also providing default behaviour that has it work out of the box.

I do absolutely understand though if you want to avoid patching thing like this

**Comment by GaetanLepage** [comment]
Completed by #772

**Comment by Theaninova** [comment]
I've just realized that the issue might be more complicated than I thought and is a universal issue with null-ls formatters.

There's actually a whole section about conflicts with LSP servers [here](https://github.com/nvimtools/none-ls.nvim/wiki/Avoiding-LSP-formatting-conflicts) in the none-ls wiki. They specifically recommend against this workaround, and it doesn't seem like there's a super universal solution either. I've seen posts about prompts to select the formatter, which I certainly did not get, but I fixed auto formatting with their guide.

I don't know what the best solution would be, but I think the commit with the warning should probably be reverted, an addition to some docstring feels like a much more appropriate option, since you can't "patch" `vim.lsp.buf.format()`.
