### ISSUE TITLE
Add support for ollama.nvim

### ISSUE THREAD

**Issue by rupurt** [nix-community/nixvim#778]
**Plugin**: ollama.nvim
**Plugin repository**: https://github.com/nomnivore/ollama.nvim
**Is the plugin on nixpkgs**: No

## Extra information

Ollama server is available in nixpkgs https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/tools/misc/ollama/default.nix#L43

**Comment by GaetanLepage** [comment]
Made a PR upstream: https://github.com/NixOS/nixpkgs/pull/275437
