### ISSUE TITLE
`extraSpecialArgs` is not working

### ISSUE THREAD

**Issue by budimanjojo** [nix-community/nixvim#779]
## Description
I don't know what I do wrong, but I pass `extraSpecialArgs` to `makeNixvimWithModule` and it's not working as I thought it should be.

## Config
This is my `flake.nix`:
```
{
  description = "My NixVim flake";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/23.11";
    nixvim.url = "github:nix-community/nixvim";
    flake-parts.url = "github:hercules-ci/flake-parts";
  };

  outputs = { flake-parts, ... }@inputs:
  inputs.flake-parts.lib.mkFlake { inherit inputs; } {
    systems = [
      "x86_64-linux"
      "aarch64-linux"
    ];
    perSystem = {
      inputs',
      pkgs,
      ...
    }: let
      nixvim = inputs'.nixvim.legacyPackages;
      myPkgs = pkgs.callPackage ./packages/default.nix {};
    in
    {
      packages = {
        default = nixvim.makeNixvimWithModule {
          extraSpecialArgs = { inherit myPkgs; };
          module = {
            imports = [
              ./configs/plugins.nix
            ];
          };
        };
      };
    };
  };
}
```

In `./configs/plugins.nix` I have this:
```
{ pkgs, myPkgs, ... }:
{
  config = {
    extraPlugins = [
      myPkgs.chezmoi-vim
    ];
}
```
And when I do `nix run .#`, I get this error:
```
error: attribute 'myPkgs' missing

at /nix/store/mdl8yp9lzzzjla69qm42sk96p15vym7d-source/lib/modules.nix:506:28:

   505|         builtins.addErrorContext (context name)
   506|           (args.${name} or config._module.args.${name})
      |                            ^
   507|       ) (lib.functionArgs f);
```

I also checked my `flake.lock`, I'm using the latest commit from this repo so the feature from PR https://github.com/nix-community/nixvim/pull/665 should be available?

**Comment by Alexnortung** [comment]
I am having the same issue

@traxys I don't think that the config is properly passed to the modules. I am not sure, but maybe the `config` should be passed to `evalModules` instead of the `_shared.nix` file that doesn't really use the config anyway. https://github.com/nix-community/nixvim/blob/cc3f5209c1253442608d17055d14e5da2122dabd/wrappers/standalone.nix#L20C22-L20C22
