### ISSUE TITLE
startup.nvim

### ISSUE THREAD

**Issue by MartinEekGerhardsen** [nix-community/nixvim#791]
**Plugin**: startup.nvim
**Plugin repository**: [URL to the repository of the plugin](https://github.com/startup-nvim/startup.nvim)
**Is the plugin on nixpkgs**: No

## Extra information
Customizable startup screen for neovim, similar to startify. 
Depends on plenary.nvim, and should depend on telescope.nvim for default setup.
I don't really understand fully how nixvim works, so I'm not sure how to add this myself, but if it would be simple for someone to implement this, I'd be grateful!

**Comment by GaetanLepage** [comment]
Made a PR to upstream the plugin: https://github.com/NixOS/nixpkgs/pull/273636
