### ISSUE TITLE
[New module] lazy.nvim

### ISSUE THREAD

**Issue by pta2002** [nix-community/nixvim#797]
**Plugin**: lazy.nvim
**Plugin repository**: https://github.com/folke/lazy.nvim
**Is the plugin on nixpkgs**: [Yes](https://github.com/NixOS/nixpkgs/blob/b4372c4924d9182034066c823df76d6eaf1f4ec4/pkgs/applications/editors/vim/plugins/generated.nix#L4789)

## Extra information
Following the discussions around #421, one thing has become clear: lazy.nvim already implements pretty much everything we need.

Therefore, instead of reinventing the wheel, the best course of action starts with adding a module to allow for plugin management via `lazy.nvim`. This can later be implemented to load plugins from `extraPlugins`, but at first it can just be a separate option from the module, given that supporting that would require a flag to tell nixvim to not install plugins the other way.

Either way, this should follow the same general idea as the [packer module](https://github.com/nix-community/nixvim/blob/main/plugins/pluginmanagers/packer.nix). Since `lazy.nvim` supports loading plugins from a directory (via the `dir` option), we can sidestep its plugin downloading completely, too, keeping the config reproducible :) (Though we should still allow a user to have `lazy.nvim` download plugins, in order to let them easily install out-of-tree plugins. However, IMO everything officially supported by us should come from Nix, since it's not that much extra work to package).

Eventually™ we can fork out lazy.nvim's lazy-loading code to a separate library, and have a module for that, to make builds smaller. But as I said in the beginning, no need to reinvent the wheel for now! Let's just use what works and see how it goes.

**Comment by ehsan2003** [comment]
I kinda guess that reinventing the wheel in this case is pretty much appropriate

**Comment by pta2002** [comment]
@ehsan2003 there was a fairly long discussion about this in #421, and the general consensus was basically "lazy.nvim already does this and we can use it to try out the idea at first and then eventually roll our own", but obviously there's merits to doing this ourselves. If you have any insights feel free to leave them in the original feature issue

**Comment by ck3mp3r** [comment]
I've started experimenting with creating a plugin manager for lazy.nvim. I've taken the current packer.nix implementation as inspiration as I am not that familiar with the internals just yet.
Still a fair amount of work left (need to implement some more of the lazy.nvim basic properties), but this is a working version.
https://github.com/ck3mp3r/nixvim/pull/1/files
This does not address using lazy.nvim as a default package manager for xvim, there would need to be a bit of re-architecting required to make that work, but at least this would be a stop gap solution for those needing lazy loading for some of their plugins.

Constructive criticism welcome!

**Comment by ck3mp3r** [comment]
I've added a PR for adding lazy.nvim as an alternative to packer. Still draft until some other folks give it a spin.
https://github.com/nix-community/nixvim/pull/1175
I've been using this to refactor my nixvim config to allow lazy package management, not allowing fetching outside of the nix package ecosystem however, kinda defeats the purpose...

Please feel free to give it a spin!

**Comment by ck3mp3r** [comment]
@pta2002 I guess we can close this now since the new plugin has landed...

**Comment by pta2002** [comment]
You're right!
