### ISSUE TITLE
Fidget plugin options have changed

### ISSUE THREAD

**Issue by arjan-s** [nix-community/nixvim#818]
**Plugin affected**: fidget
**Nixpkgs channel**: unstable
**Home-manager version**: latest master

## Description
The fidget plugin options have changed, breaking the current nixvim options and causing these errors:
```
[WARN  Sun 17 Dec 2023 08:44:03 PM CET] /lua/fidget.lua:48: Encountered unknown options during setup():
[WARN  Sun 17 Dec 2023 08:44:03 PM CET] /lua/fidget.lua:50: - unknown option: window
[WARN  Sun 17 Dec 2023 08:44:03 PM CET] /lua/fidget.lua:50: - unknown option: text
```
As can be seen on [their README](https://github.com/j-hui/fidget.nvim), the `text` option has disappeared and the `window` option is now below a `notification` option. The whole options structure and list seem to have changed.

## Config
```nix
plugins.fidget = {
  enable = true;
  text.spinner = "meter";
  window = {
    blend = 0;
    border = "rounded";
  };
};
```

**Comment by GaetanLepage** [comment]
Fixed by #839
