### ISSUE TITLE
[PLUGIN REQUEST] `codeium.vim`

### ISSUE THREAD

**Issue by trueNAHO** [nix-community/nixvim#824]
**Plugin**: `codeium.vim`
**Plugin repository**: https://github.com/Exafunction/codeium.vim
**Is the plugin on nixpkgs**: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/applications/editors/vim/plugins/generated.nix#L2050

Related: https://github.com/nix-community/nixvim/issues/825

**Comment by GaetanLepage** [comment]
Is there a reason to support both `codeium.nvim` and `codeium.vim` ? I am not sure to grasp the difference between the two.

**Comment by trueNAHO** [comment]
> Is there a reason to support both `codeium.nvim` and `codeium.vim` ? I am not sure to grasp the difference between the two.

Essentially:

| Plugin | Purpose |
|-|-|
| `codeium.nvim` | LSP linewise suggestions |
| `codeium.vim` | Suggests code chunks similar to copilot |

Both plugins fullfill different codeium use cases.
