### ISSUE TITLE
[PLUGIN REQUEST] `codeium.nvim`

### ISSUE THREAD

**Issue by trueNAHO** [nix-community/nixvim#825]
**Plugin**: `codeium.nvim`
**Plugin repository**: https://github.com/Exafunction/codeium.nvim
**Is the plugin on nixpkgs**: https://github.com/NixOS/nixpkgs/pull/276080

Related: https://github.com/nix-community/nixvim/issues/824

**Comment by trueNAHO** [comment]
For reference, https://github.com/NixOS/nixpkgs/pull/276080 has been merged upstream.

**Comment by trueNAHO** [comment]
Using https://github.com/nix-community/nixvim/pull/862 results in the following error message when opening `neovim`:

> `b7e7f7ac837ef1c7e20a4122b63630dfa501872f` does not match the expected Codeium server stamp of `16949c552cfc9641be68408fa1a88aa6968c103d`. Please update to: https://github.com/Exafunction/codeium/releases/tag/language-server-v1.6.7

Note that I just `nix flake update`d all my inputs, including `nixvim`, `nixpkgs`, and `home-manager`.

**Comment by GaetanLepage** [comment]
Thank you for reporting this. It is actually very annoying as [they seem to require](https://github.com/Exafunction/codeium.nvim/blob/f871000e91faa9ed334da2bfa4eadbf54d0e1047/lua/codeium/update.lua) a [specific version](https://github.com/Exafunction/codeium.nvim/blob/f871000e91faa9ed334da2bfa4eadbf54d0e1047/lua/codeium/versions.json) of `codeium` in the nvim plugin. For normal users, this is not too bad, as the plugin itself is in charge of downloading the correct codeium binary.
However, in the nixpkgs version of `codeium-nvim`, we patch the binary path and set it to the codeium packaged in nixpkgs (which is currently more recent (1.6.16) than what is required by the plugin(1.6.7)).

With that said, we have two choices (both to be applied in nixpkgs):
- We get rid of the version check and hope that the plugin will always be compatible with the more recent versions of the codeium language server.
- We patch the plugin with a modified version of codeium for which we set the version to be exactly what is asked for by the plugin (using `codeium.overrideAttrs`).

@teto what approach would you recommend in this case ?

**Comment by GaetanLepage** [comment]
In the upstream `flake.nix`, they adopt the second approach: https://github.com/Exafunction/codeium.nvim/blob/main/flake.nix

**Comment by teto** [comment]
the first solution will get nixpkgs a bad rap, as it will surprise upstream and is sure to make them mad.
The second solution is better, but caching the two different versions of the executable bothers me. 
Alternatively we could prevent bumps of codeium not supported by the vim plugin ?
This gets annoying if:
- the vim plugin version is bumped regularly (because it would break the vimplugins updates)
- a possible emacs plugin sets different versions as well :'(

As such
 
> We patch the plugin with a modified version of codeium for which we set the version to be exactly what is asked for by the plugin (using codeium.overrideAttrs).

may seem like the best compromise.
