### ISSUE TITLE
Request to add support for image.nvim

### ISSUE THREAD

**Issue by MartinEekGerhardsen** [nix-community/nixvim#827]
**Plugin**: image.nvim
**Plugin repository**: [URL to the repository of the plugin](https://github.com/3rd/image.nvim)
**Is the plugin on nixpkgs**: Yes

## Extra information
The plugin adds some image support to nvim. 

This plugin requires the extra lua package `ps.magick`, and the already packaged vim plugin `image-nvim`. The config seems likely to be pretty easy to map to nix. The backend option can be either "kitty" or "ueberzug", and the integrations can currently have fields for "markdown" and "neorg". 

I got this working using this nix configuration: 
```
programs.nixvim = {
    extraPlugins = [pkgs.vimPlugins.image-nvim];
    extraLuaPackages = ps: [ps.magick];

    # TODO: have some logic regarding which backend to use
    extraConfigLua = ''
      require("image").setup({
        backend = "kitty",

        integrations = {
          markdown = {
            enabled = true,
            clear_in_insert_mode = false,
            download_remote_images = true,
            only_render_image_at_cursor = false,
            filetypes = {
              "markdown",
              "vimwiki",
            }, -- markdown extensions (ie. quarto) can go here
          },

          neorg = {
            enabled = true,
            clear_in_insert_mode = false,
            download_remote_images = true,
            only_render_image_at_cursor = false,
            filetypes = {
              "norg",
            },
          },

        },

        max_width = nil,
        max_height = nil,

        max_width_window_percentage = nil,
        max_height_window_percentage = 50,

        window_overlap_clear_enabled = false, -- toggles images when windows are overlapped
        window_overlap_clear_ft_ignore = {
          "cmp_menu",
          "cmp_docs",
          "",
        },

        editor_only_render_when_focused = false, -- auto show/hide images when the editor gains/looses focus

        tmux_show_only_in_active_window = false, -- auto show/hide images in the correct Tmux window (needs visual-activity off)

        hijack_file_patterns = {
          "*.png",
          "*.jpg",
          "*.jpeg",
          "*.gif",
          "*.webp",
        }, -- render image files as images when opened
      })
    '';
};

**Comment by GaetanLepage** [comment]
What are you meaning by "have some logic regarding which backend to use" ?
I don't really see what we could do.

**Comment by MartinEekGerhardsen** [comment]
> What are you meaning by "have some logic regarding which backend to use" ? I don't really see what we could do.

Sorry for the late reply, I just meant that it might be possible to limit which options the backend could be, as there were only two options, so e.g. using backend = "asdf" wouldn't compile :P Sorry, I'm not really too well versed in nix yet.

Thanks for the work you did!

**Comment by GaetanLepage** [comment]
> Sorry for the late reply, I just meant that it might be possible to limit which options the backend could be, as there were only two options, so e.g. using backend = "asdf" wouldn't compile :P Sorry, I'm not really too well versed in nix yet.

Yes ! This is what I ended up doing.
`backend` can take only two values ("ueberzug" and "kitty") and, in the former case, it ensures that `ueberzugpp` gets added to `extraPackages`.

**Comment by MartinEekGerhardsen** [comment]
I see, that's really cool! Thank you!
