### ISSUE TITLE
Plugin request - veil.nvim

### ISSUE THREAD

**Issue by vnuxa** [nix-community/nixvim#828]
**Plugin**: veil.nvim
**Plugin repository**: [URL to the repository of the plugin](https://github.com/willothy/veil.nvim)
**Is the plugin on nixpkgs**: no

## Extra information
would be nice to customize sections and stuff

**Comment by GaetanLepage** [comment]
Made a PR to upstream the plugin: https://github.com/NixOS/nixpkgs/pull/277537

**Comment by GaetanLepage** [comment]
Actually, `veil.nvim` has been marked as "unmaintained" as the user is aiming at rewriting it.
Hence, I won't add this plugin "as is" into nixvim. Of course, if a new maintained version is released, I will go on and add support for it.

In the meantime, you can either
- use the existing plugins that we propose for startup screens (`startup` and `startify`)
- install `veil.nvim` manually (using `plugins.packer` or `extraPlugins`) and configure it using `extraConfigLua`.

I will thus close this issue.
I hope that you understand the reasoning and that one of those solutions will fit your use case :)
