### ISSUE TITLE
"highlights.tabSeparatorSelected.underline =" missing? 

### ISSUE THREAD

**Issue by RoccoRakete** [nix-community/nixvim#868]
**Plugin affected**: bufferline
**Nixpkgs channel**: unstable

## Description

According to "bufferline help", `highlights.tabSeparatorSelected.underline =` should be a valid value. But this doesn't seem to exist in the nixpkg. Is this a bug or a missing feature or something else? 

## Config

`    highlights =
      {
        tabSeparatorSelected.underline = "#89b4fa";
      };`

**Comment by RoccoRakete** [comment]
`A definition for option `programs.nixvim.plugins.bufferline.highlights.tabSeparatorSelected.underline' is not of type `null or boolean'. Definition values:`

This shouldn't accept only boolean values right?

**Comment by GaetanLepage** [comment]
After verification, this is an error for the documentation. `underline` is indeed limited to boolean values.
They state in the documentation that those values are passed to `nvim_set_hl` which expects boolean values for `underline`:
- https://github.com/akinsho/bufferline.nvim/blob/e48ce1805697e4bb97bc171c081e849a65859244/doc/bufferline.txt#L793-L794
- https://neovim.io/doc/user/api.html#nvim_set_hl()

**Comment by RoccoRakete** [comment]
Okay, thank you!
