### ISSUE TITLE
Request: rustaceanvim

### ISSUE THREAD

**Issue by garaiza-93** [nix-community/nixvim#893]
**Plugin**: rustaceanvim
**Plugin repository**: https://github.com/mrcjkb/rustaceanvim
**Is the plugin on nixpkgs**: Yes

## Extra information
`rust-tools` has been archived and effectively replaced by this fork. A flake is available as well.

**Comment by trueNAHO** [comment]
Reference: https://github.com/mrcjkb/rustaceanvim/discussions/122

**Comment by GaetanLepage** [comment]
Thanks ! The PR is ready and should be merged very soon :)
