### ISSUE TITLE
Enabling the java language server and trying to use it results in an error.

### ISSUE THREAD

**Issue by ivandimitrov8080** [nix-community/nixvim#899]
**Plugin affected**: LSP
**Nixpkgs channel**: unstable

## Description
Enabling this option and trying to use it:

```nix
        plugins.lsp.servers.java-language-server.enable = true;
```

Results in this error:

```
Error executing vim.schedule lua callback: ...rapped-0.9.5/share/nvim/runtime/lua/vim/lsp/handlers.lua:122: bad argument #1 to 'ipairs' (table expected, got nil)                                                   
stack traceback:
        [C]: in function 'ipairs'
        ...rapped-0.9.5/share/nvim/runtime/lua/vim/lsp/handlers.lua:122: in function 'handler'
        ...eovim-unwrapped-0.9.5/share/nvim/runtime/lua/vim/lsp.lua:1056: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I tried creating a flake for [this repo](https://github.com/gunnarmorling/1brc)

## Config
That's the config basically.

**Comment by GaetanLepage** [comment]
Thank you for reporting this.
I was indeed able to reproduce the issue.
However, I am not sure that this bug has anything to do with nixvim. I will then be closing this.
If you find any lua code that is wrong or missing in your generated `init.lua`, please feel free to re-open this issue.
Also, if you have access to a classic (non-nix) neovim setup, it could be nice to try reproducing this behavior there.

Also, maybe you could you try using `nvim-jdtls` instead. This is what people seem to recommend.

**Comment by GaetanLepage** [comment]
Some people seem to encounter this error on a "normal" neovim setup:
https://github.com/georgewfraser/java-language-server/issues/267

**Comment by siph** [comment]
I remember reporting this in the original pr: #417. It was annoying but I think the server would still work. I ended up switching to `nvim-jdtls` although I don't write java anymore so I haven't really used it much.
