### ISSUE TITLE
Nixvim failing to install

### ISSUE THREAD

**Issue by Lenny0939** [nix-community/nixvim#917]
**Nixpkgs channel**: Either unstable or your nixos version
unstable
**Home-manager version**: (if applicable)
24.05

## Description
Installing nixvim using flakes and home manager causes this error: 
error: attribute 'templ' missing

       at /nix/store/swb1bp18w4hj1s3xwdn3r5624h4cmpz8-source/plugins/lsp/helpers.nix:6:15:

            5|     serverName ? name,
            6|     package ? pkgs.${name},
             |               ^
            7|     cmd ? (cfg: null),
       Did you mean one of tempo, tepl, impl, teip or tml?

I tried nix-shell -p templ for trouble shooting, which did not work, even though the package came up in the nixos package search, and I could also run it by nix run nixpkgs#templ
## Config
It does not build even if it is not configured at all, the only thing is in imports I have `inputs.nixvim.homeManagerModules.nixvim
`

**Comment by siph** [comment]
You need to update nixpkgs in your `flake.lock`: https://github.com/nix-community/nixvim/pull/905#issuecomment-1880096880

**Comment by GaetanLepage** [comment]
> You need to update nixpkgs in your `flake.lock`: [#905 (comment)](https://github.com/nix-community/nixvim/pull/905#issuecomment-1880096880)

Yes, this is why it fails.
