### ISSUE TITLE
Nord theme no longer listed in colorschemes

### ISSUE THREAD

**Issue by smsegal** [nix-community/nixvim#941]
**Plugin affected**: nord colorscheme
**Nixpkgs channel**: unstable
**Home-manager version**: N/A, using standalone

## Description
It appears that [this commit](https://github.com/nix-community/nixvim/commit/3be30efc3b0297d9fae9d9feaacfce33de7887f0) caused the nord colorscheme to be removed from the colorscheme list and breaks configuration that uses nord. 

## Config
relevant snippet
```nix
    colorschemes = { 
      nord = {
        enable = true;
        disable_background = true;
        italic = false;
        contrast = true;
        borders = true;
      };
    };
```
Nixvim will no longer build with a reference to nord in the `colorschemes` attrset. Removing nord will fix the build as will specifying nord as a plugin instead of a colorscheme. 
I also noticed that on the documentation site, nord was also moved into the plugin section.

**Comment by GaetanLepage** [comment]
Indeed, I messed that up during a big rewrite. Fixed in #943 .

**Comment by GaetanLepage** [comment]
Thank you for having reported the issue !

**Comment by smsegal** [comment]
Thanks for the quick fix!
