### ISSUE TITLE
Plugin request: haskell-scope-highlighting.nvim

### ISSUE THREAD

**Issue by fbordwell** [nix-community/nixvim#948]
**Plugin**: haskell-scope-highlighting.nvim
**Plugin repository**: https://github.com/kiyoon/haskell-scope-highlighting.nvim
**Is the plugin on nixpkgs**: No

## Extra information
Good suggestions are given in the [customizations section](https://github.com/kiyoon/haskell-scope-highlighting.nvim?tab=readme-ov-file#configure-highlight-groups). I'm new to nix and nixvim, so I apologize if there are difficulties with this plugin I'm overlooking. Thanks!

**Comment by garaiza-93** [comment]
Waiting on [#284070](https://github.com/NixOS/nixpkgs/pull/284070) :D
