### ISSUE TITLE
userCommands without options cannot load

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [nix-community/nixvim#954]
**Plugin affected**: nixvim/modules/commands.nix
**Nixpkgs channel**: 23.11
**Home-manager version**: 23.11

## Description

If you set an userCommand with just a `command` (see Config below), nvim will error at start with the following error:

```
Error detected while processing /home/geoffrey/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/geoffrey/.config/nvim/init.lua:223: Expected lua table
stack traceback:
        [C]: at 0x0045d760
        /home/geoffrey/.config/nvim/init.lua:223: in main chunk
```

## Debugging

In `.config/nvim/init.lua` we can see around those line:

```lua
do
  local cmds = {["Reload"] = {["command"] = "source /home/geoffrey/.config/nvim/init.lua"}};
for name,cmd in pairs(cmds) do
  vim.api.nvim_create_user_command(name, cmd.command, cmd.options)
end
```

Seems like it's missing a `["options"] = {}` in the `cmds` local. Looking at the [nixvim code](https://github.com/nix-community/nixvim/blob/8104e24adcedb10475a5aa005fe958f4e5bd5a88/lib/helpers.nix#L34),  we can see that attrsets elements are not included if their value is an empty attrset. I guess we could remove this exception and this would work, but probably this was put there for a reason?

## Workaround

Add a dummy option, like `force = false;`.

## Config

```nix
nixvim.userCommands.Reload = { command = "source ${config.xdg.configHome}/nvim/init.lua"; };
```

**Comment by GaetanLepage** [comment]
Indeed, nice catch :)
Thank you for reporting.
This will be fixed by #955
