### ISSUE TITLE
Add support of `lualine-lsp-progress`

### ISSUE THREAD

**Issue by Velnbur** [nix-community/nixvim#956]
**Plugin**: lualine-lsp-progress
**Plugin repository**: https://github.com/arkav/lualine-lsp-progress
**Is the plugin on nixpkgs**: [Yes](https://search.nixos.org/packages?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=lualine-lsp-progress)

## Extra information

I want to have a progress line of lsp server's as for now I can't find any ways for that for `lualine`, so propose to add it. I see that it wasn't updated for a while, but alternatives are not better (see [`lsp-status`](https://github.com/nvim-lua/lsp-status.nvim))

**Comment by GaetanLepage** [comment]
Thank you for this suggestion.
I wonder what would be the added value of "including" this plugin.
It does not have any option (you directly configure it through `lualine`).
So it would boil down to a single `plugins.lualine-lsp-progress.enable` option which is strictly equivalent to
```nix
extraPlugins = [pkgs.vimPlugins.lualine-lsp-progress];
```

We could also add a `plugins.lualine.lsp-progress-plugin.enable` option...

@traxys any opinion ?

**Comment by Velnbur** [comment]
@GaetanLepage  Yeah, I've tried to write a PR for that, but that was only thing I need to is add an options to `lualine`. May be, I jumped to the conclusions, so will close this issue. Sorry for taken time

**Comment by GaetanLepage** [comment]
> @GaetanLepage Yeah, I've tried to write a PR for that, but that was only thing I need to is add an options to `lualine`. May be, I jumped to the conclusions, so will close this issue. Sorry for taken time

Yes, I guess there is nothing we really need to add to lualine.
You simply have to add `lualine-lsp-progress` to `extraPlugins` and then define a `lsp_progress` section in `plugins.lualine.sections`.

I will close this issue then.
