### ISSUE TITLE
[BUG] yanky configuration problem

### ISSUE THREAD

**Issue by ehsan2003** [nix-community/nixvim#967]
| Field        | Description |
|--------------|-------------|
| Plugin       | `yanky`  | 
| Nixpkgs      | `unstable` | 

## Description
yanki puts highlights inside picker option which isn't what's documented in yanki

generated lua code:
```lua
require('yanky').setup({["picker"] = {["highlight"] = {["timer"] = 100}}})
```
but yanki expects something like this:
```lua
{
  picker = {
    select = {
      action = nil, -- nil to use default put action
    },
  },
 
  highlight = {
    on_put = true,
    on_yank = true,
    timer = 500,
  },
}
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    plugins.yanky.enable = true;
    plugins.yanky.highlight.timer = 100;
}
```

**Comment by GaetanLepage** [comment]
Thank you for reporting.
Indeed, the implementation was flawed.
