### ISSUE TITLE
null-ls: add ability to specify custom servers

### ISSUE THREAD

**Issue by seghers** [nix-community/nixvim#97]
``` nix
  programs.nixvim = {
      plugins.null-ls = {
        enable = true;
        sources.formatting.black.enable = true;
        sources.formatting.prettier.enable = true;
        sources.diagnostics.shellcheck.enable = true;
      };

      extraPlugins = with pkgs.vimPlugins; [
        null-ls-nvim
      ];
      extraPackages = [
        pkgs.shfmt
      ];

      extraConfigLua = ''
        require('null-ls').setup {
          sources = {
            require('null-ls').builtins.formatting.shfmt.with({
              -- Indent with 4 spaces, simplify the code, indent switch cases,
              -- add space after redirection
              extra_args = { '-i', '4', '-s', '-ci', '-sr' },
            }),
          },
        }
    '';
  };
```
When I open a shell script and try to format it, it doesn't work.
The null-ls formatter isn't recognized.
`Error: [LSP] Format request failed, no matching language servers.`
I do see the diagnostics from shellcheck.
I think this is because inside nvim/init.lua: I see the nixvim generated null-ls generated way before the one I set in extraConfigLua, and only the first is executed...?
For now I do all null-ls inside extraConfigLua, without plugins.null-ls.
Could we add something to insert lua inside null-ls? plugins.null-ls.manualsources ?

When I do everything inside extraConfigLua it does work.
``` nix
  programs.nixvim = {
     extraPlugins = with pkgs.vimPlugins; [
        null-ls-nvim
     ];
      extraPackages = [
        pkgs.shfmt
      ];

      extraConfigLua = ''
        require('null-ls').setup {
          sources = {
            require('null-ls').builtins.formatting.shfmt.with({
              -- Indent with 4 spaces, simplify the code, indent switch cases,
              -- add space after redirection
              extra_args = { '-i', '4', '-s', '-ci', '-sr' },
            }),
            require("null-ls").builtins.formatting.prettier,
            require("null-ls").builtins.formatting.black,
            require("null-ls").builtins.diagnostics.shellcheck
          },
        }
    '';
  };
```

I could make a pull request to just add `shfmt` to nixvim, but I don't see a way to configure the `extra_args` inside plugins.null-ls.

**Comment by pta2002** [comment]
Yeah you're right that what you're doing won't work - the solution at the moment would be to either patch nixvim to add shfmt, or to just skip the module for null-ls.

Of course, the *proper* solution is to add the ability to add custom packages to null-ls without patching NixVim, so I'll change this issue to reflect that so I can add that functionality.

**Comment by Alexnortung** [comment]
I think there is a pretty easy fix for this. Just include an extraOptions options, so you can configure everything if nixvim doesn't have the options for it.

Related #30

**Comment by GaetanLepage** [comment]
Is this issue now fixed ? (thanks to https://github.com/pta2002/nixvim/pull/251)

**Comment by GaetanLepage** [comment]
As [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621) has been archived we will not spend time enhancing our current implementation.
If you find any bug/problem with the way we support null-ls now, please feel free to re-open.

**Comment by alesauce** [comment]
Howdy! Reopening this issue since the [none-ls fork was created](https://github.com/nvimtools/none-ls.nvim) and subsequently added in to Nixvim. Is adding the ability to add custom servers something that could be looked into again?
