### ISSUE TITLE
[PLUGIN REQUEST] telescope-ui-select

### ISSUE THREAD

**Issue by gbirke** [nix-community/nixvim#972]
| Field    | Description |
|----------|-------------|
| Plugin   | `telescope-ui-select.nvim`  | 
| Homepage | https://github.com/nvim-telescope/telescope-ui-select.nvim     | 
| Nixpkgs  | `vimplugin-telescope-ui-select.nvim` | 

## Extra Information

The plugin would have to add the following code in the Telescope `setup` function

```lua
extensions = {
    ["ui-select"] = {
      require("telescope.themes").get_dropdown {
      }
}
```

Being a newbie to Nix, I'm not sure if the current modules allow for extensions to add Lua code to the `setup` function. If you give me some pointers, I might be able to create a pull request, but at the moment, that task is too daunting

**Comment by garaiza-93** [comment]
> I'm not sure if the current modules allow for extensions to add Lua code to the setup function

They sure do! A lot of the heavy lifting has already been done to integrate Telescope extensions. [Here's how it's done](https://github.com/nix-community/nixvim/blob/main/plugins/telescope/default.nix#L118)
The `enabledExtensions`set is assigned to a Lua variable. The init file is generated, along with `enabledExtensions` parsed as a Lua object. Once nvim runs, Telescope will know what extensions to run!
Note that `enabledExtensions` is an internally used attribute, and it's the backbone of all of this. See the [file-browser](https://github.com/nix-community/nixvim/blob/main/plugins/telescope/file-browser.nix#L212) extension. When this plugin is enabled, an entry to `enabledExtensions` is added.

Therefore, adding this extension to Telescope is not so complicated. Here's an outline:
1. Write the plugin's module, following [CONTRIBUTING.md](https://github.com/nix-community/nixvim/blob/main/CONTRIBUTING.md). 
I encourage you to see both a plugin module's source and that plugin's configuration. In my opinion, The structure of a plugin module looks verrrrry similar to its configuration. It gets complicated when the configuration you're trying to mimic is complicated lol.
2. [Add the extension to Telescope, and pass on the plugin's configuration](https://github.com/nix-community/nixvim/blob/main/plugins/telescope/file-browser.nix#L211-L214)
3. Make your PR!

**Comment by garaiza-93** [comment]
And if you need help, open a draft PR :+1:
