### ISSUE TITLE
[PLUGIN REQUEST] vim-helm + Helm LSP

### ISSUE THREAD

**Issue by mnaser** [nix-community/nixvim#989]
| Field    | Description |
|----------|-------------|
| Plugin   | [`vim-helm`](https://github.com/towolf/vim-helm) + [`helm-ls`](https://github.com/mrjosh/helm-ls)  | 
| Homepage | https://github.com/towolf/vim-helm +   https://github.com/mrjosh/helm-ls   | 
| Nixpkgs  | https://search.nixos.org/packages?channel=23.11&show=vimPlugins.vim-helm&from=0&size=50&sort=relevance&type=packages&query=vim-helm + https://search.nixos.org/packages?channel=23.11&show=helm-ls&from=0&size=50&sort=relevance&type=packages&query=helm-ls | 

## Extra Information

This would be super neat to have!  Thank you for the awesome project.

**Comment by samos667** [comment]
Hi, there is a common problem with file detection when using helm-ls and yamlls, described in this [issue](https://github.com/neovim/nvim-lspconfig/issues/2252)

The only possible fix I've found is to install the vim-helm plugin via lazy and use this option "ft = helm" (like this [comment]([issue](https://github.com/neovim/nvim-lspconfig/issues/2252#issuecomment-2198825338)
)

Is there a way to achieve this in the context of nixvim ?

**Comment by MattSturgeon** [comment]
> The only possible fix I've found is to install the vim-helm plugin via lazy and use this plugin definition: "ft = helm" (like this [comment](https://github.com/neovim/nvim-lspconfig/issues/2252#issuecomment-2198825338) suggest)
> 
> Is there a way to achieve this in the context of nixvim ?

Does [this section of the docs](https://nix-community.github.io/nixvim/NeovimOptions/filetype/index.html) answer your question?

I'm half asking if our docs are any good and half asking if defining a vim filetype is the solution 😁

**Comment by samos667** [comment]
The problem with LSP-config filetype, that it seems you cannot exclude a LSP server for a defined filetype. With the following declaration, opening a helm files (detection of helm file type is base on the dir of the files, that must be on */template/*.yaml) with yaml extention trigger helmls and yamlls but the excepted behavior, in this context, is to attach only helmls.

```nix
{
  plugins = {
    helm.enable = true;
    lsp.servers = {
      helm-ls = {
        filetypes = ["helm"];
        enable = true;
      };

      yamlls = {
        enable = true;
        filetypes = ["yaml"];
        settings = {
        };
      };
    };
  };
}
```
![image](https://github.com/user-attachments/assets/e90eab97-102d-4f05-b622-e21ee8a21179)


Sadly I cannot find how to exclude a filetype for a specific LSP in LSP-config...

**Comment by samos667** [comment]
It's really frustrating, is like the only way to have a proper support for helm is to use [this](https://github.com/mrjosh/helm-ls/blob/master/examples/nvim/init.lua#L20) "obscure" lazy option.

There is no way to have a similar behavior in Nixvim context ?

**Comment by MattSturgeon** [comment]
Does calling `setup` in a ftplugin file help?

**Comment by samos667** [comment]
You mean like this ?

```nix
{
  extraFiles = {
    "ftplugin/lazy.lua".text = ''
      require("lazy").setup({
        -- towolf/vim-helm provides basic syntax highlighting and filetype detection
        -- ft = 'helm' is important to not start yamlls
        { 'towolf/vim-helm', ft = 'helm' },
      })
    '';
  };
  plugins = {
    # helm.enable = true;
    lazy.enable = true;
    lsp.servers = {
      helm-ls = {
        filetypes = ["helm"];
        enable = true;
      };

      yamlls = {
        enable = true;
        filetypes = ["yaml"];
      };
  };
}
```

It doesn't seem to install the vim-helm plugin this way. And uncommenting causes the same issue as before.

**Comment by MattSturgeon** [comment]
(Re-opening as #997 was only ever marked as a "partial" fix)



> You mean like this

I was thinking more like:

```nix
files."ftplugin/helm.lua" = {
  plugins.lsp = {
    enable = true;
    servers.helm-ls = {
      filetypes = ["helm"];
      enable = true;
    };
  };
}
```

But that seems too simple to actually work, there'd probably be issues with lsp being setup more than once...

**Comment by samos667** [comment]
Damn, always to protect my eyes when writing/reading helm template, I disable diagnostics by stopping LSP. But this time I missclick and just restart LSP. And in this case I found the expected behavior on helm-ls !
![image](https://github.com/user-attachments/assets/943e4820-f87b-4698-a418-4f6076d4ede3)

Sadly is for this buffer only, when opening another template file I get yamlls attached too and have to restart LSP for this buffer.
![image](https://github.com/user-attachments/assets/cd2b35d1-0d37-4296-80aa-36b934a848d7)

This is really weird, but I think I can deal with a autocmd to restart LSP when opening a yaml file

**Comment by samos667** [comment]
Yeah a simply autocmd make the job !
```nix
{
  autoCmd = [
    {
      event = "FileType";
      pattern = "helm";
      command = "LspRestart";
    }
  ];
}
```

**Comment by GaetanLepage** [comment]
Should we do something extra in nixvim ?
Is @samos667 's fix worth documenting ?

Otherwise, let's close this issue.

**Comment by samos667** [comment]
Yes, I think this is a good knowledge for all peoples who want to use helmls

**Comment by GaetanLepage** [comment]
> Yes, I think this is a good knowledge for all peoples who want to use helmls

Opened https://github.com/nix-community/nixvim/pull/2502, do not hesitate to propose a better wording.

**Comment by faizm55212** [comment]
Hey,

I was running into the same issue even after trying the suggested solution of using vim-helm along with an autocmd for `:LspRestart`, I still had to manually re-trigger `:LspRestart`, which ended up spawning multiple instances of helm-ls, all attaching to every open buffer.

What worked for me was adding extra filetype patterns directly in the Neovim config. This seems to fix the issue:
```nix
programs.nixvim = {
  enable = true;
  filetype.pattern = {
    ".*/templates/.*%.yaml" = "helm";
    ".*/templates/.*%.yml" = "helm";
  };
};
```
I’ve now removed `vim-helm` and `filetypes = [ ]` setting for both `yamlls` and `helm-ls`, and it still works fine for me,
Please let me know if there are any downsides to using this approach instead, so far, it seems to work fine even without the plugin.
