### ISSUE TITLE
[PLUGIN REQUEST] CopilotChat.nvim

### ISSUE THREAD

**Issue by SchnozzleCat** [nix-community/nixvim#992]
| Field    | Description |
|----------|-------------|
| Plugin   | `CopilotChat.nvim`  | 
| Homepage | `https://github.com/jellydn/CopilotChat.nvim`     | 
| Nixpkgs  | `false` | 

## Extra Information

Newer features are only present in the separate ``canary`` branch.

Requires four python packages from ``requirements.txt``, all of which are present in nixpkgs.

```
python-dotenv
requests
pynvim==0.5.0
prompt-toolkit
```

Nixpkgs stable has 0.4.3 of pynvim, unstable is at 0.5.0.

This is a fork by jellydn based off of [this](https://github.com/gptlang/CopilotChat.nvim), but the original author also uses this fork now as it is more well maintained.

**Comment by hyshka** [comment]
Homepage moved to: https://github.com/CopilotC-Nvim/CopilotChat.nvim

**Comment by MattSturgeon** [comment]
> I have added a PR in Nixpkgs to add the plugin: [NixOS/nixpkgs#310697](https://github.com/NixOS/nixpkgs/pull/310697)

https://github.com/nix-community/nixvim/issues/1425#issuecomment-2109445837 by https://github.com/MikaelFangel
